// Removes everything a build produces, so the next build starts from scratch.
//
//   npm run clean            build output, generated assets and the installers
//                            copied to the project root
//   npm run clean:all        the above + node_modules/ (full reset; the next
//                            build reinstalls it via scripts/ensure-deps.mjs)
//   npm run clean -- --dry-run   list what would be removed, delete nothing
//
// Everything listed here is git-ignored and regenerated by `npm install` or
// `npm run build:*`. Nothing tracked by git is touched - in particular
// public/icon.svg and public/file-icon.svg, which are copies of assets/*.svg
// but are committed on purpose so a fresh clone can render the welcome screen.
//
// Usage: node scripts/clean.mjs [--all] [--dry-run]
import { existsSync, readdirSync, rmSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const all = args.includes('--all');
const dryRun = args.includes('--dry-run') || args.includes('-n');

// Installer files that postbuild:* copies from release/ to the project root.
const installerExt = /\.(exe|dmg|AppImage|deb|rpm|zip|snap|blockmap)$/i;

const targets = [
  ['dist', 'web bundle (npm run build)'],
  ['release', 'electron-builder output'],
  ['build/icons', 'icons generated from assets/*.svg'],
  ['public/pdfjs', 'pdf.js runtime copied from pdfjs-dist'],
  ['src/build-info.json', 'build stamp (version, time, commit)'],
  ['node_modules/.vite', 'Vite dependency cache'],
  ['.vite', 'Vite cache'],
  ['coverage', 'test coverage report'],
  ['.vitest', 'Vitest cache'],
];

// Installers sitting in the project root, listed by name so the output says
// exactly which file goes.
for (const name of existsSync(rootDir) ? readdirSync(rootDir) : []) {
  if (installerExt.test(name)) targets.push([name, 'installer copied to the project root']);
}

if (all) targets.push(['node_modules', 'installed dependencies']);

function sizeOf(path) {
  try {
    const st = statSync(path);
    if (!st.isDirectory()) return st.size;
    let total = 0;
    for (const entry of readdirSync(path, { withFileTypes: true })) {
      if (entry.isSymbolicLink()) continue;
      total += sizeOf(join(path, entry.name));
    }
    return total;
  } catch {
    return 0;   // unreadable entries just do not count towards the total
  }
}

const mb = (bytes) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;

let removed = 0;
let freed = 0;
let failed = 0;

for (const [rel, why] of targets) {
  const path = resolve(rootDir, rel);
  // Never step outside the project, whatever ends up in the list.
  if (path !== rootDir && !path.startsWith(rootDir + sep)) continue;
  if (!existsSync(path)) continue;

  const bytes = sizeOf(path);
  const label = `${relative(rootDir, path).split(sep).join('/')}  (${why}, ${mb(bytes)})`;

  if (dryRun) {
    console.log(`[clean] would remove ${label}`);
    removed++;
    freed += bytes;
    continue;
  }
  try {
    rmSync(path, { recursive: true, force: true, maxRetries: 3, retryDelay: 200 });
    console.log(`[clean] removed ${label}`);
    removed++;
    freed += bytes;
  } catch (err) {
    // On Windows a running app or an open Explorer window keeps a handle open.
    console.error(`[clean] could not remove ${label}: ${err.message}`);
    failed++;
  }
}

if (!removed && !failed) {
  console.log('[clean] Nothing to remove - already clean.');
} else {
  console.log(dryRun
    ? `[clean] ${removed} item(s), ${mb(freed)} would be removed. Run without --dry-run to delete.`
    : `[clean] ${removed} item(s) removed, ${mb(freed)} freed.`);
  if (!all && !dryRun) console.log('[clean] node_modules/ kept - use "npm run clean:all" to remove it too.');
}

if (failed) {
  console.error(`[clean] ${failed} item(s) could not be removed - close the app or Explorer windows using them and retry.`);
  process.exit(1);
}
