const LIGHT_SHADOW = '0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)';
const LIGHT_SHADOW_LG = '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)';

export const themes = {
  default: {
    preview: ['#1e3a5f', '#3b82f6'],
    '--bg-primary': '#f0f4f8',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#1e3a5f',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#e2e8f0',
    '--accent': '#3b82f6',
    '--accent-hover': '#2563eb',
    '--accent-light': '#dbeafe',
    '--border': '#e2e8f0',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  dark: {
    preview: ['#020617', '#60a5fa'],
    '--bg-primary': '#0f172a',
    '--bg-secondary': '#1e293b',
    '--bg-sidebar': '#020617',
    '--bg-card': '#1e293b',
    '--text-primary': '#f1f5f9',
    '--text-secondary': '#94a3b8',
    '--text-sidebar': '#cbd5e1',
    '--accent': '#60a5fa',
    '--accent-hover': '#3b82f6',
    '--accent-light': '#1e3a5f',
    '--border': '#334155',
    '--success': '#34d399',
    '--warning': '#fbbf24',
    '--danger': '#f87171',
    '--shadow': '0 1px 3px rgba(0,0,0,0.3)',
    '--shadow-lg': '0 10px 15px -3px rgba(0,0,0,0.4)',
    '--radius': '12px',
  },
  graphite: {
    preview: ['#09090b', '#a78bfa'],
    '--bg-primary': '#18181b',
    '--bg-secondary': '#27272a',
    '--bg-sidebar': '#09090b',
    '--bg-card': '#27272a',
    '--text-primary': '#fafafa',
    '--text-secondary': '#a1a1aa',
    '--text-sidebar': '#d4d4d8',
    '--accent': '#a78bfa',
    '--accent-hover': '#8b5cf6',
    '--accent-light': '#3f3f46',
    '--border': '#3f3f46',
    '--success': '#4ade80',
    '--warning': '#fbbf24',
    '--danger': '#f87171',
    '--shadow': '0 1px 3px rgba(0,0,0,0.35)',
    '--shadow-lg': '0 10px 15px -3px rgba(0,0,0,0.45)',
    '--radius': '12px',
  },
  emerald: {
    preview: ['#064e3b', '#10b981'],
    '--bg-primary': '#ecfdf5',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#064e3b',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#d1fae5',
    '--accent': '#10b981',
    '--accent-hover': '#059669',
    '--accent-light': '#d1fae5',
    '--border': '#a7f3d0',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  teal: {
    preview: ['#134e4a', '#14b8a6'],
    '--bg-primary': '#f0fdfa',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#134e4a',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#ccfbf1',
    '--accent': '#14b8a6',
    '--accent-hover': '#0d9488',
    '--accent-light': '#ccfbf1',
    '--border': '#99f6e4',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  ocean: {
    preview: ['#164e63', '#06b6d4'],
    '--bg-primary': '#ecfeff',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#164e63',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#cffafe',
    '--accent': '#06b6d4',
    '--accent-hover': '#0891b2',
    '--accent-light': '#cffafe',
    '--border': '#a5f3fc',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  indigo: {
    preview: ['#312e81', '#6366f1'],
    '--bg-primary': '#eef2ff',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#312e81',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#e0e7ff',
    '--accent': '#6366f1',
    '--accent-hover': '#4f46e5',
    '--accent-light': '#e0e7ff',
    '--border': '#c7d2fe',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  purple: {
    preview: ['#4c1d95', '#8b5cf6'],
    '--bg-primary': '#faf5ff',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#4c1d95',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#e9d5ff',
    '--accent': '#8b5cf6',
    '--accent-hover': '#7c3aed',
    '--accent-light': '#ede9fe',
    '--border': '#ddd6fe',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  rose: {
    preview: ['#881337', '#f43f5e'],
    '--bg-primary': '#fff1f2',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#881337',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#ffe4e6',
    '--accent': '#f43f5e',
    '--accent-hover': '#e11d48',
    '--accent-light': '#ffe4e6',
    '--border': '#fecdd3',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  crimson: {
    preview: ['#7f1d1d', '#dc2626'],
    '--bg-primary': '#fef2f2',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#7f1d1d',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#fecaca',
    '--accent': '#dc2626',
    '--accent-hover': '#b91c1c',
    '--accent-light': '#fee2e2',
    '--border': '#fecaca',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  sunset: {
    preview: ['#7c2d12', '#f97316'],
    '--bg-primary': '#fff7ed',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#7c2d12',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#fed7aa',
    '--accent': '#f97316',
    '--accent-hover': '#ea580c',
    '--accent-light': '#ffedd5',
    '--border': '#fed7aa',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  amber: {
    preview: ['#78350f', '#f59e0b'],
    '--bg-primary': '#fffbeb',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#78350f',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#fde68a',
    '--accent': '#f59e0b',
    '--accent-hover': '#d97706',
    '--accent-light': '#fef3c7',
    '--border': '#fde68a',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  slate: {
    preview: ['#334155', '#0ea5e9'],
    '--bg-primary': '#f8fafc',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#334155',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#e2e8f0',
    '--accent': '#0ea5e9',
    '--accent-hover': '#0284c7',
    '--accent-light': '#e0f2fe',
    '--border': '#cbd5e1',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
  coffee: {
    preview: ['#44403c', '#a16207'],
    '--bg-primary': '#faf8f5',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#44403c',
    '--bg-card': '#ffffff',
    '--text-primary': '#1c1917',
    '--text-secondary': '#78716c',
    '--text-sidebar': '#e7e5e4',
    '--accent': '#a16207',
    '--accent-hover': '#854d0e',
    '--accent-light': '#fef3c7',
    '--border': '#d6d3d1',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': LIGHT_SHADOW,
    '--shadow-lg': LIGHT_SHADOW_LG,
    '--radius': '12px',
  },
};

export function applyTheme(themeName) {
  const theme = themes[themeName] || themes.default;
  const root = document.documentElement;
  Object.entries(theme).forEach(([key, value]) => {
    if (key.startsWith('--')) root.style.setProperty(key, value);
  });
}

export function normalizeTheme(themeName) {
  return themes[themeName] ? themeName : 'default';
}

export function getThemePreview(themeName) {
  return themes[themeName]?.preview ?? themes.default.preview;
}
