export const themes = {
  default: {
    name: 'default',
    '--bg-primary': '#f0f4f8',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#1e3a5f',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#e2e8f0',
    '--accent': '#3b82f6',
    '--accent-hover': '#2563eb',
    '--accent-light': '#dbeafe',
    '--border': '#e2e8f0',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': '0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)',
    '--shadow-lg': '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)',
    '--radius': '12px',
  },
  dark: {
    name: 'dark',
    '--bg-primary': '#0f172a',
    '--bg-secondary': '#1e293b',
    '--bg-sidebar': '#020617',
    '--bg-card': '#1e293b',
    '--text-primary': '#f1f5f9',
    '--text-secondary': '#94a3b8',
    '--text-sidebar': '#cbd5e1',
    '--accent': '#60a5fa',
    '--accent-hover': '#3b82f6',
    '--accent-light': '#1e3a5f',
    '--border': '#334155',
    '--success': '#34d399',
    '--warning': '#fbbf24',
    '--danger': '#f87171',
    '--shadow': '0 1px 3px rgba(0,0,0,0.3)',
    '--shadow-lg': '0 10px 15px -3px rgba(0,0,0,0.4)',
    '--radius': '12px',
  },
  emerald: {
    name: 'emerald',
    '--bg-primary': '#ecfdf5',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#064e3b',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#d1fae5',
    '--accent': '#10b981',
    '--accent-hover': '#059669',
    '--accent-light': '#d1fae5',
    '--border': '#a7f3d0',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': '0 1px 3px rgba(0,0,0,0.1)',
    '--shadow-lg': '0 10px 15px -3px rgba(0,0,0,0.1)',
    '--radius': '12px',
  },
  sunset: {
    name: 'sunset',
    '--bg-primary': '#fff7ed',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#7c2d12',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#fed7aa',
    '--accent': '#f97316',
    '--accent-hover': '#ea580c',
    '--accent-light': '#ffedd5',
    '--border': '#fed7aa',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': '0 1px 3px rgba(0,0,0,0.1)',
    '--shadow-lg': '0 10px 15px -3px rgba(0,0,0,0.1)',
    '--radius': '12px',
  },
  purple: {
    name: 'purple',
    '--bg-primary': '#faf5ff',
    '--bg-secondary': '#ffffff',
    '--bg-sidebar': '#4c1d95',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a202c',
    '--text-secondary': '#64748b',
    '--text-sidebar': '#e9d5ff',
    '--accent': '#8b5cf6',
    '--accent-hover': '#7c3aed',
    '--accent-light': '#ede9fe',
    '--border': '#ddd6fe',
    '--success': '#10b981',
    '--warning': '#f59e0b',
    '--danger': '#ef4444',
    '--shadow': '0 1px 3px rgba(0,0,0,0.1)',
    '--shadow-lg': '0 10px 15px -3px rgba(0,0,0,0.1)',
    '--radius': '12px',
  },
};

export function applyTheme(themeName) {
  const theme = themes[themeName] || themes.default;
  const root = document.documentElement;
  Object.entries(theme).forEach(([key, value]) => {
    if (key.startsWith('--')) root.style.setProperty(key, value);
  });
}

export function normalizeTheme(themeName) {
  return themes[themeName] ? themeName : 'default';
}
