import type { Language } from "./messages";

export interface Country {
  code: string;
  en: string;
  ko: string;
}

const RAW = [
  ["AD", "Andorra", "안도라"],
  ["AL", "Albania", "알바니아"],
  ["AM", "Armenia", "아르메니아"],
  ["AR", "Argentina", "아르헨티나"],
  ["AT", "Austria", "오스트리아"],
  ["AU", "Australia", "오스트레일리아"],
  ["AX", "Åland Islands", "올란드 제도"],
  ["BA", "Bosnia and Herzegovina", "보스니아 헤르체고비나"],
  ["BB", "Barbados", "바베이도스"],
  ["BD", "Bangladesh", "방글라데시"],
  ["BE", "Belgium", "벨기에"],
  ["BG", "Bulgaria", "불가리아"],
  ["BJ", "Benin", "베냉"],
  ["BO", "Bolivia", "볼리비아"],
  ["BR", "Brazil", "브라질"],
  ["BS", "Bahamas", "바하마"],
  ["BW", "Botswana", "보츠와나"],
  ["BY", "Belarus", "벨라루스"],
  ["BZ", "Belize", "벨리즈"],
  ["CA", "Canada", "캐나다"],
  ["CH", "Switzerland", "스위스"],
  ["CL", "Chile", "칠레"],
  ["CN", "China", "중국"],
  ["CO", "Colombia", "콜롬비아"],
  ["CR", "Costa Rica", "코스타리카"],
  ["CU", "Cuba", "쿠바"],
  ["CY", "Cyprus", "키프로스"],
  ["CZ", "Czechia", "체코"],
  ["DE", "Germany", "독일"],
  ["DK", "Denmark", "덴마크"],
  ["DO", "Dominican Republic", "도미니카 공화국"],
  ["EC", "Ecuador", "에콰도르"],
  ["EE", "Estonia", "에스토니아"],
  ["EG", "Egypt", "이집트"],
  ["ES", "Spain", "스페인"],
  ["FI", "Finland", "핀란드"],
  ["FJ", "Fiji", "피지"],
  ["FR", "France", "프랑스"],
  ["GA", "Gabon", "가봉"],
  ["GB", "United Kingdom", "영국"],
  ["GD", "Grenada", "그레나다"],
  ["GE", "Georgia", "조지아"],
  ["GG", "Guernsey", "건지"],
  ["GI", "Gibraltar", "지브롤터"],
  ["GM", "Gambia", "감비아"],
  ["GR", "Greece", "그리스"],
  ["GT", "Guatemala", "과테말라"],
  ["GY", "Guyana", "가이아나"],
  ["HN", "Honduras", "온두라스"],
  ["HR", "Croatia", "크로아티아"],
  ["HT", "Haiti", "아이티"],
  ["HU", "Hungary", "헝가리"],
  ["ID", "Indonesia", "인도네시아"],
  ["IE", "Ireland", "아일랜드"],
  ["IM", "Isle of Man", "맨섬"],
  ["IS", "Iceland", "아이슬란드"],
  ["IT", "Italy", "이탈리아"],
  ["JE", "Jersey", "저지"],
  ["JM", "Jamaica", "자메이카"],
  ["JP", "Japan", "일본"],
  ["KR", "South Korea", "대한민국"],
  ["KZ", "Kazakhstan", "카자흐스탄"],
  ["LI", "Liechtenstein", "리히텐슈타인"],
  ["LS", "Lesotho", "레소토"],
  ["LT", "Lithuania", "리투아니아"],
  ["LU", "Luxembourg", "룩셈부르크"],
  ["LV", "Latvia", "라트비아"],
  ["MA", "Morocco", "모로코"],
  ["MC", "Monaco", "모나코"],
  ["MD", "Moldova", "몰도바"],
  ["ME", "Montenegro", "몬테네그로"],
  ["MG", "Madagascar", "마다가스카르"],
  ["MK", "North Macedonia", "북마케도니아"],
  ["MN", "Mongolia", "몽골"],
  ["MT", "Malta", "몰타"],
  ["MX", "Mexico", "멕시코"],
  ["MZ", "Mozambique", "모잠비크"],
  ["NA", "Namibia", "나미비아"],
  ["NE", "Niger", "니제르"],
  ["NG", "Nigeria", "나이지리아"],
  ["NI", "Nicaragua", "니카라과"],
  ["NL", "Netherlands", "네덜란드"],
  ["NO", "Norway", "노르웨이"],
  ["NZ", "New Zealand", "뉴질랜드"],
  ["PA", "Panama", "파나마"],
  ["PE", "Peru", "페루"],
  ["PG", "Papua New Guinea", "파푸아뉴기니"],
  ["PL", "Poland", "폴란드"],
  ["PR", "Puerto Rico", "푸에르토리코"],
  ["PT", "Portugal", "포르투갈"],
  ["PY", "Paraguay", "파라과이"],
  ["RO", "Romania", "루마니아"],
  ["RS", "Serbia", "세르비아"],
  ["RU", "Russia", "러시아"],
  ["SE", "Sweden", "스웨덴"],
  ["SG", "Singapore", "싱가포르"],
  ["SI", "Slovenia", "슬로베니아"],
  ["SJ", "Svalbard and Jan Mayen", "스발바르 얀마옌"],
  ["SK", "Slovakia", "슬로바키아"],
  ["SM", "San Marino", "산마리노"],
  ["SR", "Suriname", "수리남"],
  ["SV", "El Salvador", "엘살바도르"],
  ["TN", "Tunisia", "튀니지"],
  ["TR", "Türkiye", "튀르키예"],
  ["UA", "Ukraine", "우크라이나"],
  ["US", "United States", "미국"],
  ["UY", "Uruguay", "우루과이"],
  ["VA", "Vatican City", "바티칸"],
  ["VE", "Venezuela", "베네수엘라"],
  ["VN", "Vietnam", "베트남"],
  ["ZA", "South Africa", "남아프리카 공화국"],
  ["ZW", "Zimbabwe", "짐바브웨"],
] as const;

export const FALLBACK_COUNTRIES: Country[] = RAW.map(([code, en, ko]) => ({ code, en, ko }));

export const KOREAN_COUNTRY_NAMES: Record<string, string> = Object.fromEntries(
  RAW.map(([code, , ko]) => [code, ko]),
);

export function countryName(country: Country, language: Language): string {
  return language === "ko" ? country.ko : country.en;
}

export function sortCountries(countries: Country[], language: Language): Country[] {
  const locale = language === "ko" ? "ko" : "en";
  return [...countries].sort((a, b) => countryName(a, language).localeCompare(countryName(b, language), locale));
}
