import type { Language } from "./messages";

export interface Country {
  code: string;
  en: string;
  ko: string;
}

const RAW = [
  ["AD", "Andorra", "안도라"],
  ["AE", "United Arab Emirates", "아랍에미리트"],
  ["AG", "Antigua and Barbuda", "앤티가 바부다"],
  ["AI", "Anguilla", "앵귈라"],
  ["AL", "Albania", "알바니아"],
  ["AM", "Armenia", "아르메니아"],
  ["AO", "Angola", "앙골라"],
  ["AR", "Argentina", "아르헨티나"],
  ["AS", "American Samoa", "아메리칸 사모아"],
  ["AT", "Austria", "오스트리아"],
  ["AU", "Australia", "오스트레일리아"],
  ["AW", "Aruba", "아루바"],
  ["AX", "Åland Islands", "올란드 제도"],
  ["AZ", "Azerbaijan", "아제르바이잔"],
  ["BA", "Bosnia and Herzegovina", "보스니아 헤르체고비나"],
  ["BB", "Barbados", "바베이도스"],
  ["BD", "Bangladesh", "방글라데시"],
  ["BE", "Belgium", "벨기에"],
  ["BF", "Burkina Faso", "부르키나파소"],
  ["BG", "Bulgaria", "불가리아"],
  ["BH", "Bahrain", "바레인"],
  ["BI", "Burundi", "부룬디"],
  ["BJ", "Benin", "베냉"],
  ["BL", "Saint Barthélemy", "생바르텔레미"],
  ["BM", "Bermuda", "버뮤다"],
  ["BN", "Brunei", "브루나이"],
  ["BO", "Bolivia", "볼리비아"],
  ["BQ", "Caribbean Netherlands", "카리브 네덜란드"],
  ["BR", "Brazil", "브라질"],
  ["BS", "Bahamas", "바하마"],
  ["BW", "Botswana", "보츠와나"],
  ["BY", "Belarus", "벨라루스"],
  ["BZ", "Belize", "벨리즈"],
  ["CA", "Canada", "캐나다"],
  ["CC", "Cocos (Keeling) Islands", "코코스 제도"],
  ["CD", "Democratic Republic of the Congo", "콩고 민주 공화국"],
  ["CF", "Central African Republic", "중앙아프리카 공화국"],
  ["CG", "Republic of the Congo", "콩고 공화국"],
  ["CH", "Switzerland", "스위스"],
  ["CI", "Côte d'Ivoire", "코트디부아르"],
  ["CK", "Cook Islands", "쿡 제도"],
  ["CL", "Chile", "칠레"],
  ["CM", "Cameroon", "카메룬"],
  ["CN", "China", "중국"],
  ["CO", "Colombia", "콜롬비아"],
  ["CR", "Costa Rica", "코스타리카"],
  ["CU", "Cuba", "쿠바"],
  ["CV", "Cape Verde", "카보베르데"],
  ["CW", "Curaçao", "퀴라소"],
  ["CX", "Christmas Island", "크리스마스섬"],
  ["CY", "Cyprus", "키프로스"],
  ["CZ", "Czechia", "체코"],
  ["DE", "Germany", "독일"],
  ["DJ", "Djibouti", "지부티"],
  ["DK", "Denmark", "덴마크"],
  ["DM", "Dominica", "도미니카"],
  ["DO", "Dominican Republic", "도미니카 공화국"],
  ["DZ", "Algeria", "알제리"],
  ["EC", "Ecuador", "에콰도르"],
  ["EE", "Estonia", "에스토니아"],
  ["EG", "Egypt", "이집트"],
  ["EH", "Western Sahara", "서사하라"],
  ["ER", "Eritrea", "에리트리아"],
  ["ES", "Spain", "스페인"],
  ["ET", "Ethiopia", "에티오피아"],
  ["FI", "Finland", "핀란드"],
  ["FJ", "Fiji", "피지"],
  ["FK", "Falkland Islands", "포클랜드 제도"],
  ["FM", "Micronesia", "미크로네시아"],
  ["FO", "Faroe Islands", "페로 제도"],
  ["FR", "France", "프랑스"],
  ["GA", "Gabon", "가봉"],
  ["GB", "United Kingdom", "영국"],
  ["GD", "Grenada", "그레나다"],
  ["GE", "Georgia", "조지아"],
  ["GF", "French Guiana", "프랑스령 기아나"],
  ["GG", "Guernsey", "건지"],
  ["GH", "Ghana", "가나"],
  ["GI", "Gibraltar", "지브롤터"],
  ["GL", "Greenland", "그린란드"],
  ["GM", "Gambia", "감비아"],
  ["GN", "Guinea", "기니"],
  ["GP", "Guadeloupe", "과들루프"],
  ["GQ", "Equatorial Guinea", "적도 기니"],
  ["GR", "Greece", "그리스"],
  ["GT", "Guatemala", "과테말라"],
  ["GU", "Guam", "괌"],
  ["GW", "Guinea-Bissau", "기니비사우"],
  ["GY", "Guyana", "가이아나"],
  ["HK", "Hong Kong", "홍콩"],
  ["HN", "Honduras", "온두라스"],
  ["HR", "Croatia", "크로아티아"],
  ["HT", "Haiti", "아이티"],
  ["HU", "Hungary", "헝가리"],
  ["IC", "Canary Islands", "카나리아 제도"],
  ["ID", "Indonesia", "인도네시아"],
  ["IE", "Ireland", "아일랜드"],
  ["IL", "Israel", "이스라엘"],
  ["IM", "Isle of Man", "맨섬"],
  ["IN", "India", "인도"],
  ["IQ", "Iraq", "이라크"],
  ["IR", "Iran", "이란"],
  ["IS", "Iceland", "아이슬란드"],
  ["IT", "Italy", "이탈리아"],
  ["JE", "Jersey", "저지"],
  ["JM", "Jamaica", "자메이카"],
  ["JP", "Japan", "일본"],
  ["KE", "Kenya", "케냐"],
  ["KH", "Cambodia", "캄보디아"],
  ["KI", "Kiribati", "키리바시"],
  ["KM", "Comoros", "코모로"],
  ["KN", "Saint Kitts and Nevis", "세인트키츠 네비스"],
  ["KR", "South Korea", "대한민국"],
  ["KY", "Cayman Islands", "케이맨 제도"],
  ["KZ", "Kazakhstan", "카자흐스탄"],
  ["LC", "Saint Lucia", "세인트루시아"],
  ["LI", "Liechtenstein", "리히텐슈타인"],
  ["LK", "Sri Lanka", "스리랑카"],
  ["LR", "Liberia", "라이베리아"],
  ["LS", "Lesotho", "레소토"],
  ["LT", "Lithuania", "리투아니아"],
  ["LU", "Luxembourg", "룩셈부르크"],
  ["LV", "Latvia", "라트비아"],
  ["LY", "Libya", "리비아"],
  ["MA", "Morocco", "모로코"],
  ["MC", "Monaco", "모나코"],
  ["MD", "Moldova", "몰도바"],
  ["ME", "Montenegro", "몬테네그로"],
  ["MF", "Saint Martin", "생마르탱"],
  ["MG", "Madagascar", "마다가스카르"],
  ["MH", "Marshall Islands", "마셜 제도"],
  ["MK", "North Macedonia", "북마케도니아"],
  ["ML", "Mali", "말리"],
  ["MN", "Mongolia", "몽골"],
  ["MP", "Northern Mariana Islands", "북마리아나 제도"],
  ["MQ", "Martinique", "마르티니크"],
  ["MR", "Mauritania", "모리타니"],
  ["MS", "Montserrat", "몬트세라트"],
  ["MT", "Malta", "몰타"],
  ["MU", "Mauritius", "모리셔스"],
  ["MW", "Malawi", "말라위"],
  ["MX", "Mexico", "멕시코"],
  ["MY", "Malaysia", "말레이시아"],
  ["MZ", "Mozambique", "모잠비크"],
  ["NA", "Namibia", "나미비아"],
  ["NC", "New Caledonia", "뉴칼레도니아"],
  ["NE", "Niger", "니제르"],
  ["NF", "Norfolk Island", "노퍽섬"],
  ["NG", "Nigeria", "나이지리아"],
  ["NI", "Nicaragua", "니카라과"],
  ["NL", "Netherlands", "네덜란드"],
  ["NO", "Norway", "노르웨이"],
  ["NR", "Nauru", "나우루"],
  ["NU", "Niue", "니우에"],
  ["NZ", "New Zealand", "뉴질랜드"],
  ["PA", "Panama", "파나마"],
  ["PE", "Peru", "페루"],
  ["PF", "French Polynesia", "프랑스령 폴리네시아"],
  ["PG", "Papua New Guinea", "파푸아뉴기니"],
  ["PH", "Philippines", "필리핀"],
  ["PK", "Pakistan", "파키스탄"],
  ["PL", "Poland", "폴란드"],
  ["PM", "Saint Pierre and Miquelon", "생피에르 미클롱"],
  ["PN", "Pitcairn Islands", "핏케언 제도"],
  ["PR", "Puerto Rico", "푸에르토리코"],
  ["PT", "Portugal", "포르투갈"],
  ["PW", "Palau", "팔라우"],
  ["PY", "Paraguay", "파라과이"],
  ["RE", "Réunion", "레위니옹"],
  ["RO", "Romania", "루마니아"],
  ["RS", "Serbia", "세르비아"],
  ["RU", "Russia", "러시아"],
  ["RW", "Rwanda", "르완다"],
  ["SA", "Saudi Arabia", "사우디아라비아"],
  ["SB", "Solomon Islands", "솔로몬 제도"],
  ["SC", "Seychelles", "세이셸"],
  ["SD", "Sudan", "수단"],
  ["SE", "Sweden", "스웨덴"],
  ["SG", "Singapore", "싱가포르"],
  ["SH", "Saint Helena", "세인트헬레나"],
  ["SI", "Slovenia", "슬로베니아"],
  ["SJ", "Svalbard and Jan Mayen", "스발바르 얀마옌"],
  ["SK", "Slovakia", "슬로바키아"],
  ["SL", "Sierra Leone", "시에라리온"],
  ["SM", "San Marino", "산마리노"],
  ["SN", "Senegal", "세네갈"],
  ["SO", "Somalia", "소말리아"],
  ["SR", "Suriname", "수리남"],
  ["SS", "South Sudan", "남수단"],
  ["ST", "São Tomé and Príncipe", "상투메 프린시페"],
  ["SV", "El Salvador", "엘살바도르"],
  ["SX", "Sint Maarten", "신트마르턴"],
  ["SY", "Syria", "시리아"],
  ["SZ", "Eswatini", "에스와티니"],
  ["TC", "Turks and Caicos Islands", "터크스 케이커스 제도"],
  ["TD", "Chad", "차드"],
  ["TG", "Togo", "토고"],
  ["TH", "Thailand", "태국"],
  ["TK", "Tokelau", "토켈라우"],
  ["TN", "Tunisia", "튀니지"],
  ["TO", "Tonga", "통가"],
  ["TR", "Türkiye", "튀르키예"],
  ["TT", "Trinidad and Tobago", "트리니다드 토바고"],
  ["TV", "Tuvalu", "투발루"],
  ["TW", "Taiwan", "대만"],
  ["TZ", "Tanzania", "탄자니아"],
  ["UA", "Ukraine", "우크라이나"],
  ["UG", "Uganda", "우간다"],
  ["US", "United States", "미국"],
  ["UY", "Uruguay", "우루과이"],
  ["UZ", "Uzbekistan", "우즈베키스탄"],
  ["VA", "Vatican City", "바티칸"],
  ["VC", "Saint Vincent and the Grenadines", "세인트빈센트그레나딘"],
  ["VE", "Venezuela", "베네수엘라"],
  ["VG", "British Virgin Islands", "영국령 버진아일랜드"],
  ["VI", "U.S. Virgin Islands", "미국령 버진아일랜드"],
  ["VN", "Vietnam", "베트남"],
  ["VU", "Vanuatu", "바누아투"],
  ["WF", "Wallis and Futuna", "왈리스 푸투나"],
  ["WS", "Samoa", "사모아"],
  ["XK", "Kosovo", "코소보"],
  ["YE", "Yemen", "예멘"],
  ["YT", "Mayotte", "마요트"],
  ["ZA", "South Africa", "남아프리카 공화국"],
  ["ZM", "Zambia", "잠비아"],
  ["ZW", "Zimbabwe", "짐바브웨"],
] as const;

export const FALLBACK_COUNTRIES: Country[] = RAW.map(([code, en, ko]) => ({ code, en, ko }));

const BY_CODE = new Map<string, Country>(FALLBACK_COUNTRIES.map((country) => [country.code, country]));

function regionName(code: string, language: Language): string | null {
  try {
    const name = new Intl.DisplayNames([language], { type: "region" }).of(code);
    return name && name !== code ? name : null;
  } catch {
    return null;
  }
}

/**
 * English and Korean names for a country code. Every country the live feed or the built-in rules know is listed
 * above; anything newer gets the system's name for that language, or the code, so one language never borrows the
 * other's name.
 */
export function countryFor(code: string): Country {
  const known = BY_CODE.get(code);
  if (known) return known;
  const ko = regionName(code, "ko");
  const en = regionName(code, "en");
  return {
    code,
    en: en && !/[\uac00-\ud7a3]/.test(en) ? en : code,
    ko: ko && /[\uac00-\ud7a3]/.test(ko) ? ko : code,
  };
}

export function countryName(country: Country, language: Language): string {
  return language === "ko" ? country.ko : country.en;
}

export function sortCountries(countries: Country[], language: Language): Country[] {
  const locale = language === "ko" ? "ko" : "en";
  return [...countries].sort((a, b) => countryName(a, language).localeCompare(countryName(b, language), locale));
}
