import type { Messages } from "./messages";

export const en: Messages = {
  appName: "My Calendar",
  tagline: "A transparent calendar for your desktop",
  today: "Today",
  settings: "Settings",
  about: "About",
  hide: "Hide to tray",
  close: "Close",
  quit: "Quit",
  showHide: "Show / Hide calendar",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  transparency: "Transparency",
  transparencyHint: "A higher value makes the background more transparent.",
  theme: "Theme",
  light: "Light",
  dark: "Dark",
  language: "Language",
  country: "Holiday country",
  countryHint: "Public holidays for the selected country are checked on the internet.",
  searchCountry: "Search countries",
  noCountry: "No matching country",
  weekStart: "First day of the week",
  sunday: "Sunday",
  monday: "Monday",
  alwaysOnTop: "Keep the calendar above other windows",
  autostart: "Launch when the system starts",
  desktopOnly: "Available in the desktop app.",
  refreshHolidays: "Check holidays again",
  holidayLive: "Checked live",
  holidayCached: "Showing the last check",
  holidayError: "Could not check holidays",
  checkedAt: "Checked {time}",
  checking: "Checking holidays…",
  noHoliday: "No public holiday",
  aboutBody: "A frameless transparent calendar that lives on the desktop and in the system tray.",
  aboutPlatformsLabel: "Platforms",
  aboutPlatforms: "Web, Linux, macOS, Windows",
  aboutHolidaySource: "Public holidays are loaded live from Nager.Date.",
  holidaySourceLink: "date.nager.at",
  version: "Version",
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  trayTooltip: "My Calendar",
  webBanner:
    "The browser can use the calendar, themes, transparency, and holidays. The system tray and launch-at-startup run in the desktop app.",
  featuresTitle: "Included",
  featureTransparent: "Adjustable transparent background",
  featureThemes: "20 light themes and 20 dark themes",
  featureHolidays: "Live public holidays by country",
  featurePlatforms: "Web, Linux, macOS, and Windows",
  featureTray: "System tray, with no title bar",
  closeToTray: "Closing the window keeps the app in the tray.",
  appearance: "Appearance",
  holidaysSection: "Holidays",
  general: "General",
  countriesLive: "Country list checked online",
  countriesFallback: "Offline country list",
  countriesLoading: "Checking the country list…",
  installLanguageHelp:
    "The Windows installer asks you to choose Korean or English. The Linux and macOS install scripts ask as well. The web app asks the first time it opens.",
  openSourcePage: "Open holiday source",
  aboutDataNote:
    "Korean uses each country's local holiday name. English uses the English name.",
  startup: "Startup",
  monthHolidays: "Holidays this month",
};
