import type { Messages } from "./messages";

export const en: Messages = {
  appName: "My Calendar",
  tagline: "A transparent calendar for your desktop",
  today: "Today",
  settings: "Settings",
  about: "About",
  aboutTab: "About",
  backgroundTab: "Background",
  hide: "Hide to tray",
  minimize: "Minimize",
  maximize: "Maximize",
  restore: "Restore down",
  close: "Close",
  quit: "Quit",
  showHide: "Show / Hide calendar",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  transparency: "Transparency",
  transparencyHint: "A higher value makes the background more transparent.",
  monthTitleFormat: "Year and month",
  monthTitleFormatHint: "How the calendar's title bar writes the year and month. Korean and English each keep their own choice. A shorter format lets the window get narrower.",
  backgroundImage: "Background image",
  chooseBackgroundImage: "Choose image…",
  changeBackgroundImage: "Change image…",
  removeBackgroundImage: "Remove",
  noBackgroundImage: "None",
  backgroundImageTransparency: "Background image transparency",
  backgroundImageTransparencyHint: "A higher value makes the background image more transparent.",
  backgroundImageHint: "The background image goes behind the calendar window only. Large images are scaled down when saved.",
  backgroundImageUnreadable: "This image could not be opened. Choose another file.",
  backgroundImageTooLarge: "This image is too large to save. Choose a smaller one.",
  theme: "Theme",
  light: "Light",
  dark: "Dark",
  language: "Language",
  country: "Holiday country",
  countryHint: "Public holidays for the selected country are checked on the internet.",
  searchCountry: "Search countries",
  noCountry: "No matching country",
  weekStart: "First day of the week",
  sunday: "Sunday",
  monday: "Monday",
  alwaysOnTop: "Keep the calendar above other windows",
  autostart: "Launch when the system starts",
  desktopOnly: "Available in the desktop app.",
  refreshHolidays: "Check holidays again",
  holidayLive: "Checked live",
  holidayCached: "Showing the last check",
  holidayBuiltin: "Showing built-in holidays",
  holidayError: "Could not check holidays",
  checkedAt: "Checked {time}",
  checking: "Checking holidays…",
  noHoliday: "No public holiday",
  aboutBody: "A frameless transparent calendar that lives on the desktop and in the system tray.",
  aboutPlatformsLabel: "Platforms",
  aboutPlatforms: "Web, Linux, macOS, Windows",
  aboutHolidaySource:
    "Public holidays are loaded live from Nager.Date. When it can't be reached, built-in rules for about 200 countries (date-holidays, CC BY 3.0) are used.",
  holidaySourceLink: "date.nager.at",
  version: "Version",
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  trayTooltip: "My Calendar",
  languageSwitch: "한국어",
  webBanner:
    "The browser can use the calendar, themes, transparency, and holidays. The system tray and launch-at-startup run in the desktop app.",
  featuresTitle: "Included",
  featureTransparent: "Adjustable transparent background",
  featureThemes: "20 light themes and 20 dark themes",
  featureHolidays: "Holidays for about 200 countries (live and built-in)",
  featurePlatforms: "Web, Linux, macOS, and Windows",
  featureTray: "System tray, with no title bar",
  closeToTray: "Closing the window keeps the app in the tray.",
  appearance: "Appearance",
  holidaysSection: "Holidays",
  general: "General",
  countriesLive: "Country list checked online",
  countriesFallback: "Offline country list",
  countriesLoading: "Checking the country list…",
  installLanguageHelp:
    "The Windows installer asks you to choose Korean or English. The Linux and macOS install scripts ask as well. The web app asks the first time it opens.",
  openSourcePage: "Open holiday source",
  aboutDataNote:
    "Korean uses each country's local holiday name. English uses the English name.",
  startup: "Startup",
  monthHolidays: "This month",
  collapseEvents: "Collapse event list",
  expandEvents: "Expand event list",
  resizeWindow: "Resize",
  calendarSection: "Calendar",
  weekStartHint: "The chosen day becomes the first column of the calendar.",
  showLunar: "Show lunar dates and solar terms",
  lunarHint:
    "The lunar date appears in small type under the first day of each lunar month and each solar month. The 24 solar terms are named on their days.",
  lunarUnavailable: "This environment cannot compute lunar dates, so only solar terms are shown.",
  lunarShort: "L",
  lunarLeapShort: "Leap",
  lunarFull: "Lunar {month}/{day}{leap}",
  lunarLeapMark: " (leap month)",
  lunarMonthName: "Month {month}",
  lunarLeapMonthName: "Leap month {month}",
  solarTerms: [
    "Minor Cold", "Major Cold", "Spring Begins", "Rain Water", "Insects Wake", "Spring Equinox",
    "Clear and Bright", "Grain Rain", "Summer Begins", "Grain Buds", "Grain in Ear", "Summer Solstice",
    "Minor Heat", "Major Heat", "Autumn Begins", "End of Heat", "White Dew", "Autumn Equinox",
    "Cold Dew", "Frost Descent", "Winter Begins", "Minor Snow", "Major Snow", "Winter Solstice",
  ],
  eventsSection: "Events",
  addEvent: "Add event",
  editEvent: "Edit event",
  manageEvents: "Manage events",
  eventTitle: "Title",
  eventTitlePlaceholder: "Event name",
  eventDate: "Date",
  dateCalendar: "Date calendar",
  calendarSolar: "Solar",
  calendarLunar: "Lunar",
  solarDate: "Solar date",
  lunarDate: "Lunar date",
  lunarYear: "Lunar year",
  lunarMonth: "Lunar month",
  lunarDay: "Lunar day",
  lunarRepeatHint: "A lunar event follows its lunar date when it repeats monthly or yearly.",
  lunarDateInvalid: "That lunar date does not exist. Check the year, month, and day.",
  eventTime: "Time (empty for all day)",
  allDay: "All day",
  repeat: "Repeat",
  repeatNone: "Never",
  repeatWeekly: "Weekly",
  repeatMonthly: "Monthly",
  repeatYearly: "Yearly",
  repeatEvery: { weekly: "Every {n} weeks", monthly: "Every {n} months", yearly: "Every {n} years" },
  repeatEveryOne: { weekly: "Weekly", monthly: "Monthly", yearly: "Yearly" },
  repeatInterval: "Interval",
  repeatUntil: "Ends on",
  repeatUntilHint: "Leave empty to repeat forever.",
  repeatUntilShort: "until {date}",
  eventColor: "Color",
  colorNames: ["Blue", "Teal", "Green", "Yellow", "Orange", "Red", "Pink", "Purple"],
  customColor: "Custom color",
  save: "Save",
  cancel: "Cancel",
  deleteEvent: "Delete",
  deleteSeries: "Delete all",
  deleteOccurrence: "Delete this day",
  noEvents: "No events",
  noEventsYet: "No events yet. Add your first one.",
  searchEvents: "Search events",
  noMatchingEvents: "No matching events",
  noEventsOnDay: "No events on this day.",
  showAllEvents: "All events",
  titleRequired: "Enter a title.",
  eventCount: "{count} events",
  reminder: "Reminder",
  reminderNone: "No reminder",
  reminderAtStart: "At start time",
  reminderBefore: {
    minute: "{n} minute before",
    minutes: "{n} minutes before",
    hour: "{n} hour before",
    hours: "{n} hours before",
    day: "{n} day before",
    days: "{n} days before",
    week: "{n} week before",
    weeks: "{n} weeks before",
  },
  allDayReminderHint: "All-day events are reminded relative to 9:00 AM.",
  defaultReminder: "Default reminder for new events",
  remindersHint: "While the calendar is running, a popup appears at the bottom right of the screen at reminder time.",
  remindersTitle: "Event reminders",
  startingNow: "Starting now",
  startedAt: "Started at {time}",
  startsInMinutes: "Starts in {n} min",
  todayAt: "Today at {time}",
  tomorrowAt: "Tomorrow at {time}",
  dateAt: "{date} at {time}",
  todayAllDay: "Today, all day",
  tomorrowAllDay: "Tomorrow, all day",
  dateAllDay: "{date}, all day",
  snooze: "Snooze 5 min",
  dismiss: "Dismiss",
  dismissAll: "Dismiss all",
  confirmDelete: "Delete \u201c{title}\u201d?",
  goToday: "Go to today",
  addEventOn: "Add event on this day",
  dateFont: "Date font",
  dateFontSize: "Size",
  dateFontSizeHint: "Dates still grow and shrink with the window; this scales them up or down from there.",
  dateFontFamily: "Font",
  dateFontWeight: "Weight",
  dateFontItalic: "Italic",
  fontFamilies: { system: "Default", sans: "Sans serif", serif: "Serif", rounded: "Rounded", mono: "Monospace" },
  fontWeights: { regular: "Regular", bold: "Bold", heavy: "Heavy" },
  fontPreview: "Preview",
  resetFont: "Reset",
  dateFontTarget: "For",
  dateFontTargets: { window: "Window", fullscreen: "Full screen" },
  dateFontTargetHint: "The window and full screen each keep their own font. Settings opened in full screen change the full screen font.",
  print: "Print",
  printTitle: "Print preview",
  printSetup: "Page setup",
  printStart: "Start month",
  printMonths: "Months",
  printPaper: "Paper",
  printOrientation: "Orientation",
  printOrientations: { portrait: "Portrait", landscape: "Landscape" },
  printMargin: "Margins",
  printMargins: { none: "None", narrow: "Narrow", normal: "Normal", wide: "Wide" },
  printContent: "Include",
  printCellEvents: "Events in day cells",
  printEventList: "Event list for each month",
  printHolidayNames: "Holiday names",
  printLunar: "Lunar dates and solar terms",
  printGrayscale: "Print in grayscale",
  printPageOf: "Page {page} of {total}",
  printPages: "{n} pages",
  printPrinted: "Printed {date}",
  printMonthEvents: "Events this month",
  printMore: "+{n} more",
  printHint: "Print opens the printer dialog. Paper, orientation, and margins follow what you set here.",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  decrease: "Decrease {name}",
  increase: "Increase {name}",
  windowMenu: "Calendar menu",
};
