import type { Messages } from "./messages";

export const ko: Messages = {
  appName: "마이 캘린더",
  tagline: "바탕화면 위에 두는 투명 캘린더",
  today: "오늘",
  settings: "설정",
  about: "프로그램 정보",
  hide: "트레이로 숨기기",
  close: "닫기",
  quit: "종료",
  showHide: "캘린더 표시/숨기기",
  prevMonth: "이전 달",
  nextMonth: "다음 달",
  transparency: "투명도",
  transparencyHint: "값을 높일수록 배경이 더 투명해집니다.",
  theme: "테마",
  light: "라이트",
  dark: "다크",
  language: "언어",
  country: "공휴일 국가",
  countryHint: "선택한 국가의 공휴일을 인터넷에서 확인합니다.",
  searchCountry: "국가 검색",
  noCountry: "일치하는 국가가 없습니다",
  weekStart: "한 주의 시작",
  sunday: "일요일",
  monday: "월요일",
  alwaysOnTop: "다른 창보다 위에 두기",
  autostart: "시스템 시작 시 자동 실행",
  desktopOnly: "데스크톱 앱에서 사용할 수 있습니다.",
  refreshHolidays: "공휴일 다시 확인",
  holidayLive: "실시간 확인됨",
  holidayCached: "마지막 확인 내용을 표시 중",
  holidayError: "공휴일을 확인하지 못했습니다",
  checkedAt: "확인 시각 {time}",
  checking: "공휴일 확인 중…",
  noHoliday: "공휴일 없음",
  aboutBody: "제목 표시줄 없이 바탕화면과 시스템 트레이에서 동작하는 투명 캘린더입니다.",
  aboutPlatformsLabel: "지원 환경",
  aboutPlatforms: "Web, Linux, macOS, Windows",
  aboutHolidaySource: "공휴일은 Nager.Date에서 실시간으로 가져옵니다.",
  holidaySourceLink: "date.nager.at",
  version: "버전",
  months: ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"],
  weekdays: ["일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"],
  weekdaysShort: ["일", "월", "화", "수", "목", "금", "토"],
  trayTooltip: "마이 캘린더",
  webBanner:
    "브라우저에서는 캘린더, 테마, 투명도, 공휴일을 사용할 수 있습니다. 시스템 트레이와 시작 시 자동 실행은 데스크톱 앱에서 동작합니다.",
  featuresTitle: "포함 기능",
  featureTransparent: "조절할 수 있는 투명 배경",
  featureThemes: "라이트 20종, 다크 20종",
  featureHolidays: "국가별 실시간 공휴일",
  featurePlatforms: "Web, Linux, macOS, Windows",
  featureTray: "제목 표시줄 없는 시스템 트레이",
  closeToTray: "창을 닫아도 트레이에서 계속 실행됩니다.",
  appearance: "모양",
  holidaysSection: "공휴일",
  general: "일반",
  countriesLive: "국가 목록을 온라인에서 확인함",
  countriesFallback: "오프라인 국가 목록",
  countriesLoading: "국가 목록을 확인하는 중…",
  installLanguageHelp:
    "Windows 설치 프로그램은 설치 중에 한국어와 English 중 하나를 고릅니다. Linux와 macOS는 설치 스크립트에서 고르고, 웹은 처음 열 때 고릅니다.",
  openSourcePage: "공휴일 출처 열기",
  aboutDataNote: "한국어 화면은 해당 국가의 현지 공휴일 이름을 쓰고, English 화면은 영어 이름을 씁니다.",
  startup: "시작 프로그램",
  monthHolidays: "이번 달 공휴일",
};
