import type { Messages } from "./messages";

export const ko: Messages = {
  appName: "마이 캘린더",
  tagline: "바탕화면 위에 두는 투명 캘린더",
  today: "오늘",
  settings: "설정",
  about: "프로그램 정보",
  aboutTab: "정보",
  hide: "트레이로 숨기기",
  minimize: "최소화",
  maximize: "최대화",
  restore: "이전 크기로 복원",
  close: "닫기",
  quit: "종료",
  showHide: "캘린더 표시/숨기기",
  prevMonth: "이전 달",
  nextMonth: "다음 달",
  transparency: "투명도",
  transparencyHint: "값을 높일수록 배경이 더 투명해집니다.",
  theme: "테마",
  light: "라이트",
  dark: "다크",
  language: "언어",
  country: "공휴일 국가",
  countryHint: "선택한 국가의 공휴일을 인터넷에서 확인합니다.",
  searchCountry: "국가 검색",
  noCountry: "일치하는 국가가 없습니다",
  weekStart: "한 주의 시작",
  sunday: "일요일",
  monday: "월요일",
  alwaysOnTop: "다른 창보다 위에 두기",
  autostart: "시스템 시작 시 자동 실행",
  desktopOnly: "데스크톱 앱에서 사용할 수 있습니다.",
  refreshHolidays: "공휴일 다시 확인",
  holidayLive: "실시간 확인됨",
  holidayCached: "마지막 확인 내용을 표시 중",
  holidayBuiltin: "내장 공휴일을 표시 중",
  holidayError: "공휴일을 확인하지 못했습니다",
  checkedAt: "확인 시각 {time}",
  checking: "공휴일 확인 중…",
  noHoliday: "공휴일 없음",
  aboutBody: "제목 표시줄 없이 바탕화면과 시스템 트레이에서 동작하는 투명 캘린더입니다.",
  aboutPlatformsLabel: "지원 환경",
  aboutPlatforms: "Web, Linux, macOS, Windows",
  aboutHolidaySource:
    "공휴일은 Nager.Date에서 실시간으로 가져옵니다. 연결할 수 없을 때는 약 200개 나라의 내장 규칙(date-holidays, CC BY 3.0)으로 계산합니다.",
  holidaySourceLink: "date.nager.at",
  version: "버전",
  months: ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"],
  weekdays: ["일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"],
  weekdaysShort: ["일", "월", "화", "수", "목", "금", "토"],
  trayTooltip: "마이 캘린더",
  languageSwitch: "English",
  webBanner:
    "브라우저에서는 캘린더, 테마, 투명도, 공휴일을 사용할 수 있습니다. 시스템 트레이와 시작 시 자동 실행은 데스크톱 앱에서 동작합니다.",
  featuresTitle: "포함 기능",
  featureTransparent: "조절할 수 있는 투명 배경",
  featureThemes: "라이트 20종, 다크 20종",
  featureHolidays: "약 200개 나라의 공휴일 (실시간·내장)",
  featurePlatforms: "Web, Linux, macOS, Windows",
  featureTray: "제목 표시줄 없는 시스템 트레이",
  closeToTray: "창을 닫아도 트레이에서 계속 실행됩니다.",
  appearance: "모양",
  holidaysSection: "공휴일",
  general: "일반",
  countriesLive: "국가 목록을 온라인에서 확인함",
  countriesFallback: "오프라인 국가 목록",
  countriesLoading: "국가 목록을 확인하는 중…",
  installLanguageHelp:
    "Windows 설치 프로그램은 설치 중에 한국어와 English 중 하나를 고릅니다. Linux와 macOS는 설치 스크립트에서 고르고, 웹은 처음 열 때 고릅니다.",
  openSourcePage: "공휴일 출처 열기",
  aboutDataNote: "한국어 화면은 해당 국가의 현지 공휴일 이름을 쓰고, English 화면은 영어 이름을 씁니다.",
  startup: "시작 프로그램",
  monthHolidays: "이번 달 공휴일·일정",
  collapseEvents: "일정 목록 접기",
  expandEvents: "일정 목록 펼치기",
  resizeWindow: "크기 조절",
  calendarSection: "달력",
  weekStartHint: "선택한 요일이 달력의 첫 번째 열에 옵니다.",
  showLunar: "음력과 절기 표시",
  lunarHint: "음력 달이 바뀌는 날과 양력 1일에는 날짜 아래에 음력 날짜를, 24절기에는 절기 이름을 작게 표시합니다.",
  lunarUnavailable: "이 환경에서는 음력 날짜를 계산할 수 없어 절기만 표시합니다.",
  lunarShort: "음",
  lunarLeapShort: "윤",
  lunarFull: "음력 {leap}{month}월 {day}일",
  lunarLeapMark: "윤",
  lunarMonthName: "{month}월",
  lunarLeapMonthName: "윤{month}월",
  solarTerms: [
    "소한", "대한", "입춘", "우수", "경칩", "춘분", "청명", "곡우", "입하", "소만", "망종", "하지",
    "소서", "대서", "입추", "처서", "백로", "추분", "한로", "상강", "입동", "소설", "대설", "동지",
  ],
  eventsSection: "일정",
  addEvent: "일정 추가",
  editEvent: "일정 편집",
  manageEvents: "일정 관리",
  eventTitle: "제목",
  eventTitlePlaceholder: "일정 이름",
  eventDate: "날짜",
  dateCalendar: "날짜 기준",
  calendarSolar: "양력",
  calendarLunar: "음력",
  solarDate: "양력 날짜",
  lunarDate: "음력 날짜",
  lunarYear: "음력 연도",
  lunarMonth: "음력 월",
  lunarDay: "음력 일",
  lunarRepeatHint: "음력 일정은 매월·매년 반복할 때 음력 날짜를 따라갑니다.",
  lunarDateInvalid: "그 음력 날짜는 없습니다. 연도와 월, 일을 다시 확인해 주세요.",
  eventTime: "시간 (비우면 종일)",
  allDay: "종일",
  repeat: "반복",
  repeatNone: "안 함",
  repeatWeekly: "매주",
  repeatMonthly: "매월",
  repeatYearly: "매년",
  repeatEvery: { weekly: "{n}주마다", monthly: "{n}개월마다", yearly: "{n}년마다" },
  repeatEveryOne: { weekly: "매주", monthly: "매월", yearly: "매년" },
  repeatInterval: "반복 간격",
  repeatUntil: "종료일",
  repeatUntilHint: "비워 두면 계속 반복합니다.",
  repeatUntilShort: "{date}까지",
  eventColor: "색상",
  colorNames: ["파랑", "청록", "초록", "노랑", "주황", "빨강", "분홍", "보라"],
  customColor: "사용자 지정 색",
  save: "저장",
  cancel: "취소",
  deleteEvent: "삭제",
  deleteSeries: "전체 삭제",
  deleteOccurrence: "이 날만 삭제",
  noEvents: "일정 없음",
  noEventsYet: "등록된 일정이 없습니다. 새 일정을 추가해 보세요.",
  searchEvents: "일정 검색",
  noMatchingEvents: "일치하는 일정이 없습니다",
  titleRequired: "제목을 입력하세요.",
  eventCount: "일정 {count}개",
  reminder: "알림",
  reminderNone: "알림 없음",
  reminderAtStart: "일정 시간에",
  reminderBefore: {
    minute: "{n}분 전",
    minutes: "{n}분 전",
    hour: "{n}시간 전",
    hours: "{n}시간 전",
    day: "{n}일 전",
    days: "{n}일 전",
    week: "{n}주 전",
    weeks: "{n}주 전",
  },
  allDayReminderHint: "종일 일정은 오전 9시를 기준으로 알립니다.",
  defaultReminder: "새 일정의 기본 알림",
  remindersHint: "캘린더가 실행 중이면 알림 시간에 화면 오른쪽 아래에 팝업이 나타납니다.",
  remindersTitle: "일정 알림",
  startingNow: "지금 시작",
  startedAt: "{time}에 시작함",
  startsInMinutes: "{n}분 후 시작",
  todayAt: "오늘 {time}",
  tomorrowAt: "내일 {time}",
  dateAt: "{date} {time}",
  todayAllDay: "오늘 종일",
  tomorrowAllDay: "내일 종일",
  dateAllDay: "{date} 종일",
  snooze: "5분 후 다시",
  dismiss: "확인",
  dismissAll: "모두 닫기",
  confirmDelete: "'{title}' 일정을 삭제할까요?",
  goToday: "오늘로 이동",
  addEventOn: "이 날에 일정 추가",
  dateFont: "날짜 글꼴",
  dateFontSize: "글자 크기",
  dateFontSizeHint: "창 크기에 맞춰 커지고 작아지며, 여기서 정한 비율만큼 더 크거나 작게 표시됩니다.",
  dateFontFamily: "글꼴",
  dateFontWeight: "굵기",
  dateFontItalic: "기울임꼴",
  fontFamilies: { system: "기본", sans: "고딕", serif: "명조", rounded: "둥근 글꼴", mono: "고정폭" },
  fontWeights: { regular: "보통", bold: "굵게", heavy: "아주 굵게" },
  fontPreview: "미리 보기",
  resetFont: "기본값으로",
  dateFontTarget: "적용",
  dateFontTargets: { window: "창", fullscreen: "전체 화면" },
  dateFontTargetHint: "창과 전체 화면의 글꼴은 따로 기억됩니다. 전체 화면에서 설정을 열면 전체 화면 글꼴을 바꿉니다.",
  print: "인쇄",
  printTitle: "인쇄 미리 보기",
  printSetup: "페이지 설정",
  printStart: "시작 달",
  printMonths: "개월 수",
  printPaper: "용지",
  printOrientation: "방향",
  printOrientations: { portrait: "세로", landscape: "가로" },
  printMargin: "여백",
  printMargins: { none: "없음", narrow: "좁게", normal: "보통", wide: "넓게" },
  printContent: "인쇄할 내용",
  printCellEvents: "날짜 칸에 일정 표시",
  printEventList: "달마다 일정 목록 추가",
  printHolidayNames: "공휴일 이름",
  printLunar: "음력과 절기",
  printGrayscale: "흑백으로 인쇄",
  printPageOf: "{page} / {total}쪽",
  printPages: "모두 {n}쪽",
  printPrinted: "{date} 인쇄",
  printMonthEvents: "이달의 일정",
  printMore: "외 {n}건",
  printHint: "인쇄를 누르면 프린터를 고르는 창이 열립니다. 용지와 방향, 여백은 여기서 정한 대로 맞춰집니다.",
  zoomIn: "확대",
  zoomOut: "축소",
  decrease: "{name} 줄이기",
  increase: "{name} 늘리기",
  windowMenu: "캘린더 메뉴",
};
