// Netlist exports: KiCad S-expression netlist (from the schematic) and
// IPC-D-356 bare-board test netlist (from the PCB pads and vias).

import { buildNetlist } from "../core/netlist.js";
import { getSymbol } from "../lib/symbols.js";
import { allPads } from "../pcb/board.js";
import { naturalCompare } from "./bom.js";

const q = (s) => `"${String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;

export function kicadNetlist(project, opts = {}) {
  const sch = project.schematic;
  const nl = buildNetlist(sch);
  const meta = project.meta || {};
  const date = opts.date ? new Date(opts.date).toISOString() : new Date().toISOString();
  const L = [];
  L.push("(export (version \"E\")");
  L.push("  (design");
  L.push(`    (source ${q(`${meta.title || "Untitled"}.mycircuit`)})`);
  L.push(`    (date ${q(date)})`);
  L.push("    (tool \"MyCircuit 10.0\")");
  L.push("    (sheet (number \"1\") (name \"/\") (tstamps \"/\")");
  L.push(`      (title_block (title ${q(meta.title || "")}) (company ${q(meta.company || "")}) (rev ${q(meta.rev || "")}) (date ${q(meta.date || "")}))))`);
  L.push("  (components");
  const parts = sch.parts.filter((p) => {
    const s = getSymbol(p.lib);
    return !(s && (s.power || s.flag)) && p.ref && !p.ref.startsWith("#");
  }).sort((a, b) => naturalCompare(a.ref, b.ref));
  for (const p of parts) {
    const s = getSymbol(p.lib);
    L.push(`    (comp (ref ${q(p.ref)})`);
    L.push(`      (value ${q(p.value || "")})`);
    if (p.footprint) L.push(`      (footprint ${q(p.footprint)})`);
    const fields = Object.entries(p.fields || {});
    if (fields.length) L.push(`      (fields ${fields.map(([k, v]) => `(field (name ${q(k)}) ${q(v)})`).join(" ")})`);
    L.push(`      (libsource (lib "MyCircuit") (part ${q(p.lib)}) (description ${q((s && s.title) || "")}))`);
    if (p.dnp) L.push("      (property (name \"dnp\"))");
    L.push("      (sheetpath (names \"/\") (tstamps \"/\"))");
    L.push(`      (tstamps ${q(p.id || "")}))`);
  }
  L.push("  )");
  L.push("  (nets");
  for (const n of nl.nets) {
    const pins = [...n.pins].sort((a, b) => naturalCompare(a.ref, b.ref) || naturalCompare(a.pin, b.pin));
    L.push(`    (net (code ${q(n.code)}) (name ${q(n.name)})`);
    for (const p of pins) {
      const fn = p.name && p.name !== "~" ? ` (pinfunction ${q(p.name)})` : "";
      L.push(`      (node (ref ${q(p.ref)}) (pin ${q(p.pin)})${fn} (pintype ${q(p.type || "passive")}))`);
    }
    L[L.length - 1] += ")";
  }
  L.push("  )");
  L.push(")");
  return L.join("\n") + "\n";
}

// ---------------------------------------------------------------- IPC-D-356
// Units: "UNITS CUST 1" = millimetres, coordinates/sizes in 0.001 mm. Y uses
// the Gerber convention (Y = -Y(board)). Net names longer than 14 characters
// are replaced by NNAMEn aliases declared in the header, like KiCad does.

const pad = (s, n) => String(s ?? "").slice(0, n).padEnd(n, " ");
const signed6 = (v) => {
  const n = Math.max(-999999, Math.min(999999, Math.round(v * 1000)));
  return (n < 0 ? "-" : "+") + String(Math.abs(n)).padStart(6, "0");
};
const u4 = (v) => String(Math.max(0, Math.min(9999, Math.round(v * 1000)))).padStart(4, "0");

export function ipc356(project, opts = {}) {
  const pcb = project.pcb;
  const meta = project.meta || {};
  const aliases = new Map();
  const netName = (n) => {
    if (!n) return "N/C";
    const s = String(n).replace(/\s+/g, "_");
    if (s.length <= 14) return s;
    if (!aliases.has(s)) aliases.set(s, `NNAME${aliases.size + 1}`);
    return aliases.get(s);
  };
  const recs = [];
  for (const p of allPads(pcb)) {
    const tht = p.drill > 0;
    const op = p.npth ? "367" : tht ? "317" : "327";
    const access = tht ? 0 : p.side === "B" ? 2 : 1;
    const rot = Math.round((((p.rot || 0) % 360) + 360) % 360) % 360;
    const w = p.shape === "circle" ? Math.max(p.w, p.h) : p.w;
    const h = p.shape === "circle" ? Math.max(p.w, p.h) : p.h;
    recs.push(op + pad(netName(p.net), 14) + "   " + pad(p.ref, 6) + "-" + pad(p.num || "", 4) + " " +
      (tht ? `D${u4(p.drill)}${p.npth ? "U" : "P"}` : "      ") +
      `A${String(access).padStart(2, "0")}X${signed6(p.x)}Y${signed6(-p.y)}X${u4(w)}Y${u4(h)}R${String(rot).padStart(3, "0")} S${access === 0 ? 0 : access === 1 ? 1 : 2}`);
  }
  for (const v of pcb.vias || []) {
    recs.push("317" + pad(netName(v.net), 14) + "   " + pad("VIA", 6) + "-" + pad("", 4) + "M" +
      `D${u4(v.drill || 0)}PA00X${signed6(v.x)}Y${signed6(-v.y)}X${u4(v.d)}Y${u4(v.d)}R000 S3`);
  }
  const head = [
    "C  IPC-D-356 netlist generated by MyCircuit 10.0",
    `C  ${opts.date ? new Date(opts.date).toISOString() : new Date().toISOString()}`,
    "C",
    `P  JOB   ${meta.title || "Untitled"}`,
    "P  CODE  00",
    "P  UNITS CUST 1",
    "P  DIM   N",
    "P  VER   IPC-D-356",
    "P  IMAGE PRIMARY",
    "C",
  ];
  for (const [name, alias] of aliases) head.push(`P  ${alias.padEnd(11, " ")} ${name}`);
  return [...head, ...recs, "999", ""].join("\n");
}
