// Everything a board house needs in one go: Gerbers, drill files, BOM,
// centroid, IPC-356 netlist, Gerber job file and a README, plus a zip of it.

import { copperLayers } from "../core/project.js";
import { polygonBounds } from "../core/geom.js";
import { gerberLayer, gerberFileName, baseName, projectGuid, fabLayers, layerInfo } from "./gerber.js";
import { excellon, drillFileName } from "./excellon.js";
import { bomCsv } from "./bom.js";
import { pickPlaceCsv } from "./pnp.js";
import { ipc356 } from "./netlistExport.js";
import { makeZip } from "./zip.js";

function jobFile(project, gerbers, opts) {
  const pcb = project.pcb;
  const meta = project.meta || {};
  const b = polygonBounds(pcb.outline);
  const r = pcb.rules || {};
  const n = copperLayers(pcb).length;
  const date = (opts.date ? new Date(opts.date) : new Date()).toISOString().replace(/\.\d{3}Z$/, "Z");
  const job = {
    Header: {
      GenerationSoftware: { Vendor: "MyCircuit", Application: "MyCircuit", Version: "10.0" },
      CreationDate: date,
    },
    GeneralSpecs: {
      ProjectId: { Name: meta.title || "Untitled", GUID: projectGuid(project), Revision: meta.rev || "1.0" },
      Size: { X: +(b.x2 - b.x1).toFixed(4), Y: +(b.y2 - b.y1).toFixed(4) },
      LayerNumber: n,
      BoardThickness: pcb.thickness || 1.6,
      Finish: pcb.finish || "HASL",
    },
    DesignRules: [{
      Layers: "Outer",
      PadToPad: r.clearance, PadToTrack: r.clearance, TrackToTrack: r.clearance,
      MinLineWidth: r.minTrackWidth ?? r.trackWidth,
    }],
    FilesAttributes: gerbers.map((g) => ({ Path: g.name, FileFunction: g.fileFunction, FilePolarity: g.polarity })),
    MaterialStackup: [
      { Type: "Legend", Color: pcb.silkColor || "White", Name: "Top Silk Screen" },
      { Type: "SolderMask", Color: pcb.maskColor || "Green", Name: "Top Solder Mask" },
      ...copperLayers(pcb).flatMap((l, i, arr) => {
        const items = [{ Type: "Copper", Name: l }];
        if (i < arr.length - 1) items.push({ Type: "Dielectric", Material: "FR4", Name: `dielectric ${i + 1}`, Thickness: +(((pcb.thickness || 1.6) - 0.035 * n) / (n - 1)).toFixed(4) });
        return items;
      }),
      { Type: "SolderMask", Color: pcb.maskColor || "Green", Name: "Bottom Solder Mask" },
      { Type: "Legend", Color: pcb.silkColor || "White", Name: "Bottom Silk Screen" },
    ],
  };
  return JSON.stringify(job, null, 2) + "\n";
}

function readme(project, files) {
  const pcb = project.pcb;
  const meta = project.meta || {};
  const b = polygonBounds(pcb.outline);
  const lines = [
    `${meta.title || "Untitled"} - fabrication files`,
    `Revision ${meta.rev || "1.0"}${meta.company ? ` - ${meta.company}` : ""}${meta.author ? ` - ${meta.author}` : ""}`,
    "Generated by MyCircuit 10.0",
    "",
    `Board: ${(b.x2 - b.x1).toFixed(2)} x ${(b.y2 - b.y1).toFixed(2)} mm, ${copperLayers(pcb).length} copper layers, ${pcb.thickness || 1.6} mm, finish ${pcb.finish || "HASL"}, ${pcb.maskColor || "green"} mask / ${pcb.silkColor || "white"} silk`,
    "",
    "Units: millimetres. Gerber RS-274X (X2 attributes), format 4.6 (%FSLAX46Y46*%).",
    "Coordinates: Gerber and drill Y = -Y of the design (same origin in every file).",
    "Pick-and-place: origin at the bottom-left corner of the board outline, Y up.",
    "",
    "Files:",
  ];
  for (const f of files) lines.push(`  ${f.name.padEnd(36)} ${f.description || f.kind}`);
  lines.push("");
  return lines.join("\r\n");
}

// opts: maskExpansion, tentVias, pasteShrink, date, + {bom, pnp, netlist, job, readme: false to skip}
export function fabricationFiles(project, opts = {}) {
  const pcb = project.pcb;
  const base = baseName(project);
  const files = [];
  const gerbers = [];
  for (const layer of fabLayers(pcb)) {
    const info = layerInfo(pcb, layer);
    const name = gerberFileName(project, layer);
    files.push({ name, data: gerberLayer(project, layer, opts), kind: "gerber", layer, description: `Gerber ${layer} (${info.fileFunction})` });
    gerbers.push({ name, fileFunction: info.fileFunction, polarity: info.polarity });
  }
  files.push({ name: drillFileName(base, true), data: excellon(project, { plated: true, date: opts.date }), kind: "drill", description: "Excellon drill, plated holes (pads + vias)" });
  files.push({ name: drillFileName(base, false), data: excellon(project, { plated: false, date: opts.date }), kind: "drill", description: "Excellon drill, non-plated holes" });
  if (opts.bom !== false) files.push({ name: `${base}-BOM.csv`, data: bomCsv(project, { group: true }), kind: "bom", description: "Bill of materials (grouped)" });
  if (opts.pnp !== false) files.push({ name: `${base}-pos.csv`, data: pickPlaceCsv(project, { side: "both" }), kind: "pnp", description: "Pick-and-place / centroid, both sides" });
  if (opts.netlist !== false) files.push({ name: `${base}.d356`, data: ipc356(project, { date: opts.date }), kind: "netlist", description: "IPC-D-356 netlist for electrical test" });
  if (opts.job !== false) files.push({ name: `${base}-job.gbrjob`, data: jobFile(project, gerbers, opts), kind: "job", description: "Gerber job file (layer stack, attributes)" });
  if (opts.readme !== false) {
    const list = [...files, { name: "README.txt", kind: "readme", description: "This file" }];
    files.push({ name: "README.txt", data: readme(project, list), kind: "readme", description: "This file" });
  }
  return files.map(({ name, data, kind, layer }) => (layer ? { name, data, kind, layer } : { name, data, kind }));
}

export function fabricationZip(project, opts = {}) {
  return makeZip(fabricationFiles(project, opts), { date: opts.date });
}
