const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  isElectron: true,
  resizeWindow: (step) => ipcRenderer.invoke("window-resize", step),
  moveWindow: (step) => ipcRenderer.invoke("window-move", step),
  resizeWindowTo: (size) => ipcRenderer.invoke("window-size", size),
  onWindowState: (callback) => ipcRenderer.on("window-state", (_event, state) => callback(state)),
  listFonts: () => ipcRenderer.invoke("list-fonts"),
  fetch: (url, options) => ipcRenderer.invoke("fetch-url", url, options),
  openFile: (opts) => ipcRenderer.invoke("open-file", opts),
  saveFile: (opts) => ipcRenderer.invoke("save-file", opts),
  readFile: (filePath) => ipcRenderer.invoke("read-file", filePath),
  writeFile: (filePath, text) => ipcRenderer.invoke("write-file", filePath, text),
  pickImage: (opts) => ipcRenderer.invoke("pick-image", opts),
  print: (payload) => ipcRenderer.invoke("print", payload),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  windowControl: (action) => ipcRenderer.invoke("window-control", action),
  confirmQuit: () => ipcRenderer.invoke("confirm-quit"),
  windowBounds: () => ipcRenderer.invoke("window-bounds"),
  readSettings: () => ipcRenderer.invoke("read-settings"),
  writeSettings: (data) => ipcRenderer.invoke("write-settings", data),
  setAutoStart: (on) => ipcRenderer.invoke("set-auto-start", on),
  getAutoStart: () => ipcRenderer.invoke("get-auto-start"),
  beginPopup: (spec) => ipcRenderer.invoke("begin-popup", spec),
  updatePopup: (id, patch) => ipcRenderer.invoke("update-popup", id, patch),
  waitPopup: (id) => ipcRenderer.invoke("wait-popup", id),
  endPopup: (id) => ipcRenderer.invoke("end-popup", id),
  takePopupSpec: () => ipcRenderer.invoke("take-popup-spec"),
  finishPopup: (result) => ipcRenderer.invoke("finish-popup", result),
  resizePopup: (size) => ipcRenderer.invoke("resize-popup", size),
  popupImmediate: (message) => ipcRenderer.send("popup-immediate", message),
  broadcastTheme: (payload) => ipcRenderer.send("broadcast-theme", payload),
  broadcastWallpaper: (payload) => ipcRenderer.send("broadcast-wallpaper", payload),
  onApplyTheme: (callback) => ipcRenderer.on("apply-theme", (_event, payload) => callback(payload)),
  onApplyWallpaper: (callback) => ipcRenderer.on("apply-wallpaper", (_event, payload) => callback(payload)),
  onPopupUpdate: (callback) => ipcRenderer.on("popup-update", (_event, patch) => callback(patch)),
  onPopupImmediate: (callback) => ipcRenderer.on("popup-immediate", (_event, message) => callback(message)),
  showMenu: (payload) => ipcRenderer.invoke("show-menu", payload),
  onMenuCommand: (callback) => ipcRenderer.on("menu-command", (_event, id) => callback(id)),
  takeMenuSpec: () => ipcRenderer.invoke("take-menu-spec"),
  fitTrayMenu: (size) => ipcRenderer.invoke("fit-tray-menu", size),
  menuCommand: (id) => ipcRenderer.send("menu-command", id),
  onRequestClose: (callback) => ipcRenderer.on("request-close", () => callback()),
  clipboardWrite: (text) => ipcRenderer.invoke("clipboard-write", text),
  clipboardRead: () => ipcRenderer.invoke("clipboard-read"),
});
