// The sample projects in sample/ (generated by scripts/create-samples.mjs):
// every file listed in sample/index.json must load and pass ERC, routing,
// DRC, simulation (where set up) and fabrication output.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { parseProject, copperLayers } from "../../src/core/project.js";
import { runERC } from "../../src/core/netlist.js";
import { getSymbol } from "../../src/lib/symbols.js";
import { getFootprint } from "../../src/lib/footprints.js";
import { routingStats } from "../../src/pcb/board.js";
import { runDRC } from "../../src/pcb/drc.js";
import { simulate } from "../../src/sim/engine.js";
import { fabricationFiles } from "../../src/fab/package.js";

const DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "sample");
const index = JSON.parse(readFileSync(join(DIR, "index.json"), "utf8"));
const load = (file) => parseProject(readFileSync(join(DIR, file), "utf8"));
const realParts = (p) => p.schematic.parts.filter((x) => { const s = getSymbol(x.lib); return s && !s.power && !s.flag; });

test("index.json lists every sample file once, with complete card data", () => {
  assert.equal(index.length, 12);
  const files = readdirSync(DIR).filter((f) => f.endsWith(".mycircuit")).sort();
  assert.deepEqual(index.map((e) => e.file).sort(), files);
  assert.equal(new Set(index.map((e) => e.file)).size, index.length);
  for (const e of index) {
    for (const k of ["file", "title", "titleKo", "description", "descriptionKo"]) assert.ok(typeof e[k] === "string" && e[k].length > 0, `${e.file}: ${k}`);
    assert.ok(Array.isArray(e.tags) && e.tags.length > 0, `${e.file}: tags`);
    assert.ok(Array.isArray(e.features) && e.features.length > 0, `${e.file}: features`);
    assert.ok(existsSync(join(DIR, e.file)), e.file);
  }
  // Numbered in order.
  index.forEach((e, i) => assert.ok(e.file.startsWith(String(i + 1).padStart(2, "0") + "-"), e.file));
});

for (const entry of index) {
  test(`sample ${entry.file}`, () => {
    const p = load(entry.file);
    assert.equal(p.format, "mycircuit");
    assert.ok(p.meta.title && p.meta.author && p.meta.rev && p.meta.date, "meta filled in");

    // Schematic: annotated, every part has a footprint, ERC clean.
    const parts = realParts(p);
    assert.ok(parts.length >= 4, "has parts");
    for (const part of parts) {
      assert.ok(!/\?$/.test(part.ref), `${part.ref} annotated`);
      if (getSymbol(part.lib).pins.length) assert.ok(part.footprint && getFootprint(part.footprint), `${part.ref} footprint ${part.footprint}`);
    }
    const ercErrors = runERC(p.schematic).filter((i) => i.severity === "error");
    assert.deepEqual(ercErrors.map((e) => e.message), []);

    // Board: one footprint per part, fully routed, DRC clean.
    assert.equal(p.pcb.footprints.length, parts.length);
    assert.ok(p.pcb.tracks.length > 0, "routed");
    assert.equal(routingStats(p.pcb).unrouted, 0);
    const drcErrors = runDRC(p).filter((i) => i.severity === "error");
    assert.deepEqual(drcErrors.map((e) => `${e.code}: ${e.message}`), []);
    assert.ok(p.pcb.texts.some((t) => t.layer === "F.SilkS"), "board name on the silkscreen");

    // Simulation where the sample is set up for it.
    if (p.sim.probes.length > 0) {
      const r = simulate(p, { mode: p.sim.mode });
      assert.ok(r.ok, `${p.sim.mode}: ${(r.errors || []).join("; ")}`);
    }

    // Fabrication: a Gerber for every copper layer, plus drills.
    const files = fabricationFiles(p, { date: "2026-10-09T00:00:00Z" });
    for (const layer of copperLayers(p.pcb)) {
      const g = files.find((f) => f.kind === "gerber" && f.layer === layer);
      assert.ok(g && g.data.length > 100, `Gerber for ${layer}`);
    }
    assert.ok(files.some((f) => f.kind === "drill"), "drill file");
  });
}

test("samples cover the advertised features", () => {
  const byFile = Object.fromEntries(index.map((e) => [e.file.slice(0, 2), load(e.file)]));
  // Simulated samples and their analyses.
  const simulated = Object.entries(byFile).filter(([, p]) => p.sim.probes.length).map(([k, p]) => `${k}:${p.sim.mode}`).sort();
  assert.deepEqual(simulated, ["01:op", "02:ac", "04:op", "05:op", "06:tran", "07:tran"]);
  // 4-layer board with inner planes.
  const four = byFile["11"];
  assert.equal(four.pcb.layerCount, 4);
  assert.deepEqual(four.pcb.zones.map((z) => `${z.layer}:${z.net}`).sort(), ["B.Cu:GND", "In1.Cu:GND", "In2.Cu:+3V3"]);
  // Parts on the bottom side.
  assert.ok(byFile["09"].pcb.footprints.some((f) => f.side === "B"));
  // Project-local library.
  const lib = byFile["12"];
  assert.equal(lib.library.symbols.length, 1);
  assert.equal(lib.library.footprints.length, 1);
  assert.ok(lib.schematic.parts.some((x) => x.lib === lib.library.symbols[0].name));
  assert.ok(lib.pcb.footprints.some((f) => f.footprint === lib.library.footprints[0].name));
  // Buses and labels in the shift-register sample.
  assert.ok(byFile["10"].schematic.buses.length >= 8);
  assert.ok(byFile["10"].schematic.labels.length >= 16);
  // Mask colours vary across the set.
  assert.ok(new Set(Object.values(byFile).map((p) => p.pcb.maskColor)).size >= 6);
  // Mounting holes where advertised.
  for (const k of ["04", "08"]) assert.ok(byFile[k].pcb.footprints.some((f) => f.footprint.startsWith("MountingHole")), k);
});

test("generated files are stable (ids renumbered, fixed date)", () => {
  for (const e of index) {
    const p = load(e.file);
    assert.equal(p.meta.date, "2026-10-09");
    assert.equal(p.meta.author, "MyCircuit Samples");
    p.schematic.parts.forEach((x, i) => assert.equal(x.id, `p${i + 1}`));
    p.schematic.wires.forEach((x, i) => assert.equal(x.id, `w${i + 1}`));
    p.pcb.footprints.forEach((x, i) => assert.equal(x.id, `f${i + 1}`));
    p.pcb.tracks.forEach((x, i) => assert.equal(x.id, `t${i + 1}`));
    const partIds = new Set(p.schematic.parts.map((x) => x.id));
    for (const f of p.pcb.footprints) assert.ok(partIds.has(f.partId), `${f.ref} links to its part`);
  }
});
