using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DBToolsWinV10.Models;

namespace DBToolsWinV10.Export;

public static class SqlExporter
{
	public static string Export(DbSchema schema)
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.AppendLine("-- Generated by DBToolsWinV10");
		StringBuilder stringBuilder2 = stringBuilder;
		StringBuilder stringBuilder3 = stringBuilder2;
		StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(13, 1, stringBuilder2);
		handler.AppendLiteral("-- Database: ");
		handler.AppendFormatted(schema.Name);
		stringBuilder3.AppendLine(ref handler);
		stringBuilder2 = stringBuilder;
		StringBuilder stringBuilder4 = stringBuilder2;
		handler = new StringBuilder.AppendInterpolatedStringHandler(13, 1, stringBuilder2);
		handler.AppendLiteral("-- Target:   ");
		handler.AppendFormatted(schema.TargetDb);
		stringBuilder4.AppendLine(ref handler);
		stringBuilder2 = stringBuilder;
		StringBuilder stringBuilder5 = stringBuilder2;
		handler = new StringBuilder.AppendInterpolatedStringHandler(13, 1, stringBuilder2);
		handler.AppendLiteral("-- Date:     ");
		handler.AppendFormatted(DateTime.Now, "yyyy-MM-dd HH:mm:ss");
		stringBuilder5.AppendLine(ref handler);
		stringBuilder.AppendLine();
		foreach (DbTable table in schema.Tables)
		{
			AppendCreateTable(stringBuilder, table, schema);
			stringBuilder.AppendLine();
		}
		if (schema.TargetDb != DbTargetType.SQLite)
		{
			foreach (DbRelationship relationship in schema.Relationships)
			{
				AppendForeignKey(stringBuilder, relationship, schema);
			}
		}
		return stringBuilder.ToString();
	}

	private static void AppendCreateTable(StringBuilder sb, DbTable table, DbSchema schema)
	{
		StringBuilder stringBuilder;
		StringBuilder.AppendInterpolatedStringHandler handler;
		if (!string.IsNullOrWhiteSpace(table.Comment))
		{
			stringBuilder = sb;
			StringBuilder stringBuilder2 = stringBuilder;
			handler = new StringBuilder.AppendInterpolatedStringHandler(3, 1, stringBuilder);
			handler.AppendLiteral("-- ");
			handler.AppendFormatted(table.Comment);
			stringBuilder2.AppendLine(ref handler);
		}
		stringBuilder = sb;
		StringBuilder stringBuilder3 = stringBuilder;
		handler = new StringBuilder.AppendInterpolatedStringHandler(15, 1, stringBuilder);
		handler.AppendLiteral("CREATE TABLE ");
		handler.AppendFormatted(Quote(schema.TargetDb, table.Name));
		handler.AppendLiteral(" (");
		stringBuilder3.AppendLine(ref handler);
		List<string> list = new List<string>();
		foreach (DbColumn column in table.Columns)
		{
			list.Add("    " + GetColumnDdl(column, schema));
		}
		List<DbColumn> list2 = table.Columns.Where((DbColumn c) => c.IsPrimaryKey).ToList();
		if (list2.Count > 1)
		{
			list.Add("    PRIMARY KEY (" + string.Join(", ", list2.Select((DbColumn c) => Quote(schema.TargetDb, c.Name))) + ")");
		}
		if (schema.TargetDb == DbTargetType.SQLite)
		{
			foreach (DbRelationship rel in schema.Relationships.Where((DbRelationship r) => r.SourceTableId == table.Id))
			{
				DbColumn dbColumn = table.Columns.FirstOrDefault((DbColumn c) => c.Id == rel.SourceColumnId);
				DbTable dbTable = schema.FindTable(rel.TargetTableId);
				DbColumn dbColumn2 = schema.FindColumn(rel.TargetTableId, rel.TargetColumnId);
				if (dbColumn != null && dbTable != null && dbColumn2 != null)
				{
					list.Add($"    FOREIGN KEY ({Quote(schema.TargetDb, dbColumn.Name)}) REFERENCES {Quote(schema.TargetDb, dbTable.Name)}({Quote(schema.TargetDb, dbColumn2.Name)})");
				}
			}
		}
		sb.AppendLine(string.Join(",\n", list));
		sb.Append(")");
		DbTargetType targetDb = schema.TargetDb;
		if ((uint)(targetDb - 1) <= 1u)
		{
			sb.Append(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
			if (!string.IsNullOrWhiteSpace(table.Comment))
			{
				stringBuilder = sb;
				StringBuilder stringBuilder4 = stringBuilder;
				handler = new StringBuilder.AppendInterpolatedStringHandler(11, 1, stringBuilder);
				handler.AppendLiteral(" COMMENT='");
				handler.AppendFormatted(EscapeString(table.Comment));
				handler.AppendLiteral("'");
				stringBuilder4.Append(ref handler);
			}
		}
		sb.AppendLine(";");
		if (schema.TargetDb != DbTargetType.PostgreSQL)
		{
			return;
		}
		foreach (DbColumn item in table.Columns.Where((DbColumn c) => !string.IsNullOrWhiteSpace(c.Comment)))
		{
			stringBuilder = sb;
			StringBuilder stringBuilder5 = stringBuilder;
			handler = new StringBuilder.AppendInterpolatedStringHandler(26, 3, stringBuilder);
			handler.AppendLiteral("COMMENT ON COLUMN ");
			handler.AppendFormatted(Quote(schema.TargetDb, table.Name));
			handler.AppendLiteral(".");
			handler.AppendFormatted(Quote(schema.TargetDb, item.Name));
			handler.AppendLiteral(" IS '");
			handler.AppendFormatted(EscapeString(item.Comment));
			handler.AppendLiteral("';");
			stringBuilder5.AppendLine(ref handler);
		}
		if (!string.IsNullOrWhiteSpace(table.Comment))
		{
			stringBuilder = sb;
			StringBuilder stringBuilder6 = stringBuilder;
			handler = new StringBuilder.AppendInterpolatedStringHandler(24, 2, stringBuilder);
			handler.AppendLiteral("COMMENT ON TABLE ");
			handler.AppendFormatted(Quote(schema.TargetDb, table.Name));
			handler.AppendLiteral(" IS '");
			handler.AppendFormatted(EscapeString(table.Comment));
			handler.AppendLiteral("';");
			stringBuilder6.AppendLine(ref handler);
		}
	}

	private static string GetColumnDdl(DbColumn col, DbSchema schema)
	{
		StringBuilder stringBuilder = new StringBuilder();
		string columnType = GetColumnType(col, schema.TargetDb);
		DbTargetType targetDb = schema.TargetDb;
		StringBuilder stringBuilder2 = stringBuilder;
		StringBuilder stringBuilder3 = stringBuilder2;
		StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(1, 2, stringBuilder2);
		handler.AppendFormatted(Quote(targetDb, col.Name));
		handler.AppendLiteral(" ");
		handler.AppendFormatted(columnType);
		stringBuilder3.Append(ref handler);
		if (col.IsPrimaryKey)
		{
			List<DbColumn> list = schema.Tables.FirstOrDefault((DbTable t) => t.Columns.Any((DbColumn c) => c.Id == col.Id))?.Columns.Where((DbColumn c) => c.IsPrimaryKey).ToList() ?? new List<DbColumn>();
			if (list.Count == 1 && col.IsAutoIncrement)
			{
				string autoIncrementKeyword = DataTypeProvider.GetAutoIncrementKeyword(targetDb, col.DataType);
				if (!string.IsNullOrEmpty(autoIncrementKeyword))
				{
					stringBuilder2 = stringBuilder;
					StringBuilder stringBuilder4 = stringBuilder2;
					handler = new StringBuilder.AppendInterpolatedStringHandler(1, 1, stringBuilder2);
					handler.AppendLiteral(" ");
					handler.AppendFormatted(autoIncrementKeyword);
					stringBuilder4.Append(ref handler);
				}
			}
			if (list.Count == 1)
			{
				stringBuilder.Append(" PRIMARY KEY");
			}
			stringBuilder.Append(" NOT NULL");
		}
		else
		{
			if (!col.IsNullable)
			{
				stringBuilder.Append(" NOT NULL");
			}
			if (col.IsUnique)
			{
				stringBuilder.Append(" UNIQUE");
			}
		}
		if (!string.IsNullOrWhiteSpace(col.DefaultValue))
		{
			stringBuilder2 = stringBuilder;
			StringBuilder stringBuilder5 = stringBuilder2;
			handler = new StringBuilder.AppendInterpolatedStringHandler(9, 1, stringBuilder2);
			handler.AppendLiteral(" DEFAULT ");
			handler.AppendFormatted(col.DefaultValue);
			stringBuilder5.Append(ref handler);
		}
		bool flag = (uint)(targetDb - 1) <= 1u;
		if (flag && !string.IsNullOrWhiteSpace(col.Comment))
		{
			stringBuilder2 = stringBuilder;
			StringBuilder stringBuilder6 = stringBuilder2;
			handler = new StringBuilder.AppendInterpolatedStringHandler(11, 1, stringBuilder2);
			handler.AppendLiteral(" COMMENT '");
			handler.AppendFormatted(EscapeString(col.Comment));
			handler.AppendLiteral("'");
			stringBuilder6.Append(ref handler);
		}
		return stringBuilder.ToString();
	}

	private static string GetColumnType(DbColumn col, DbTargetType db)
	{
		string text = col.DataType.ToUpperInvariant();
		if (db == DbTargetType.PostgreSQL && col.IsPrimaryKey && col.IsAutoIncrement)
		{
			if ((text == "INTEGER" || text == "INT") ? true : false)
			{
				return "SERIAL";
			}
			if (text == "BIGINT")
			{
				return "BIGSERIAL";
			}
			if (text == "SMALLINT")
			{
				return "SMALLSERIAL";
			}
		}
		if (DataTypeProvider.TypeHasLength(text) && col.Length.HasValue)
		{
			return $"{col.DataType}({col.Length})";
		}
		if (DataTypeProvider.TypeHasPrecisionScale(text))
		{
			if (col.Precision.HasValue && col.Scale.HasValue)
			{
				return $"{col.DataType}({col.Precision},{col.Scale})";
			}
			if (col.Precision.HasValue)
			{
				return $"{col.DataType}({col.Precision})";
			}
		}
		return col.DataType;
	}

	private static void AppendForeignKey(StringBuilder sb, DbRelationship rel, DbSchema schema)
	{
		DbTable dbTable = schema.FindTable(rel.SourceTableId);
		DbTable dbTable2 = schema.FindTable(rel.TargetTableId);
		DbColumn dbColumn = schema.FindColumn(rel.SourceTableId, rel.SourceColumnId);
		DbColumn dbColumn2 = schema.FindColumn(rel.TargetTableId, rel.TargetColumnId);
		if (dbTable != null && dbTable2 != null && dbColumn != null && dbColumn2 != null)
		{
			string identifier = (string.IsNullOrWhiteSpace(rel.Name) ? ("fk_" + dbTable.Name + "_" + dbColumn.Name) : rel.Name);
			DbTargetType targetDb = schema.TargetDb;
			StringBuilder stringBuilder = sb;
			StringBuilder stringBuilder2 = stringBuilder;
			StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(12, 1, stringBuilder);
			handler.AppendLiteral("ALTER TABLE ");
			handler.AppendFormatted(Quote(targetDb, dbTable.Name));
			stringBuilder2.AppendLine(ref handler);
			stringBuilder = sb;
			StringBuilder stringBuilder3 = stringBuilder;
			handler = new StringBuilder.AppendInterpolatedStringHandler(19, 1, stringBuilder);
			handler.AppendLiteral("    ADD CONSTRAINT ");
			handler.AppendFormatted(Quote(targetDb, identifier));
			stringBuilder3.AppendLine(ref handler);
			stringBuilder = sb;
			StringBuilder stringBuilder4 = stringBuilder;
			handler = new StringBuilder.AppendInterpolatedStringHandler(18, 1, stringBuilder);
			handler.AppendLiteral("    FOREIGN KEY (");
			handler.AppendFormatted(Quote(targetDb, dbColumn.Name));
			handler.AppendLiteral(")");
			stringBuilder4.AppendLine(ref handler);
			stringBuilder = sb;
			StringBuilder stringBuilder5 = stringBuilder;
			handler = new StringBuilder.AppendInterpolatedStringHandler(18, 2, stringBuilder);
			handler.AppendLiteral("    REFERENCES ");
			handler.AppendFormatted(Quote(targetDb, dbTable2.Name));
			handler.AppendLiteral("(");
			handler.AppendFormatted(Quote(targetDb, dbColumn2.Name));
			handler.AppendLiteral(");");
			stringBuilder5.AppendLine(ref handler);
			sb.AppendLine();
		}
	}

	private static string Quote(DbTargetType db, string identifier)
	{
		var (text, text2) = GetQuotePair(db);
		return text + identifier + text2;
	}

	private static (string Open, string Close) GetQuotePair(DbTargetType db)
	{
		if (1 == 0)
		{
		}
		(string, string) result;
		switch (db)
		{
		case DbTargetType.MySQL:
		case DbTargetType.MariaDB:
			result = ("`", "`");
			break;
		case DbTargetType.SqlServer:
			result = ("[", "]");
			break;
		default:
			result = ("\"", "\"");
			break;
		}
		if (1 == 0)
		{
		}
		return result;
	}

	private static string EscapeString(string s)
	{
		return s.Replace("'", "''");
	}
}
