using VixReaderTest01.Utils;

namespace VixReaderTest01
{
    public partial class Main
    {
        // _lastSetSerialNumber 필드를 클래스에 추가합니다.
        private string _lastSetSerialNumber = "";

        private async void SetSerialNumber_Click(object sender, EventArgs e)
        {
            try
            {
                // 현재 디바이스 타입에 맞는 시리얼 번호 자동 생성 정보
                string autoGeneratedPrefix = GenerateSerialNumberFormat();
                
                // 🔧 다음 시리얼 번호 자동 증가 계산
                string suggestedProductNumber = GetNextProductNumber(autoGeneratedPrefix);
                
                // 커스텀 다이얼로그를 사용하여 시리얼 번호 입력받기 (제안된 번호 포함)
                string productNumber = ShowSerialNumberInputDialog(autoGeneratedPrefix, suggestedProductNumber);

                // 더 명확한 null/empty 체크
                if (string.IsNullOrWhiteSpace(productNumber))
                {
                    Logger.LogMessage(LogTextBox, "시리얼 번호 설정이 취소되었습니다.");
                    return;
                }

                // 4자리 숫자 검증
                if (!ValidateProductNumber(productNumber))
                {
                    Logger.LogMessage(LogTextBox, "❌ 올바르지 않은 제품 번호 형식입니다.");
                    Logger.LogMessage(LogTextBox, "📋 4자리 숫자를 입력해주세요 (예: 0001, 0123, 9999)");
                    
                    MessageBox.Show($"올바르지 않은 제품 번호 형식입니다.\n\n4자리 숫자를 입력해주세요.\n예시: 0001, 0123, 9999\n\n자동 생성된 접두사: {autoGeneratedPrefix}", 
                                  "제품 번호 형식 오류", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    return;
                }

                // 완전한 시리얼 번호 생성
                string fullSerialNumber = autoGeneratedPrefix + productNumber.PadLeft(4, '0');

                Logger.LogMessage(LogTextBox, "🔢 시리얼 번호 자동 생성 시작");
                Logger.LogMessage(LogTextBox, $"📋 자동 생성된 접두사: {autoGeneratedPrefix}");
                Logger.LogMessage(LogTextBox, $"📋 타입: {CurrentDeviceType}, 년도: {DateTime.Now.Year}, 주차: {GetWeekOfYear(DateTime.Now):D2}");
                Logger.LogMessage(LogTextBox, $"📋 입력된 제품 번호: {productNumber.PadLeft(4, '0')}");
                Logger.LogMessage(LogTextBox, $"🏷️  생성된 완전한 시리얼 번호: {fullSerialNumber}");

                await _serialNumberApi.SetSerialNumberAsync(fullSerialNumber);

                // 🔧 성공 후에 마지막으로 설정된 시리얼 번호 저장
                _lastSetSerialNumber = fullSerialNumber;
                Logger.LogMessage(LogTextBox, $"📝 다음 자동 증가를 위해 저장된 시리얼 번호: {_lastSetSerialNumber}");

                // 성공 시 설정한 시리얼 번호만 DB에 저장
                await SaveTestResult("Set Serial Number", fullSerialNumber);

                // 성공 시 TestResult 버튼을 초록색으로 설정
                UpdateTestResultButton(true);

                Logger.LogMessage(LogTextBox, $"✅ 시리얼 번호가 {fullSerialNumber}로 성공적으로 설정됨");
            }
            catch (Exception ex)
            {
                Logger.LogMessage(LogTextBox, $"❌ 시리얼 번호 설정 실패: {ex.Message}");

                // TLS 연결오류 확인하고 적절히 처리
                if (IsTlsError(ex.Message))
                {
                    HandleTlsConnectionError("DefaultState", ex.Message);
                }
                else
                {
                    // 실패 시 "FAIL"만 DB에 저장
                    await SaveTestResult("Set Serial Number", "FAIL");
                }

                // 실패 시 TestResult 버튼을 빨간색으로 설정
                UpdateTestResultButton(false);
            }
        }

        // 🔧 다음 제품 번호를 자동으로 계산하는 메서드 추가
        private string GetNextProductNumber(string currentPrefix)
        {
            try
            {
                // 이전에 설정한 시리얼 번호가 없으면 0001 반환
                if (string.IsNullOrEmpty(_lastSetSerialNumber))
                {
                    Logger.LogMessage(LogTextBox, "📋 이전 설정 기록이 없어 기본값 0001을 제안합니다.");
                    return "0001";
                }

                // 이전 시리얼 번호에서 접두사와 제품 번호 분리
                if (_lastSetSerialNumber.Length >= 4)
                {
                    string lastPrefix = _lastSetSerialNumber.Substring(0, _lastSetSerialNumber.Length - 4);
                    string lastProductNumber = _lastSetSerialNumber.Substring(_lastSetSerialNumber.Length - 4);

                    // 접두사가 같으면 제품 번호를 1 증가
                    if (lastPrefix == currentPrefix)
                    {
                        if (int.TryParse(lastProductNumber, out int lastNumber))
                        {
                            int nextNumber = lastNumber + 1;
                            
                            // 9999를 초과하면 0001로 순환
                            if (nextNumber > 9999)
                            {
                                Logger.LogMessage(LogTextBox, "⚠️ 제품 번호가 9999를 초과하여 0001로 순환합니다.");
                                nextNumber = 1;
                            }
                            
                            string nextProductNumber = nextNumber.ToString("D4");
                            Logger.LogMessage(LogTextBox, $"📈 이전 번호 {lastProductNumber}에서 자동 증가: {nextProductNumber}");
                            return nextProductNumber;
                        }
                    }
                    else
                    {
                        Logger.LogMessage(LogTextBox, "📋 접두사가 변경되어 기본값 0001을 제안합니다.");
                        Logger.LogMessage(LogTextBox, $"   이전 접두사: {lastPrefix} → 현재 접두사: {currentPrefix}");
                    }
                }

                // 파싱 실패 시 기본값 반환
                Logger.LogMessage(LogTextBox, "📋 이전 번호 분석 실패로 기본값 0001을 제안합니다.");
                return "0001";
            }
            catch (Exception ex)
            {
                Logger.LogMessage(LogTextBox, $"⚠️ 다음 번호 계산 중 오류: {ex.Message}. 기본값 0001을 사용합니다.");
                return "0001";
            }
        }

        // 🔧 커스텀 시리얼 번호 입력 다이얼로그 메서드 (제안 번호 매개변수 추가)
        private string ShowSerialNumberInputDialog(string autoGeneratedPrefix, string suggestedProductNumber = "0001")
        {
            Form inputDialog = new Form()
            {
                Width = 450,
                Height = 320,
                FormBorderStyle = FormBorderStyle.FixedDialog,
                Text = "시리얼 번호 설정",
                StartPosition = FormStartPosition.CenterParent,
                MaximizeBox = false,
                MinimizeBox = false
            };

            // 디바이스 타입 정보 라벨
            Label deviceTypeLabel = new Label()
            {
                Left = 20,
                Top = 20,
                Width = 400,
                Height = 20,
                Text = $"디바이스 타입: {CurrentDeviceType} ({(CurrentDeviceType == "M" ? "Mullion" : "Gang")})",
                Font = new Font("맑은 고딕", 9F, FontStyle.Bold)
            };

            // 자동 생성된 접두사 표시 라벨 (변경 불가능한 부분)
            Label prefixInfoLabel = new Label()
            {
                Left = 20,
                Top = 50,
                Width = 150,
                Height = 20,
                Text = "자동 생성된 접두사:",
                Font = new Font("맑은 고딕", 9F)
            };

            Label prefixLabel = new Label()
            {
                Left = 180,
                Top = 50,
                Width = 100,
                Height = 25,
                Text = autoGeneratedPrefix,
                Font = new Font("맑은 고딕", 12F, FontStyle.Bold),
                BackColor = Color.LightBlue,
                BorderStyle = BorderStyle.FixedSingle,
                TextAlign = ContentAlignment.MiddleCenter,
                ForeColor = Color.DarkBlue
            };

            // 구분자 라벨
            Label separatorLabel = new Label()
            {
                Left = 285,
                Top = 50,
                Width = 20,
                Height = 25,
                Text = "-",
                Font = new Font("맑은 고딕", 12F, FontStyle.Bold),
                TextAlign = ContentAlignment.MiddleCenter
            };

            // 🔧 자동 증가 안내 라벨 추가
            Label autoIncrementLabel = new Label()
            {
                Left = 20,
                Top = 85,
                Width = 400,
                Height = 20,
                Text = !string.IsNullOrEmpty(_lastSetSerialNumber) ? 
                       $"💡 자동 증가 제안: {suggestedProductNumber} (이전: {_lastSetSerialNumber.Substring(Math.Max(0, _lastSetSerialNumber.Length - 4))})" :
                       "💡 첫 번째 설정입니다",
                Font = new Font("맑은 고딕", 8.5F, FontStyle.Italic),
                ForeColor = Color.DarkGreen
            };

            // 제품 번호 입력 안내 라벨
            Label instructionLabel = new Label()
            {
                Left = 20,
                Top = 110,
                Width = 400,
                Height = 40,
                Text = $"4자리 제품 번호를 입력하세요:\n(예: 0001, 0123, 9999)\n완성 예시: {autoGeneratedPrefix}{suggestedProductNumber}",
                Font = new Font("맑은 고딕", 9F)
            };

            // 🔧 제품 번호 입력 텍스트박스 (제안된 번호로 초기화)
            TextBox productNumberTextBox = new TextBox()
            {
                Left = 310,
                Top = 50,
                Width = 100,
                Height = 25,
                Font = new Font("맑은 고딕", 12F, FontStyle.Bold),
                MaxLength = 4,
                Text = suggestedProductNumber, // 제안된 번호로 초기화
                TextAlign = HorizontalAlignment.Center
            };

            // 실시간 미리보기 라벨
            Label previewLabel = new Label()
            {
                Left = 20,
                Top = 165,
                Width = 400,
                Height = 30,
                Text = $"완성될 시리얼 번호: {autoGeneratedPrefix}{suggestedProductNumber}",
                Font = new Font("맑은 고딕", 10F, FontStyle.Bold),
                BackColor = Color.LightYellow,
                BorderStyle = BorderStyle.FixedSingle,
                TextAlign = ContentAlignment.MiddleLeft,
                ForeColor = Color.DarkGreen
            };

            // 텍스트박스 변경 이벤트로 실시간 미리보기 업데이트
            productNumberTextBox.TextChanged += (sender, e) =>
            {
                string currentInput = productNumberTextBox.Text ?? string.Empty;
                string paddedInput = string.IsNullOrEmpty(currentInput) ? "0000" : currentInput.PadLeft(4, '0');
                previewLabel.Text = $"완성될 시리얼 번호: {autoGeneratedPrefix}{paddedInput}";
            };

            // 숫자만 입력 가능하도록 제한
            productNumberTextBox.KeyPress += (sender, e) =>
            {
                if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar))
                {
                    e.Handled = true;
                }
            };

            // 확인 버튼
            Button confirmButton = new Button()
            {
                Text = "확인",
                Left = 250,
                Width = 80,
                Top = 220,
                Height = 35,
                DialogResult = DialogResult.OK,
                BackColor = Color.LightGreen,
                Font = new Font("맑은 고딕", 9F, FontStyle.Bold)
            };

            // 취소 버튼
            Button cancelButton = new Button()
            {
                Text = "취소",
                Left = 340,
                Width = 80,
                Top = 220,
                Height = 35,
                DialogResult = DialogResult.Cancel,
                BackColor = Color.LightCoral,
                Font = new Font("맑은 고딕", 9F, FontStyle.Bold)
            };

            // 컨트롤들을 다이얼로그에 추가
            inputDialog.Controls.Add(deviceTypeLabel);
            inputDialog.Controls.Add(prefixInfoLabel);
            inputDialog.Controls.Add(prefixLabel);
            inputDialog.Controls.Add(separatorLabel);
            inputDialog.Controls.Add(autoIncrementLabel); // 🔧 추가
            inputDialog.Controls.Add(instructionLabel);
            inputDialog.Controls.Add(productNumberTextBox);
            inputDialog.Controls.Add(previewLabel);
            inputDialog.Controls.Add(confirmButton);
            inputDialog.Controls.Add(cancelButton);

            inputDialog.AcceptButton = confirmButton;
            inputDialog.CancelButton = cancelButton;

            // 텍스트박스에 포커스 설정
            productNumberTextBox.Select();
            productNumberTextBox.SelectAll();

            // 다이얼로그 표시 및 결과 반환 - null 안전성 확보
            try
            {
                if (inputDialog.ShowDialog(this) == DialogResult.OK)
                {
                    // TextBox.Text는 null이 될 수 없지만, 안전을 위해 null 체크 추가
                    return productNumberTextBox.Text ?? string.Empty;
                }
                else
                {
                    return string.Empty; // 취소 시 빈 문자열 반환
                }
            }
            finally
            {
                // 리소스 정리
                inputDialog.Dispose();
            }
        }

        // 시리얼 번호 형식을 생성하는 메서드
        private string GenerateSerialNumberFormat()
        {
            string deviceType = CurrentDeviceType;
            int currentYear = DateTime.Now.Year;
            int yearSuffix = currentYear % 10; // 2025 -> 5
            int weekOfYear = GetWeekOfYear(DateTime.Now);
            
            return $"{deviceType}{yearSuffix}{weekOfYear:D2}"; // 예: M501
        }

        // 연도의 주차를 계산하는 메서드
        private int GetWeekOfYear(DateTime date)
        {
            var culture = System.Globalization.CultureInfo.CurrentCulture;
            var calendar = culture.Calendar;
            var calendarWeekRule = culture.DateTimeFormat.CalendarWeekRule;
            var firstDayOfWeek = culture.DateTimeFormat.FirstDayOfWeek;
    
            return calendar.GetWeekOfYear(date, calendarWeekRule, firstDayOfWeek);
        }

        // 4자리 제품 번호를 검증하는 메서드 (기존 3자리에서 4자리로 변경)
        private bool ValidateProductNumber(string productNumber)
        {
            if (string.IsNullOrWhiteSpace(productNumber))
            {
                Logger.LogMessage(LogTextBox, "❌ 제품 번호가 입력되지 않았습니다.");
                return false;
            }

            // 숫자만 포함되어야 함
            if (!productNumber.All(char.IsDigit))
            {
                Logger.LogMessage(LogTextBox, "❌ 제품 번호는 숫자만 포함해야 합니다.");
                return false;
            }

            // 1-4자리 숫자여야 함 (0001로 패딩될 것임)
            if (productNumber.Length < 1 || productNumber.Length > 4)
            {
                Logger.LogMessage(LogTextBox, "❌ 제품 번호는 1-4자리 숫자여야 합니다.");
                return false;
            }

            // 숫자 범위 검증 (1-9999)
            if (int.TryParse(productNumber, out int number))
            {
                if (number < 1 || number > 9999)
                {
                    Logger.LogMessage(LogTextBox, "❌ 제품 번호는 1-9999 범위의 숫자여야 합니다.");
                    return false;
                }
            }
            else
            {
                Logger.LogMessage(LogTextBox, "❌ 유효하지 않은 숫자 형식입니다.");
                return false;
            }

            return true;
        }
    }
}