using VixReaderTest01.Utils;

namespace VixReaderTest01
{
    public partial class Main
    {
        // _lastSetSerialNumber 필드를 클래스에 추가합니다.
        private string _lastSetSerialNumber = "";

        private async void SetSerialNumber_Click(object sender, EventArgs e)
        {
            try
            {
                string autoGeneratedPrefix = GenerateSerialNumberFormat();
                string suggestedProductNumber = GetNextProductNumber(autoGeneratedPrefix);

                var (prefix, productNumber, isOk) = ShowSerialNumberInputDialog(autoGeneratedPrefix, suggestedProductNumber);

                if (!isOk)
                {
                    Logger.LogMessage(LogTextBox, "시리얼 번호 설정이 취소되었습니다.");
                    return;
                }

                // 최종 시리얼 번호 조합
                string fullSerialNumber = prefix + productNumber.PadLeft(4, '0');

                // 전체 시리얼 번호 형식 검증: M/G + 3자리 숫자 + 4자리 숫자
                if (!IsValidSerialNumberFormat(fullSerialNumber, CurrentDeviceType))
                {
                    MessageBox.Show("시리얼 번호는 반드시 '" + CurrentDeviceType + "###NNNN' 형식이어야 합니다.\n예: M1230001, G0051234", "시리얼 번호 형식 오류", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    Logger.LogMessage(LogTextBox, $"❌ 잘못된 시리얼 번호 형식({fullSerialNumber})으로 인해 시리얼 번호 설정이 중단되었습니다.");
                    return;
                }

                Logger.LogMessage(LogTextBox, "🔢 시리얼 번호 자동 생성 시작");
                Logger.LogMessage(LogTextBox, $"📋 사용된 접두사: {prefix}");
                Logger.LogMessage(LogTextBox, $"📋 타입: {CurrentDeviceType}, 년도: {DateTime.Now.Year}, 주차: {GetWeekOfYear(DateTime.Now):D2}");
                Logger.LogMessage(LogTextBox, $"📋 입력된 제품 번호: {productNumber.PadLeft(4, '0')}");
                Logger.LogMessage(LogTextBox, $"🏷️  생성된 완전한 시리얼 번호: {fullSerialNumber}");

                await _serialNumberApi.SetSerialNumberAsync(fullSerialNumber);

                _lastSetSerialNumber = fullSerialNumber;
                Logger.LogMessage(LogTextBox, $"📝 다음 자동 증가를 위해 저장된 시리얼 번호: {_lastSetSerialNumber}");

                await SaveTestResult("Set Serial Number", fullSerialNumber);
                UpdateTestResultButton(true);

                Logger.LogMessage(LogTextBox, $"✅ 시리얼 번호가 {fullSerialNumber}로 성공적으로 설정됨");
            }
            catch (Exception ex)
            {
                Logger.LogMessage(LogTextBox, $"❌ 시리얼 번호 설정 실패: {ex.Message}");

                if (IsTlsError(ex.Message))
                {
                    HandleTlsConnectionError("DefaultState", ex.Message);
                }
                else
                {
                    await SaveTestResult("Set Serial Number", "FAIL");
                }
                UpdateTestResultButton(false);
            }
        }

        // 시리얼 번호 전체 형식 검증 메서드 추가
        private bool IsValidSerialNumberFormat(string serial, string deviceType)
        {
            // deviceType은 "M" 또는 "G"만 허용
            if (string.IsNullOrEmpty(serial) || serial.Length != 8)
                return false;
            if (!(deviceType == "M" || deviceType == "G"))
                return false;
            if (!serial.StartsWith(deviceType, StringComparison.OrdinalIgnoreCase))
                return false;
            // M/G + 3자리 숫자 + 4자리 숫자
            string numberPart = serial.Substring(1, 3);
            string productPart = serial.Substring(4, 4);
            return numberPart.All(char.IsDigit) && productPart.All(char.IsDigit);
        }

        // 🔧 다음 제품 번호를 자동으로 계산하는 메서드 추가
        private string GetNextProductNumber(string currentPrefix)
        {
            try
            {
                // 이전에 설정한 시리얼 번호가 없으면 0001 반환
                if (string.IsNullOrEmpty(_lastSetSerialNumber))
                {
                    Logger.LogMessage(LogTextBox, "📋 이전 설정 기록이 없어 기본값 0001을 제안합니다.");
                    return "0001";
                }

                // 이전 시리얼 번호에서 접두사와 제품 번호 분리
                if (_lastSetSerialNumber.Length >= 4)
                {
                    string lastPrefix = _lastSetSerialNumber.Substring(0, _lastSetSerialNumber.Length - 4);
                    string lastProductNumber = _lastSetSerialNumber.Substring(_lastSetSerialNumber.Length - 4);

                    // 접두사가 같으면 제품 번호를 1 증가
                    if (lastPrefix == currentPrefix)
                    {
                        if (int.TryParse(lastProductNumber, out int lastNumber))
                        {
                            int nextNumber = lastNumber + 1;
                            
                            // 9999를 초과하면 0001로 순환
                            if (nextNumber > 9999)
                            {
                                Logger.LogMessage(LogTextBox, "⚠️ 제품 번호가 9999를 초과하여 0001로 순환합니다.");
                                nextNumber = 1;
                            }
                            
                            string nextProductNumber = nextNumber.ToString("D4");
                            Logger.LogMessage(LogTextBox, $"📈 이전 번호 {lastProductNumber}에서 자동 증가: {nextProductNumber}");
                            return nextProductNumber;
                        }
                    }
                    else
                    {
                        Logger.LogMessage(LogTextBox, "📋 접두사가 변경되어 기본값 0001을 제안합니다.");
                        Logger.LogMessage(LogTextBox, $"   이전 접두사: {lastPrefix} → 현재 접두사: {currentPrefix}");
                    }
                }

                // 파싱 실패 시 기본값 반환
                Logger.LogMessage(LogTextBox, "📋 이전 번호 분석 실패로 기본값 0001을 제안합니다.");
                return "0001";
            }
            catch (Exception ex)
            {
                Logger.LogMessage(LogTextBox, $"⚠️ 다음 번호 계산 중 오류: {ex.Message}. 기본값 0001을 사용합니다.");
                return "0001";
            }
        }

        // 🔧 커스텀 시리얼 번호 입력 다이얼로그 메서드 (제안 번호 매개변수 추가)
        // 시리얼 번호 입력 다이얼로그: 접두어와 제품번호를 모두 반환
        private (string prefix, string productNumber, bool isOk) ShowSerialNumberInputDialog(string autoGeneratedPrefix, string suggestedProductNumber = "0001")
        {
            Form inputDialog = new Form()
            {
                Width = 450,
                Height = 360,
                FormBorderStyle = FormBorderStyle.FixedDialog,
                Text = "시리얼 번호 설정",
                StartPosition = FormStartPosition.CenterParent,
                MaximizeBox = false,
                MinimizeBox = false
            };

            // 디바이스 타입 정보 라벨
            Label deviceTypeLabel = new Label()
            {
                Left = 20,
                Top = 20,
                Width = 400,
                Height = 20,
                Text = $"디바이스 타입: {CurrentDeviceType} ({(CurrentDeviceType == "M" ? "Mullion" : "Gang")})",
                Font = new Font("맑은 고딕", 9F, FontStyle.Bold)
            };

            // 접두사 설명 라벨
            Label prefixInfoLabel = new Label()
            {
                Left = 20,
                Top = 50,
                Width = 150,
                Height = 20,
                Text = "접두사:",
                Font = new Font("맑은 고딕", 9F)
            };

            // 접두사 입력을 위한 텍스트 박스 (기본값으로 자동 생성된 접두사 사용)
            TextBox prefixTextBox = new TextBox()
            {
                Left = 180,
                Top = 50,
                Width = 100,
                Height = 25,
                Text = autoGeneratedPrefix,
                Font = new Font("맑은 고딕", 12F, FontStyle.Bold),
                MaxLength = 4,  // 접두사는 최대 4자리
                TextAlign = HorizontalAlignment.Center,
                BackColor = Color.LightBlue,
                ForeColor = Color.DarkBlue
            };

            // 구분자 라벨
            Label separatorLabel = new Label()
            {
                Left = 285,
                Top = 50,
                Width = 20,
                Height = 25,
                Text = "-",
                Font = new Font("맑은 고딕", 12F, FontStyle.Bold),
                TextAlign = ContentAlignment.MiddleCenter
            };

            // 🔧 제품 번호 입력 텍스트박스 (제안된 번호로 초기화)
            TextBox productNumberTextBox = new TextBox()
            {
                Left = 310,
                Top = 50,
                Width = 100,    
                Height = 25,
                Font = new Font("맑은 고딕", 12F, FontStyle.Bold),
                MaxLength = 4,
                Text = suggestedProductNumber, // 제안된 번호로 초기화
                TextAlign = HorizontalAlignment.Center
            };

            // 제품 번호 힌트 라벨
            Label productNumberHintLabel = new Label()
            {
                Left = 20,
                Top = 170,
                Width = 400,
                Height = 20,
                Text = "💡 제품 번호는 4자리 숫자로 입력해주세요 (예: 0001, 0123, 9999)",
                Font = new Font("맑은 고딕", 8F, FontStyle.Italic),
                ForeColor = Color.DarkGreen
            };

            // 실시간 미리보기 라벨
            Label previewLabel = new Label()
            {
                Left = 20,
                Top = 200,
                Width = 400,
                Height = 35,
                Text = $"완성될 시리얼 번호: {autoGeneratedPrefix}{suggestedProductNumber}",
                Font = new Font("맑은 고딕", 11F, FontStyle.Bold),
                BackColor = Color.LightYellow,
                BorderStyle = BorderStyle.FixedSingle,
                TextAlign = ContentAlignment.MiddleLeft,
                ForeColor = Color.DarkGreen
            };

            // 접두사 텍스트 박스 제한 (영문자와 숫자만 허용)
            prefixTextBox.KeyPress += (sender, e) =>
            {
                if (!char.IsControl(e.KeyChar) && !char.IsLetterOrDigit(e.KeyChar))
                {
                    e.Handled = true;
                }
            };

            // 제품 번호 텍스트 박스 제한 (숫자만 허용)
            productNumberTextBox.KeyPress += (sender, e) =>
            {
                if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar))
                {
                    e.Handled = true;
                }
            };

            // 텍스트 박스들의 변경 이벤트를 연결하여 실시간 미리보기 업데이트
            EventHandler updatePreview = (sender, e) =>
            {
                string currentPrefix = prefixTextBox.Text ?? string.Empty;
                string currentInput = productNumberTextBox.Text ?? string.Empty;
                string paddedInput = string.IsNullOrEmpty(currentInput) ? "0000" : currentInput.PadLeft(4, '0');
                previewLabel.Text = $"완성될 시리얼 번호: {currentPrefix}{paddedInput}";
            };

            prefixTextBox.TextChanged += updatePreview;
            productNumberTextBox.TextChanged += updatePreview;

            // 기본값 복원 버튼
            Button resetButton = new Button()
            {
                Text = "기본값 복원",
                Left = 20,
                Width = 110,
                Top = 250,
                Height = 35,
                Font = new Font("맑은 고딕", 9F),
                BackColor = Color.LightGray
            };

            resetButton.Click += (sender, e) =>
            {
                prefixTextBox.Text = GenerateSerialNumberFormat(); // 기본 접두사로 재설정
                productNumberTextBox.Text = suggestedProductNumber; // 제안된 제품 번호로 재설정
            };

            // 확인 버튼
            Button confirmButton = new Button()
            {
                Text = "확인",
                Left = 250,
                Width = 80,
                Top = 250,
                Height = 35,
                DialogResult = DialogResult.None, // 여기서 None으로 설정
                BackColor = Color.LightGreen,
                Font = new Font("맑은 고딕", 9F, FontStyle.Bold)
            };

            // 확인 버튼 클릭 시 검증
            confirmButton.Click += (sender, e) =>
            {
                string prefix = prefixTextBox.Text.Trim();
                string productNum = productNumberTextBox.Text.Trim();

                // 접두사 검증 (영문/숫자, 2~4자리)
                if (string.IsNullOrEmpty(prefix) || prefix.Length < 2 || prefix.Length > 4 || !prefix.All(char.IsLetterOrDigit))
                {
                    MessageBox.Show("접두사는 2~4자리의 영문자/숫자만 가능합니다.", "접두사 형식 오류", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    prefixTextBox.Focus();
                    return;
                }
                // 제품번호 검증 (ValidateProductNumber 재사용)
                if (!ValidateProductNumber(productNum))
                {
                    MessageBox.Show("제품 번호는 1~4자리의 숫자(1~9999)만 가능합니다.", "제품 번호 형식 오류", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    productNumberTextBox.Focus();
                    return;
                }
                // 검증 통과 시 다이얼로그 닫기
                inputDialog.DialogResult = DialogResult.OK;
                inputDialog.Close();
            };

            // 취소 버튼
            Button cancelButton = new Button()
            {
                Text = "취소",
                Left = 340,
                Width = 80,
                Top = 250,
                Height = 35,
                DialogResult = DialogResult.Cancel,
                BackColor = Color.LightCoral,
                Font = new Font("맑은 고딕", 9F, FontStyle.Bold)
            };

            // 컨트롤들을 다이얼로그에 추가
            inputDialog.Controls.Add(deviceTypeLabel);
            inputDialog.Controls.Add(prefixInfoLabel);
            inputDialog.Controls.Add(prefixTextBox);
            inputDialog.Controls.Add(separatorLabel);
            inputDialog.Controls.Add(productNumberTextBox);
            inputDialog.Controls.Add(productNumberHintLabel);
            inputDialog.Controls.Add(previewLabel);
            inputDialog.Controls.Add(resetButton);
            inputDialog.Controls.Add(confirmButton);
            inputDialog.Controls.Add(cancelButton);

            inputDialog.AcceptButton = confirmButton;
            inputDialog.CancelButton = cancelButton;

            // 제품 번호 텍스트박스에 포커스 설정
            productNumberTextBox.Select();
            productNumberTextBox.SelectAll();

            // 반환 값을 저장할 튜플
            string result = string.Empty;

            // 다이얼로그 표시 및 결과 반환 - null 안전성 확보
            try
            {
                if (inputDialog.ShowDialog(this) == DialogResult.OK)
                {
                    // 접두사와 제품 번호 가져오기
                    string prefix = prefixTextBox.Text.Trim();
                    string productNum = productNumberTextBox.Text.Trim();
                    
                    // 유효성 검사
                    if (string.IsNullOrEmpty(prefix))
                    {
                        MessageBox.Show("접두사가 비어 있습니다. 기본 접두사를 사용합니다.", 
                                       "경고", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                        prefix = autoGeneratedPrefix;
                    }
                    
                    // 접두사가 너무 긴 경우 처리
                    if (prefix.Length > 4)
                    {
                        prefix = prefix.Substring(0, 4);
                        MessageBox.Show("접두사는 최대 4자리까지만 허용됩니다.\n앞 4자리만 사용합니다.", 
                                       "경고", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    }
                    
                    // 전체 시리얼 번호 구성을 위해 접두사를 저장 (전역 변수에 저장하거나 필요에 따라 처리)
                    autoGeneratedPrefix = prefix; // 수정된 접두사를 사용
                    
                    // 제품 번호 반환 (기존 메서드 호환성 유지)
                    return (prefix, productNum, true);
                }
                else
                {
                    return ("", "", false); // 취소 시 빈 문자열 반환
                }
            }
            finally
            {
                // 리소스 정리
                inputDialog.Dispose();
            }
        }

        // 시리얼 번호 형식을 생성하는 메서드
        private string GenerateSerialNumberFormat()
        {
            string deviceType = CurrentDeviceType;
            int currentYear = DateTime.Now.Year;
            int yearSuffix = currentYear % 10; // 2025 -> 5
            int weekOfYear = GetWeekOfYear(DateTime.Now);
            
            return $"{deviceType}{yearSuffix}{weekOfYear:D2}"; // 예: M501
        }

        // 연도의 주차를 계산하는 메서드
        private int GetWeekOfYear(DateTime date)
        {
            var culture = System.Globalization.CultureInfo.CurrentCulture;
            var calendar = culture.Calendar;
            var calendarWeekRule = culture.DateTimeFormat.CalendarWeekRule;
            var firstDayOfWeek = culture.DateTimeFormat.FirstDayOfWeek;
    
            return calendar.GetWeekOfYear(date, calendarWeekRule, firstDayOfWeek);
        }

        // 4자리 제품 번호를 검증하는 메서드 (기존 3자리에서 4자리로 변경)
        private bool ValidateProductNumber(string productNumber)
        {
            if (string.IsNullOrWhiteSpace(productNumber))
            {
                Logger.LogMessage(LogTextBox, "❌ 제품 번호가 입력되지 않았습니다.");
                return false;
            }

            // 숫자만 포함되어야 함
            if (!productNumber.All(char.IsDigit))
            {
                Logger.LogMessage(LogTextBox, "❌ 제품 번호는 숫자만 포함해야 합니다.");
                return false;
            }

            // 1-4자리 숫자여야 함 (0001로 패딩될 것임)
            if (productNumber.Length < 1 || productNumber.Length > 4)
            {
                Logger.LogMessage(LogTextBox, "❌ 제품 번호는 1-4자리 숫자여야 합니다.");
                return false;
            }

            // 숫자 범위 검증 (1-9999)
            if (int.TryParse(productNumber, out int number))
            {
                if (number < 1 || number > 9999)
                {
                    Logger.LogMessage(LogTextBox, "❌ 제품 번호는 1-9999 범위의 숫자여야 합니다.");
                    return false;
                }
            }
            else
            {
                Logger.LogMessage(LogTextBox, "❌ 유효하지 않은 숫자 형식입니다.");
                return false;
            }

            return true;
        }
    }
}