-- Generated by DBTools
-- Database: OnlineShop
-- Target:   SQLite
-- Date:     2026-09-11 09:06:26

-- 회원 정보
CREATE TABLE "users" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 상품 카테고리
CREATE TABLE "categories" (
    "id" SERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT
);

-- 판매 상품
CREATE TABLE "products" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "price" DECIMAL(12,2) NOT NULL,
    "category_id" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY ("category_id") REFERENCES "categories"("id")
);

-- 주문 헤더
CREATE TABLE "orders" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "order_date" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    FOREIGN KEY ("user_id") REFERENCES "users"("id")
);

-- 주문 상세
CREATE TABLE "order_items" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "unit_price" DECIMAL(12,2) NOT NULL,
    FOREIGN KEY ("order_id") REFERENCES "orders"("id"),
    FOREIGN KEY ("product_id") REFERENCES "products"("id")
);
