-- Generated by DBTools
-- Database: OnlineShop
-- Target:   MySQL
-- Date:     2026-09-11 09:06:26

-- 회원 정보
CREATE TABLE `users` (
    `id` BIGSERIAL AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT '회원 ID',
    `username` VARCHAR(50) NOT NULL COMMENT '로그인 이름',
    `email` VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일',
    `created_at` TIMESTAMPTZ NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='회원 정보';

-- 상품 카테고리
CREATE TABLE `categories` (
    `id` SERIAL AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='상품 카테고리';

-- 판매 상품
CREATE TABLE `products` (
    `id` BIGSERIAL AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `price` DECIMAL(12,2) NOT NULL,
    `category_id` INTEGER NOT NULL COMMENT '카테고리 FK',
    `is_active` BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='판매 상품';

-- 주문 헤더
CREATE TABLE `orders` (
    `id` BIGSERIAL AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `user_id` BIGINT NOT NULL COMMENT '주문 회원 FK',
    `order_date` TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='주문 헤더';

-- 주문 상세
CREATE TABLE `order_items` (
    `id` BIGSERIAL AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `order_id` BIGINT NOT NULL,
    `product_id` BIGINT NOT NULL,
    `quantity` INTEGER NOT NULL DEFAULT 1,
    `unit_price` DECIMAL(12,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='주문 상세';

ALTER TABLE `products`
    ADD CONSTRAINT `fk_products_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `categories`(`id`);

ALTER TABLE `orders`
    ADD CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `users`(`id`);

ALTER TABLE `order_items`
    ADD CONSTRAINT `fk_order_items_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders`(`id`);

ALTER TABLE `order_items`
    ADD CONSTRAINT `fk_order_items_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `products`(`id`);
