// Compare this port's output against the files DBToolsWinV10 actually produced
// for the same OnlineShop sample. Skips itself when the reference project is
// not checked out beside this one.
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { suite, test, expect } from '../helpers/runner.mjs';
import { exportHelper, report, sampleSchema, serializer, sqlExporter } from '../helpers/core.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const REFERENCE = path.resolve(here, '../../../DBToolsWinV10/Template');
const available = existsSync(REFERENCE);

const sample = sampleSchema.createOnlineShopSchema();

/** Drop the generated-on banner lines so only real content is compared. */
function normalize(text) {
  return text
    .replace(/\r\n/g, '\n')
    .split('\n')
    .filter((line) => !/^-- (Generated by|Date:)/.test(line.trim()))
    .filter((line) => !/^- \*\*(작성 일시|프로젝트 파일)\*\*/.test(line.trim()))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/** Everything before the first ALTER TABLE — the CREATE TABLE half. */
function createTableSection(sql) {
  const index = sql.search(/^ALTER TABLE/m);
  return index < 0 ? sql : sql.slice(0, index);
}

/**
 * The report body. The cover page is an addition of this port, so comparison
 * starts at the document heading; anchored to a whole line because the cover's
 * "### 데이터베이스 설계 보고서" contains the body heading as a substring.
 */
function reportBody(markdown) {
  const match = /^# 데이터베이스 설계 보고서$/m.exec(markdown);
  return match ? markdown.slice(match.index) : markdown;
}

function reference(name) {
  return readFileSync(path.join(REFERENCE, name), 'utf8').replace(/^﻿/, '');
}

/** Parse the ALTER TABLE ... ADD CONSTRAINT blocks into structured endpoints. */
function foreignKeyBlocks(sql) {
  const re =
    /ALTER TABLE\s+(\S+)\s*\n\s*ADD CONSTRAINT\s+(\S+)\s*\n\s*FOREIGN KEY \((\S+)\)\s*\n\s*REFERENCES\s+([^(]+)\((\S+)\);/g;
  const strip = (v) => v.trim().replace(/^[`"[]|[`"\]]$/g, '');
  const out = [];
  let m;
  while ((m = re.exec(sql)) !== null) {
    out.push({ child: strip(m[1]), column: strip(m[3]), parent: strip(m[4]), parentColumn: strip(m[5]) });
  }
  return out;
}

suite('fidelity vs DBToolsWinV10', () => {
  if (!available) {
    test('reference project not present — skipped', () => {
      expect(true).toBeTruthy();
    });
  } else {
    for (const [target, file] of [
      ['PostgreSQL', 'OnlineShop_postgres.sql'],
      ['MySQL', 'OnlineShop_mysql.sql'],
      ['MariaDB', 'OnlineShop_mariadb.sql'],
    ]) {
      test(`${target}: the CREATE TABLE half is byte-identical`, () => {
        const ours = normalize(createTableSection(sqlExporter.exportSql(exportHelper.cloneForTarget(sample, target))));
        const theirs = normalize(createTableSection(reference(file)));
        expect(ours).toBe(theirs);
      });
    }

    test('the Markdown report body is byte-identical', () => {
      expect(normalize(reportBody(report.writeReport(sample)))).toBe(normalize(reportBody(reference('OnlineShop_report.md'))));
    });

    test('the project JSON has the same tables and column attributes', () => {
      const expected = JSON.parse(reference('OnlineShop.mdprj'));
      const actual = JSON.parse(serializer.serializeToString(sample));
      expect(actual.Name).toBe(expected.Name);
      expect(actual.TargetDb).toBe(expected.TargetDb);
      expect(actual.Tables).toHaveLength(expected.Tables.length);
      expect(actual.Relationships).toHaveLength(expected.Relationships.length);

      for (let i = 0; i < expected.Tables.length; i++) {
        const e = expected.Tables[i];
        const a = actual.Tables[i];
        expect(a.Id).toBe(e.Id);
        expect(a.Name).toBe(e.Name);
        expect(a.Columns).toHaveLength(e.Columns.length);
        for (let j = 0; j < e.Columns.length; j++) {
          for (const key of ['Id', 'Name', 'DataType', 'Length', 'Precision', 'Scale',
                             'IsPrimaryKey', 'IsAutoIncrement', 'IsNullable', 'IsUnique', 'DefaultValue']) {
            expect(a.Columns[j][key] ?? null).toBe(e.Columns[j][key] ?? null, `${e.Name}.${e.Columns[j].Name}.${key}`);
          }
        }
      }
    });

    test('the foreign key direction is corrected (documented deviation)', () => {
      const ours = foreignKeyBlocks(sqlExporter.exportSql(exportHelper.cloneForTarget(sample, 'PostgreSQL')));
      const theirs = foreignKeyBlocks(reference('OnlineShop_postgres.sql'));

      // The original declares the constraint on the parent, which no server accepts.
      expect(theirs[0].child).toBe('categories', 'original was expected to be inverted');

      expect(ours).toEqual([
        { child: 'products', column: 'category_id', parent: 'categories', parentColumn: 'id' },
        { child: 'orders', column: 'user_id', parent: 'users', parentColumn: 'id' },
        { child: 'order_items', column: 'order_id', parent: 'orders', parentColumn: 'id' },
        { child: 'order_items', column: 'product_id', parent: 'products', parentColumn: 'id' },
      ]);
    });
  }
});
