//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidiSheetMusic {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidiSheetMusic.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string aboutMenu {
            get {
                return ResourceManager.GetString("aboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Signature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string changeKeyMenu {
            get {
                return ResourceManager.GetString("changeKeyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Colors...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string chooseColorMenu {
            get {
                return ResourceManager.GetString("chooseColorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Note Colors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string chooseColorsTitle {
            get {
                return ResourceManager.GetString("chooseColorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Instruments...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string chooseInstrumentsMenu {
            get {
                return ResourceManager.GetString("chooseInstrumentsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Instruments For Each Track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string chooseInstrumentsTitle {
            get {
                return ResourceManager.GetString("chooseInstrumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string closeMenu {
            get {
                return ResourceManager.GetString("closeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string colorMenu {
            get {
                return ResourceManager.GetString("colorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combine Notes Within Interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string combineNotesMenu {
            get {
                return ResourceManager.GetString("combineNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combine All Tracks Into Two Staffs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string combineStaffMenu {
            get {
                return ResourceManager.GetString("combineStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deselect All Tracks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deselectAllTracksMenu {
            get {
                return ResourceManager.GetString("deselectAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Measure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string endMeasure {
            get {
                return ResourceManager.GetString("endMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string exitMenu {
            get {
                return ResourceManager.GetString("exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast Forward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string fastForward {
            get {
                return ResourceManager.GetString("fastForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string fileMenu {
            get {
                return ResourceManager.GetString("fileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help Contents...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string helpContentsMenu {
            get {
                return ResourceManager.GetString("helpContentsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string helpMenu {
            get {
                return ResourceManager.GetString("helpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large Notes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string largeNotesMenu {
            get {
                return ResourceManager.GetString("largeNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measure Length과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string measureMenu {
            get {
                return ResourceManager.GetString("measureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   milliseconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string milliseconds {
            get {
                return ResourceManager.GetString("milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute All Tracks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string muteAllTracksMenu {
            get {
                return ResourceManager.GetString("muteAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string notesMenu {
            get {
                return ResourceManager.GetString("notesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show One Staff Per Track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string oneStaffMenu {
            get {
                return ResourceManager.GetString("oneStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string openMenu {
            get {
                return ResourceManager.GetString("openMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Sample Song...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string openSampleSongMenu {
            get {
                return ResourceManager.GetString("openSampleSongMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Measures in a Loop...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string playMeasuresMenu {
            get {
                return ResourceManager.GetString("playMeasuresMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Selected Measures in a Loop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string playMeasuresTitle {
            get {
                return ResourceManager.GetString("playMeasuresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print Preview...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string previewMenu {
            get {
                return ResourceManager.GetString("previewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string printMenu {
            get {
                return ResourceManager.GetString("printMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pulses과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pulses {
            get {
                return ResourceManager.GetString("pulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rewind과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string rewind {
            get {
                return ResourceManager.GetString("rewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose a Sample MIDI Song과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string sampleSongTitle {
            get {
                return ResourceManager.GetString("sampleSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As Images...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string saveImagesMenu {
            get {
                return ResourceManager.GetString("saveImagesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As PDF...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string savePDFMenu {
            get {
                return ResourceManager.GetString("savePDFMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll Horizontally과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string scrollHorizMenu {
            get {
                return ResourceManager.GetString("scrollHorizMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll Vertically과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string scrollVertMenu {
            get {
                return ResourceManager.GetString("scrollVertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All Tracks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selectAllTracksMenu {
            get {
                return ResourceManager.GetString("selectAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set All To Piano과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setAllPiano {
            get {
                return ResourceManager.GetString("setAllPiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift Notes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftNotesMenu {
            get {
                return ResourceManager.GetString("shiftNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right 1/2 note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftRight12 {
            get {
                return ResourceManager.GetString("shiftRight12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right 1/4 note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftRight14 {
            get {
                return ResourceManager.GetString("shiftRight14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right 1/8 note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftRight18 {
            get {
                return ResourceManager.GetString("shiftRight18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right 3/4 note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftRight34 {
            get {
                return ResourceManager.GetString("shiftRight34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right 3/8 note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftRight38 {
            get {
                return ResourceManager.GetString("shiftRight38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right 5/8 note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftRight58 {
            get {
                return ResourceManager.GetString("shiftRight58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right 7/8 note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string shiftRight78 {
            get {
                return ResourceManager.GetString("shiftRight78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showDefault {
            get {
                return ResourceManager.GetString("showDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed Do-Re-Mi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showFixedDoReMi {
            get {
                return ResourceManager.GetString("showFixedDoReMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed Numbers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showFixedNumbers {
            get {
                return ResourceManager.GetString("showFixedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showLetters {
            get {
                return ResourceManager.GetString("showLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Note Letters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showLettersMenu {
            get {
                return ResourceManager.GetString("showLettersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Lyrics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showLyricsMenu {
            get {
                return ResourceManager.GetString("showLyricsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Measure Numbers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showMeasuresMenu {
            get {
                return ResourceManager.GetString("showMeasuresMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movable Do-Re-Mi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showMovableDoReMi {
            get {
                return ResourceManager.GetString("showMovableDoReMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movable Numbers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string showMovableNumbers {
            get {
                return ResourceManager.GetString("showMovableNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small Notes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string smallNotesMenu {
            get {
                return ResourceManager.GetString("smallNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split Track Into Two Staffs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splitStaffMenu {
            get {
                return ResourceManager.GetString("splitStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Measure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string startMeasure {
            get {
                return ResourceManager.GetString("startMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strConfirm {
            get {
                return ResourceManager.GetString("strConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s lyrics editing state. Close anyway ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strEditingMode {
            get {
                return ResourceManager.GetString("strEditingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Saving File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strErrorSave {
            get {
                return ResourceManager.GetString("strErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MidiSheetMusic was unable to save to file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strErrorSaveFile {
            get {
                return ResourceManager.GetString("strErrorSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit from Lyrics Edit mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strExitEditMenu {
            get {
                return ResourceManager.GetString("strExitEditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the menu File:Open or Drag &amp;&amp; Drop to select a MIDI file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strFileOpenInfo {
            get {
                return ResourceManager.GetString("strFileOpenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Midi Sheet Music Help Contents과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strHelpContents {
            get {
                return ResourceManager.GetString("strHelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Shade과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strLeftShade {
            get {
                return ResourceManager.GetString("strLeftShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left to start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strLeftToStartMenu {
            get {
                return ResourceManager.GetString("strLeftToStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (edited lyrics are discarded.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strLyricsDiscarded {
            get {
                return ResourceManager.GetString("strLyricsDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Midi Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strMIDIFiles {
            get {
                return ResourceManager.GetString("strMIDIFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to independent mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strModeChange {
            get {
                return ResourceManager.GetString("strModeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slave mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strModeTitle {
            get {
                return ResourceManager.GetString("strModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lyrics editing state.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strMsgLyricsEditMode_1 {
            get {
                return ResourceManager.GetString("strMsgLyricsEditMode_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Use mouse button to edit lyrics)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strMsgLyricsEditMode_2 {
            get {
                return ResourceManager.GetString("strMsgLyricsEditMode_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program runs at slave mode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strMsgSlaveMode {
            get {
                return ResourceManager.GetString("strMsgSlaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strNoShiftMenu {
            get {
                return ResourceManager.GetString("strNoShiftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strNoTransMenu {
            get {
                return ResourceManager.GetString("strNoTransMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are changed lyrics. Do you save them ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strQuerySave {
            get {
                return ResourceManager.GetString("strQuerySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Shade과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strRightShade {
            get {
                return ResourceManager.GetString("strRightShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save &amp;As...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strSaveAsMenu {
            get {
                return ResourceManager.GetString("strSaveAsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a Track to Edit Lyrics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strSelEditMenu {
            get {
                return ResourceManager.GetString("strSelEditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program is controlled by host program, so some controls and menus are disabled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string strSlaveModeInfo {
            get {
                return ResourceManager.GetString("strSlaveModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Signature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string timeSigMenu {
            get {
                return ResourceManager.GetString("timeSigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Tracks to Display과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string trackDisplayMenu {
            get {
                return ResourceManager.GetString("trackDisplayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string trackMenu {
            get {
                return ResourceManager.GetString("trackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Tracks to Mute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string trackMuteMenu {
            get {
                return ResourceManager.GetString("trackMuteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transpose과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string transposeMenu {
            get {
                return ResourceManager.GetString("transposeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unmute All Tracks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string unmuteAllTracksMenu {
            get {
                return ResourceManager.GetString("unmuteAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string useColorMenu {
            get {
                return ResourceManager.GetString("useColorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string viewMenu {
            get {
                return ResourceManager.GetString("viewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string volume {
            get {
                return ResourceManager.GetString("volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom to 100%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zoom100Menu {
            get {
                return ResourceManager.GetString("zoom100Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom to 150%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zoom150Menu {
            get {
                return ResourceManager.GetString("zoom150Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zoomInMenu {
            get {
                return ResourceManager.GetString("zoomInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zoomOutMenu {
            get {
                return ResourceManager.GetString("zoomOutMenu", resourceCulture);
            }
        }
    }
}
