/* ── Internationalization (한국어 / English) ──────────────────────────────── */
const LANGS = {
  ko: {
    logout: '로그아웃', settings: '설정', userMgmt: '사용자 관리',
    login: '로그인', loginTitle: 'MyKanban에 오신 것을 환영합니다',
    loginSub: '팀의 업무를 시각화하세요',
    idLabel: '아이디', pwLabel: '비밀번호', registerLink: '계정 등록 요청',
    backToLogin: '← 로그인으로 돌아가기',
    registerTitle: '등록 요청', registerSub: '관리자 승인 후 로그인할 수 있습니다',
    nameLabel: '이름', emailLabel: '이메일', submitRegister: '등록 요청',
    myBoards: '내 프로젝트', newBoard: '+ 새 프로젝트',
    boardEmpty: '아직 프로젝트가 없습니다. 새 프로젝트를 만들어 시작하세요!',
    createBoard: '새 프로젝트 만들기', boardName: '프로젝트 이름 *',
    boardDesc: '설명', create: '만들기', edit: '편집', delete: '삭제', cancel: '취소', save: '저장',
    owner: '소유자',
    backToBoards: '프로젝트 목록', addColumn: '+ 컬럼 추가', addCard: '+ 카드 추가',
    members: '멤버', summary: '요약', renameColumn: '이름 변경', deleteColumn: '컬럼 삭제',
    columnName: '컬럼 이름 *',
    cardTitle: '제목 *', cardDesc: '설명', assignee: '담당자', changeAssignee: '담당자 지정', dueDate: '마감일',
    attachments: '첨부파일', noAttach: '첨부파일 없음', attachFile: '파일 첨부',
    cardColor: '카드 배경색', deleteCard: '카드 삭제', cardEdit: '카드 편집', addCardTitle: '카드 추가',
    memberMgmt: '멤버 관리', projectOwner: '프로젝트 소유자', addMember: '멤버 추가',
    roleAdmin: '관리자', roleEditor: '편집자', roleViewer: '뷰어', removeBtn: '제거',
    allUsers: '전체 사용자', pendingApproval: '승인 대기', addUser: '+ 사용자 추가',
    approve: '승인', reject: '거부', active: '활성', pending: '대기', inactive: '비활성',
    admin: '관리자', user: '사용자', createdAt: '가입일', noUsers: '사용자가 없습니다.',
    noPending: '승인 대기 중인 요청이 없습니다.',
    role: '권한', status: '상태', addBtn: '추가', changeBtn: '변경',
    pwOptionalHint: '변경할 경우에만 입력',
    dbSettings: 'DB 설정', dbCurrent: '현재', dbChangeWarn: 'DB를 변경하면 사용자·관리자·프로젝트 데이터가 새 DB로 이전됩니다.',
    testConn: '연결 테스트', applyDb: '적용', resetSqlite: 'SQLite 초기화',
    dbSqliteDefault: '기본 (파일)', dbRemoteDefault: '원격 기본', dbFileHint: '비워두면 기본 경로 사용',
    dbConnSettings: '연결 설정', dbSqliteSettings: 'SQLite 파일 설정', dbFileBrowse: 'DB 파일 찾기',
    testingConn: '연결 테스트 중...',
    dbMissingTitle: '입력 필요', dbMissingIntro: '다음 항목을 입력해 주세요.',
    dbConnFailed: '연결 실패', dbConnSuccess: '연결에 성공했습니다.',
    dbChangeConfirm: 'DB를 변경하면 기존 사용자·관리자·프로젝트 데이터가 새 DB로 이전됩니다. 적용 후 다시 로그인해야 합니다. 계속하시겠습니까?',
    dbResetConfirm: 'SQLite3 기본 설정으로 초기화하시겠습니까?',
    host: '호스트', port: '포트', dbName: '데이터베이스명', dbUser: '사용자', dbPass: '비밀번호', dbFile: 'DB 파일 경로',
    profile: '내 프로필', displayName: '표시 이름', changePw: '비밀번호 변경',
    curPw: '현재 비밀번호', newPw: '새 비밀번호', confirmPw: '새 비밀번호 확인',
    summaryTitle: '프로젝트 요약', totalCards: '전체 카드', completedCards: '완료된 카드',
    overdueCards: '기한 초과', burndownChart: '번다운 차트', burndownChartFrom: '프로젝트 시작일 기준',
    cardsCreated: '생성', cardsCompleted: '완료',
    completionRate: '완료율', columnDist: '컬럼별 카드 분포',
    burndownRemaining: '남은 작업 (실제)', burndownIdeal: '이상적 번다운',
    burndownStartDate: '시작일', burndownEndDate: '종료일', burndownApply: '적용',
    burndownDateRequired: '시작일과 종료일을 선택하세요.',
    burndownDateInvalid: '시작일은 종료일보다 이전이어야 합니다.',
    burndownEndFuture: '종료일은 오늘 이후로 설정할 수 없습니다.',
    chartCardCount: '카드 수', chartCardTotal: '합계',
    exportReport: '리포트 생성', exportReportDesc: '요약 통계와 차트 이미지를 포함한 리포트를 저장합니다.',
    reportGenerating: '리포트 생성 중...', reportSaved: '리포트가 저장되었습니다.', reportNoData: '리포트 데이터가 없습니다.',
    backToKanban: '칸반 보드',
    exportProject: '프로젝트보내기 (.kprj)',
    importProject: '프로젝트 가져오기 (.kprj)',
    exportSuccess: '보내기 완료', importSuccess: '가져오기 완료. 새 프로젝트가 생성되었습니다.', importError: '가져오기 실패',
    menuProject: '프로젝트', menuView: '보기', menuAdmin: '관리', menuHelp: '도움말',
    programInfo: '프로그램 정보', aboutDescription: '멀티 플랫폼 칸반 보드 (Electron + Web)', aboutVersion: '버전', aboutBuild: '빌드',
    refresh: '새로 고침', refreshed: '새로 고침되었습니다.',
    themeToggle: '테마 전환', langToggle: '언어 전환', boardList: '프로젝트 목록',
    openSample: '샘플 프로젝트 열기', open: '열기',
    none: '없음', loading: '로딩 중...', ready: '준비', loadFailed: '로드 실패',
    lightMode: '라이트 모드', darkMode: '다크 모드', orDivider: '또는', langBtnTitle: '한/EN',
    adminRequired: '관리자 권한이 필요합니다.',
    loginRequired: '아이디와 비밀번호를 입력하세요.',
    userPwRequired: '아이디와 비밀번호는 필수입니다.',
    userCreated: '사용자가 추가되었습니다.', userSaved: '저장되었습니다.', userDeleted: '삭제되었습니다.',
    userApproved: '승인되었습니다.', userRejected: '거부되었습니다.',
    confirmDeleteUser: '이 사용자를 삭제하시겠습니까?',
    confirmTitle: '삭제 확인',
    confirmDeleteProject: '"{name}" 프로젝트를 삭제하시겠습니까? 모든 컬럼과 카드가 함께 삭제되며 복구할 수 없습니다.',
    confirmRemoveMember: '"{name}" 멤버를 프로젝트에서 제거하시겠습니까?',
    confirmDeleteColumn: '이 컬럼을 삭제하시겠습니까? 포함된 모든 카드가 함께 삭제됩니다.',
    confirmDeleteCard: '이 카드를 삭제하시겠습니까?',
    confirmContinue: '계속하시겠습니까?',
    cannotDeleteAdmin: '관리자 계정은 삭제할 수 없습니다.',
    confirmRejectUser: '이 등록 요청을 거부하고 삭제하시겠습니까?',
    profileSaved: '프로필이 저장되었습니다.', allFieldsRequired: '모든 필드를 입력하세요.',
    pwMismatch: '새 비밀번호가 일치하지 않습니다.', pwChanged: '비밀번호가 변경되었습니다.',
    fieldRequired: '필수', savedDone: '저장 완료', createdDone: '생성 완료', deletedDone: '삭제 완료',
    exportSaveFailed: '저장에 실패했습니다.',
    invalidKprj: '올바른 .kprj 파일이 아닙니다.',
    invalidKprjDetail: '올바른 .kprj 파일이 아닙니다.\n\n예상 형식: {"format":"mykanban-project",...}',
    sampleNotFound: '샘플 파일을 찾을 수 없습니다.',
    fileOpenFailed: '파일 열기 실패', fileReadFailed: '파일 읽기 실패',
    addColumnFirst: '먼저 컬럼을 추가하세요.',
    deleteCardFailed: '카드 삭제 실패',
    noMembers: '멤버가 없습니다.', memberAdded: '멤버가 추가되었습니다.', uploadFailed: '업로드 실패',
    ctxOpenBoard: '프로젝트를 엽니다', ctxEditBoard: '프로젝트 정보를 수정합니다',
    ctxExportBoard: '.kprj 파일로보냅니다', ctxDeleteBoard: '프로젝트를 삭제합니다',
    ctxAddCardCol: '이 컬럼에 카드를 추가합니다', ctxRenameCol: '컬럼 이름을 변경합니다',
    ctxDeleteCol: '이 컬럼을 삭제합니다', ctxEditCard: '카드 내용을 편집합니다', ctxDeleteCard: '이 카드를 삭제합니다',
    colorDefault: '기본', colorBlue: '파랑', colorGreen: '초록', colorYellow: '노랑',
    colorOrange: '주황', colorRed: '빨강', colorPurple: '보라', colorPink: '분홍', colorCyan: '청록',
    titleProjectMenu: '프로젝트 메뉴', titleCreateBoard: '새 Kanban 프로젝트를 만듭니다',
    titleImportProject: '.kprj 파일에서 프로젝트를 가져옵니다',
    titleExportProject: '현재 프로젝트를 .kprj 파일로보냅니다',
    titleLogout: '현재 계정에서 로그아웃합니다', titleViewMenu: '보기 메뉴',
    titleRefresh: '현재 화면을 새로 고침합니다 (F5)',
    titleThemeToggle: '라이트/다크 테마를 전환합니다', titleLangToggle: '한국어/영어를 전환합니다',
    titleBoardList: '프로젝트 목록으로 돌아갑니다', titleAdminMenu: '관리자 메뉴',
    titleUserMgmt: '사용자 계정을 관리합니다', titleSettings: '애플리케이션 설정을 변경합니다',
    titleHelpMenu: '도움말 메뉴', titleProgramInfo: '프로그램 정보를 표시합니다', dbInfoTitle: 'DB 연결 정보',
    serverError: '서버 오류', request: '요청', error: '오류', unknownError: '알 수 없는 오류가 발생했습니다.',
    errorCopied: '오류 내용이 복사되었습니다.', copied: '복사됨', copy: '복사', close: '닫기',
  },
  en: {
    logout: 'Logout', settings: 'Settings', userMgmt: 'User Management',
    login: 'Login', loginTitle: 'Welcome to MyKanban',
    loginSub: 'Visualize your team\'s work',
    idLabel: 'Username', pwLabel: 'Password', registerLink: 'Request Account Registration',
    backToLogin: '← Back to Login',
    registerTitle: 'Registration Request', registerSub: 'You can log in after admin approval',
    nameLabel: 'Name', emailLabel: 'Email', submitRegister: 'Submit Request',
    myBoards: 'My Projects', newBoard: '+ New Project',
    boardEmpty: 'No projects yet. Create a new project to get started!',
    createBoard: 'Create New Project', boardName: 'Project Name *',
    boardDesc: 'Description', create: 'Create', edit: 'Edit', delete: 'Delete', cancel: 'Cancel', save: 'Save',
    owner: 'Owner',
    backToBoards: 'Project List', addColumn: '+ Add Column', addCard: '+ Add Card',
    members: 'Members', summary: 'Summary', renameColumn: 'Rename', deleteColumn: 'Delete Column',
    columnName: 'Column Name *',
    cardTitle: 'Title *', cardDesc: 'Description', assignee: 'Assignee', changeAssignee: 'Assign', dueDate: 'Due Date',
    attachments: 'Attachments', noAttach: 'No attachments', attachFile: 'Attach File',
    cardColor: 'Card Color', deleteCard: 'Delete Card', cardEdit: 'Edit Card', addCardTitle: 'Add Card',
    memberMgmt: 'Member Management', projectOwner: 'Project Owner', addMember: 'Add Member',
    roleAdmin: 'Admin', roleEditor: 'Editor', roleViewer: 'Viewer', removeBtn: 'Remove',
    allUsers: 'All Users', pendingApproval: 'Pending Approval', addUser: '+ Add User',
    approve: 'Approve', reject: 'Reject', active: 'Active', pending: 'Pending', inactive: 'Inactive',
    admin: 'Admin', user: 'User', createdAt: 'Joined', noUsers: 'No users.', noPending: 'No pending requests.',
    role: 'Role', status: 'Status', addBtn: 'Add', changeBtn: 'Change',
    pwOptionalHint: 'leave blank to keep current',
    dbSettings: 'Database Settings', dbCurrent: 'Current', dbChangeWarn: 'Changing DB migrates users, admins, and project data to the new database.',
    testConn: 'Test Connection', applyDb: 'Apply', resetSqlite: 'Reset to SQLite',
    dbSqliteDefault: 'Default (file)', dbRemoteDefault: 'Remote default', dbFileHint: 'leave blank for default path',
    dbConnSettings: 'Connection Settings', dbSqliteSettings: 'SQLite File Settings', dbFileBrowse: 'Browse DB file',
    testingConn: 'Testing connection...',
    dbMissingTitle: 'Input Required', dbMissingIntro: 'Please fill in the following fields:',
    dbConnFailed: 'Connection Failed', dbConnSuccess: 'Connection successful.',
    dbChangeConfirm: 'Users, admins, and project data will be copied to the new database. You must log in again after applying. Continue?',
    dbResetConfirm: 'Reset to SQLite3 defaults?',
    host: 'Host', port: 'Port', dbName: 'Database', dbUser: 'Username', dbPass: 'Password', dbFile: 'DB File Path',
    profile: 'My Profile', displayName: 'Display Name', changePw: 'Change Password',
    curPw: 'Current Password', newPw: 'New Password', confirmPw: 'Confirm New Password',
    summaryTitle: 'Project Summary', totalCards: 'Total Cards', completedCards: 'Completed',
    overdueCards: 'Overdue', burndownChart: 'Burndown Chart', burndownChartFrom: 'From project start',
    cardsCreated: 'Created', cardsCompleted: 'Completed',
    completionRate: 'Completion Rate', columnDist: 'Cards by Column',
    burndownRemaining: 'Remaining Work (Actual)', burndownIdeal: 'Ideal Burndown',
    burndownStartDate: 'Start Date', burndownEndDate: 'End Date', burndownApply: 'Apply',
    burndownDateRequired: 'Select both start and end dates.',
    burndownDateInvalid: 'Start date must be on or before the end date.',
    burndownEndFuture: 'End date cannot be after today.',
    chartCardCount: 'Cards', chartCardTotal: 'Total',
    exportReport: 'Generate Report', exportReportDesc: 'Save a report with summary stats and chart images.',
    reportGenerating: 'Generating report...', reportSaved: 'Report saved.', reportNoData: 'No report data available.',
    backToKanban: 'Kanban Board',
    exportProject: 'Export Project (.kprj)',
    importProject: 'Import Project (.kprj)',
    exportSuccess: 'Export complete', importSuccess: 'Import complete. A new project was created.', importError: 'Import failed',
    menuProject: 'Project', menuView: 'View', menuAdmin: 'Admin', menuHelp: 'Help',
    programInfo: 'About', aboutDescription: 'Multi-platform Kanban Board (Electron + Web)', aboutVersion: 'Version', aboutBuild: 'Build',
    refresh: 'Refresh', refreshed: 'Refreshed.',
    themeToggle: 'Toggle Theme', langToggle: 'Toggle Language', boardList: 'Project List',
    openSample: 'Open Sample Project', open: 'Open',
    none: 'None', loading: 'Loading...', ready: 'Ready', loadFailed: 'Load failed',
    lightMode: 'Light mode', darkMode: 'Dark mode', orDivider: 'or', langBtnTitle: 'KO/EN',
    adminRequired: 'Admin access required.',
    loginRequired: 'Username and password are required.',
    userPwRequired: 'Username and password are required.',
    userCreated: 'User created.', userSaved: 'Saved.', userDeleted: 'Deleted.',
    userApproved: 'Approved.', userRejected: 'Rejected.',
    confirmDeleteUser: 'Delete this user?',
    confirmTitle: 'Confirm Delete',
    confirmDeleteProject: 'Delete project "{name}"? All columns and cards will be permanently removed.',
    confirmRemoveMember: 'Remove member "{name}" from this project?',
    confirmDeleteColumn: 'Delete this column? All cards in it will also be deleted.',
    confirmDeleteCard: 'Delete this card?',
    confirmContinue: 'Do you want to continue?',
    cannotDeleteAdmin: 'The administrator account cannot be deleted.',
    confirmRejectUser: 'Reject and delete this request?',
    profileSaved: 'Profile saved.', allFieldsRequired: 'All fields required.',
    pwMismatch: 'Passwords do not match.', pwChanged: 'Password changed.',
    fieldRequired: 'required', savedDone: 'Saved', createdDone: 'Created', deletedDone: 'Deleted',
    exportSaveFailed: 'Save failed.',
    invalidKprj: 'Invalid .kprj file.',
    invalidKprjDetail: 'Invalid .kprj file.\n\nExpected format: {"format":"mykanban-project",...}',
    sampleNotFound: 'Sample file not found.',
    fileOpenFailed: 'Failed to open file', fileReadFailed: 'Failed to read file',
    addColumnFirst: 'Add a column first.',
    deleteCardFailed: 'Failed to delete card',
    noMembers: 'No members.', memberAdded: 'Member added.', uploadFailed: 'Upload failed',
    ctxOpenBoard: 'Open this project', ctxEditBoard: 'Edit project info',
    ctxExportBoard: 'Export as .kprj file', ctxDeleteBoard: 'Delete this project',
    ctxAddCardCol: 'Add a card to this column', ctxRenameCol: 'Rename this column',
    ctxDeleteCol: 'Delete this column', ctxEditCard: 'Edit card content', ctxDeleteCard: 'Delete this card',
    colorDefault: 'Default', colorBlue: 'Blue', colorGreen: 'Green', colorYellow: 'Yellow',
    colorOrange: 'Orange', colorRed: 'Red', colorPurple: 'Purple', colorPink: 'Pink', colorCyan: 'Cyan',
    titleProjectMenu: 'Project menu', titleCreateBoard: 'Create a new Kanban project',
    titleImportProject: 'Import a project from a .kprj file',
    titleExportProject: 'Export current project as .kprj file',
    titleLogout: 'Log out of current account', titleViewMenu: 'View menu',
    titleRefresh: 'Refresh the current view (F5)',
    titleThemeToggle: 'Switch light/dark theme', titleLangToggle: 'Switch Korean/English',
    titleBoardList: 'Return to project list', titleAdminMenu: 'Admin menu',
    titleUserMgmt: 'Manage user accounts', titleSettings: 'Change application settings',
    titleHelpMenu: 'Help menu', titleProgramInfo: 'Show program information', dbInfoTitle: 'Database connection',
    serverError: 'Server error', request: 'Request', error: 'Error', unknownError: 'An unknown error occurred.',
    errorCopied: 'Error details copied.', copied: 'Copied', copy: 'Copy', close: 'Close',
  }
};

const I18n = (() => {
  let lang = localStorage.getItem('kanban-lang') || 'ko';

  function t(key, vars) {
    let str = (LANGS[lang] && LANGS[lang][key]) || (LANGS.ko[key]) || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replaceAll(`{${k}}`, v);
      });
    }
    return str;
  }

  function setLang(l) {
    lang = l;
    localStorage.setItem('kanban-lang', l);
    document.documentElement.lang = l;
  }

  function getLang() { return lang; }

  return { t, setLang, getLang };
})();
