<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon />
    <AssemblyName>EaxyMDV10</AssemblyName>
    <RootNamespace>EaxyMDV10</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.38.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Icons\h1.png" />
    <EmbeddedResource Include="Resources\Icons\h2.png" />
    <EmbeddedResource Include="Resources\Icons\h3.png" />
    <EmbeddedResource Include="Resources\Icons\h4.png" />
    <EmbeddedResource Include="Resources\Icons\h5.png" />
    <EmbeddedResource Include="Resources\Icons\h6.png" />
  </ItemGroup>

</Project>
