<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>DiffMergeWinV10.ico</ApplicationIcon>
    <AssemblyTitle>Diff &amp; Merge Win V10</AssemblyTitle>
    <Product>Diff &amp; Merge Win V10</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Include="DiffMergeWinV10.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
