import type { Language } from './appSettings'

export const text = {
  ko: {
    appName: 'My Music Station V1.0.0',
    title: '멀티 OS 플레이어',
    addFiles: '파일 추가',
    addFilesShort: '추가',
    openFolder: '폴더 열기',
    openFolderShort: '폴더',
    reopenFolder: '다시 열기',
    reopenFolderShort: '다시',
    savePlaylist: '플레이리스트 저장',
    savePlaylistShort: '저장',
    openPlaylist: '플레이리스트 열기',
    addRemote: 'URL 추가',
    addRemoteBusy: '오디오 준비 중…',
    addRemoteSuccess: '오디오를 불러와 재생합니다',
    addRemoteStreamSuccess: '오디오 스트림을 재생합니다',
    addRemoteExtractSuccess: '비디오에서 오디오를 추출해 재생합니다',
    addRemoteError: '링크에서 오디오를 가져올 수 없습니다',
    addTheme: '테마 추가',
    deleteTheme: '테마 삭제',
    exportTheme: '테마 파일 저장',
    importTheme: '테마 파일 열기',
    exportThemeSuccess: '테마 파일을 저장했습니다',
    importThemeSuccess: '테마 파일을 불러왔습니다',
    exportThemeError: '테마 파일을 저장할 수 없습니다',
    importThemeError: '테마 파일을 읽을 수 없습니다',
    appInfo: '프로그램 정보',
    settings: '설정',
    settingsGeneral: '일반',
    settingsWindow: '창 / 시스템',
    settingsAppearance: '배경',
    settingsPlayback: '재생',
    saveSettings: '설정 저장',
    settingsSaved: '설정을 저장했습니다',
    settingsSaveError: '설정을 저장할 수 없습니다',
    useSystemTray: '시스템 트레이 사용',
    useSystemTrayHint: '끄면 닫기 시 앱이 종료되고 트레이 아이콘이 숨겨집니다.',
    closeToTray: '닫기 시 시스템 트레이로 보내기',
    closeToTrayHint: '켜면 닫기(X)가 창만 숨기고 트레이에서 계속 실행합니다.',
    closeQuitApp: '앱 종료',
    closeQuitAppHint: '끄면 닫기(X)가 앱을 완전히 종료합니다. 트레이 아이콘도 숨겨집니다.',
    wallpaperEnabled: '배경 이미지 사용',
    wallpaperEnabledHint: 'background 폴더의 기본 이미지 또는 사용자 지정 이미지를 표시합니다.',
    wallpaperBuiltIn: '기본 배경',
    wallpaperChoose: '다른 이미지 선택',
    wallpaperClear: '배경 이미지 제거',
    wallpaperDim: '배경 어둡기',
    panelOpacity: '패널 불투명도',
    panelOpacityHint: '값을 낮출수록 배경이 더 비칩니다.',
    collapseTrackList: '곡 목록 접기',
    expandTrackList: '곡 목록 펼치기',
    wallpaperNone: '선택된 이미지 없음',
    wallpaperCustom: '사용자 지정',
    wallpaperFormats: '이미지 파일',
    rememberVolume: '종료 후 볼륨 기억',
    showSpectrum: '스펙트럼 표시',
    spectrumColorOrder: '스펙트럼 색 방향',
    spectrumBlueRed: '왼쪽 파랑 → 오른쪽 빨강',
    spectrumRedBlue: '왼쪽 빨강 → 오른쪽 파랑',
    flipSpectrumColors: '스펙트럼 색 좌우 반전',
    spectrumStyle: '스펙트럼 표시 방식',
    cycleSpectrumStyle: '스펙트럼 방식 전환',
    spectrumStyleBars: '막대',
    spectrumStyleMirror: '대칭 막대',
    spectrumStyleWave: '파형',
    spectrumStyleLine: '라인',
    spectrumStyleRadial: '원형',
    spectrumStyleDots: '도트',
    spectrumStyleBlocks: '블록',
    spectrumStyleRidge: '능선',
    spectrumStyleRing: '링',
    spectrumStyleNeedle: '니들',
    spectrumStylePulse: '펄스',
    spectrumStyleStripe: '스트라이프',
    spectrumStyleSpark: '스파크',
    spectrumStyleAurora: '오로라',
    spectrumStyleMatrix: '매트릭스',
    convertSave: '형식 변환 저장',
    convertSaveShort: '변환',
    languageShortEn: 'EN',
    languageShortKo: '한',
    convertFormat: '저장 형식',
    convertTrack: '대상 트랙',
    convertBusy: '변환 중…',
    convertSuccess: '변환 파일을 저장했습니다',
    convertError: '변환할 수 없습니다',
    convertNoTrack: '변환할 곡을 먼저 선택하세요',
    convertNoSource: '변환할 수 있는 오디오 소스가 없습니다',
    saveStream: '스트리밍 저장',
    saveStreamBusy: '스트리밍 저장 중…',
    saveStreamSuccess: '스트리밍 오디오를 저장했습니다',
    extractAudio: 'URL 오디오 저장',
    extractAudioShort: '추출',
    extractAudioHint: '비디오·미디어 링크는 오디오만 추출해 저장합니다. 직접 오디오 링크는 스트리밍 재생 후 변환 저장을 사용하세요.',
    extractUrl: '링크 주소',
    extractFormat: '저장 형식',
    extractQuality: '음질',
    extractQualityHigh: '고음질 (기본)',
    extractQualityMedium: '표준',
    extractQualityLow: '용량 절약',
    extractBusy: '오디오 추출 중…',
    extractSuccess: '오디오 파일을 저장했습니다',
    extractError: '오디오를 추출할 수 없습니다',
    extractNoUrl: '오디오를 추출할 링크를 입력하세요',
    extractAddToPlaylist: '저장 후 플레이리스트에 추가',
    reopenLastFolderOnStart: '시작 시 마지막 폴더 열기',
    tracksAlreadyLoaded: '이미 목록에 있는 항목은 건너뛰었습니다',
    folderNothingNew: '새 파일이 없어 다시 불러오지 않았습니다',
    folderProgressTitle: '폴더에서 곡 추가 중',
    folderScanning: '오디오 파일을 검색하는 중…',
    folderLoadingTracks: '곡 불러오는 중',
    downloadProgressTitle: '링크에서 다운로드 중',
    downloadPreparing: '준비 중…',
    downloadDownloading: '다운로드 중…',
    downloadConverting: '오디오 변환 중…',
    downloadFinishing: '마무리 중…',
    language: '언어',
    theme: '테마',
    themeMenu: '테마 선택',
    themeMenuOpen: '테마 메뉴',
    themePickerHint: '색상을 보고 테마를 고르세요. 도구 모음의 테마 버튼은 다음 테마로 넘어갑니다.',
    miniMode: '최소 크기 모드',
    restoreNormalMode: '정상 모드로 복귀',
    minimize: '최소화',
    close: '닫기',
    confirm: '확인',
    quitApp: '종료',
    previous: '이전 곡',
    play: '재생',
    pause: '일시정지',
    stop: '정지',
    next: '다음 곡',
    volume: '볼륨',
    mute: '볼륨 Off',
    unmute: '볼륨 On',
    speakerActive: '스피커 켜짐',
    speakerInactive: '스피커 꺼짐',
    position: '재생 위치',
    remoteUrl: '미디어·오디오 URL',
    noTrack: '음악을 추가하세요',
    playlist: '재생 목록',
    removeTrack: '목록에서 삭제',
    contextSaveDownload: '다운로드 오디오 저장',
    contextPlay: '재생',
    folder: '폴더',
    formats: 'MP3 FLAC WAV OGG AAC M4A WebM OPUS WMA AIFF',
    themeName: '테마 이름',
    accent: '강조색',
    local: '로컬',
    remote: '원격',
    noAlbumArt: '앨범 이미지 없음',
    playbackError: '재생할 수 없습니다',
    saveError: '저장할 수 없습니다',
    saveEmpty: '저장할 재생 목록이 없습니다',
    saveNoPersistable: '경로가 있는 로컬 파일이나 URL만 저장할 수 있습니다. 폴더 열기/파일 열기를 사용하세요.',
    saveSuccess: '재생 목록을 저장했습니다',
    statusReady: '준비됨',
    statusPlaying: '재생 중',
    statusPaused: '일시정지',
    statusStopped: '정지',
    statusTrayOn: '트레이 사용',
    statusTrayOff: '트레이 끄기',
    statusWallpaperOn: '배경 사용',
    statusWallpaperOff: '배경 없음',
    statusBar: '상태바',
    errorDialog: '오류',
    errorDialogHint: '아래 내용을 선택하거나 복사할 수 있습니다.',
    copyError: '내용 복사',
    copied: '복사됨',
    copyFailed: '클립보드에 복사하지 못했습니다',
    version: '버전',
    build: '빌드',
    author: '작성자',
    copyright: '저작권',
    copyrightText: 'Copyright (c) 2026 SHKWON. 모든 권리 보유.',
  },
  en: {
    appName: 'My Music Station V1.0.0',
    title: 'Multi OS Player',
    addFiles: 'Add files',
    addFilesShort: 'Add',
    openFolder: 'Open folder',
    openFolderShort: 'Open',
    reopenFolder: 'Reopen',
    reopenFolderShort: 'Reopen',
    savePlaylist: 'Save playlist',
    savePlaylistShort: 'Save',
    openPlaylist: 'Open playlist',
    addRemote: 'Add URL',
    addRemoteBusy: 'Preparing audio…',
    addRemoteSuccess: 'Audio ready — playing',
    addRemoteStreamSuccess: 'Streaming audio',
    addRemoteExtractSuccess: 'Extracted audio from video — playing',
    addRemoteError: 'Could not get audio from this link',
    addTheme: 'Add theme',
    deleteTheme: 'Delete theme',
    exportTheme: 'Save theme file',
    importTheme: 'Open theme file',
    exportThemeSuccess: 'Theme file saved',
    importThemeSuccess: 'Theme file loaded',
    exportThemeError: 'Cannot save theme file',
    importThemeError: 'Cannot read theme file',
    appInfo: 'About',
    settings: 'Settings',
    settingsGeneral: 'General',
    settingsWindow: 'Window / System',
    settingsAppearance: 'Background',
    settingsPlayback: 'Playback',
    saveSettings: 'Save settings',
    settingsSaved: 'Settings saved',
    settingsSaveError: 'Could not save settings',
    useSystemTray: 'Use system tray',
    useSystemTrayHint: 'When off, Close quits the app and the tray icon is hidden.',
    closeToTray: 'Send to system tray on close',
    closeToTrayHint: 'When on, Close (X) hides the window and keeps the app in the tray.',
    closeQuitApp: 'Quit the app',
    closeQuitAppHint: 'When off, Close (X) fully quits the app and hides the tray icon.',
    wallpaperEnabled: 'Use background image',
    wallpaperEnabledHint: 'Show built-in images from the background folder, or a custom image.',
    wallpaperBuiltIn: 'Built-in backgrounds',
    wallpaperChoose: 'Choose another image',
    wallpaperClear: 'Clear background image',
    wallpaperDim: 'Background dim',
    panelOpacity: 'Panel opacity',
    panelOpacityHint: 'Lower values reveal more of the background.',
    collapseTrackList: 'Collapse track list',
    expandTrackList: 'Expand track list',
    wallpaperNone: 'No image selected',
    wallpaperCustom: 'Custom',
    wallpaperFormats: 'Image files',
    rememberVolume: 'Remember volume',
    showSpectrum: 'Show spectrum',
    spectrumColorOrder: 'Spectrum color direction',
    spectrumBlueRed: 'Left blue → right red',
    spectrumRedBlue: 'Left red → right blue',
    flipSpectrumColors: 'Flip spectrum colors',
    spectrumStyle: 'Spectrum style',
    cycleSpectrumStyle: 'Cycle spectrum style',
    spectrumStyleBars: 'Bars',
    spectrumStyleMirror: 'Mirror bars',
    spectrumStyleWave: 'Waveform',
    spectrumStyleLine: 'Line',
    spectrumStyleRadial: 'Radial',
    spectrumStyleDots: 'Dots',
    spectrumStyleBlocks: 'Blocks',
    spectrumStyleRidge: 'Ridge',
    spectrumStyleRing: 'Rings',
    spectrumStyleNeedle: 'Needles',
    spectrumStylePulse: 'Pulse',
    spectrumStyleStripe: 'Stripes',
    spectrumStyleSpark: 'Sparks',
    spectrumStyleAurora: 'Aurora',
    spectrumStyleMatrix: 'Matrix',
    convertSave: 'Convert & save',
    convertSaveShort: 'Convert',
    languageShortEn: 'EN',
    languageShortKo: '한',
    convertFormat: 'Output format',
    convertTrack: 'Track',
    convertBusy: 'Converting…',
    convertSuccess: 'Converted file saved',
    convertError: 'Cannot convert this track',
    convertNoTrack: 'Select a track to convert first',
    convertNoSource: 'No convertible audio source is available',
    saveStream: 'Save stream',
    saveStreamBusy: 'Saving stream…',
    saveStreamSuccess: 'Streamed audio saved',
    extractAudio: 'Save audio from URL',
    extractAudioShort: 'Extract',
    extractAudioHint: 'Video/media links extract audio only. Direct audio links stream for playback — use Convert & save to download them.',
    extractUrl: 'Link URL',
    extractFormat: 'Output format',
    extractQuality: 'Quality',
    extractQualityHigh: 'High (default)',
    extractQualityMedium: 'Standard',
    extractQualityLow: 'Smaller file',
    extractBusy: 'Extracting audio…',
    extractSuccess: 'Audio file saved',
    extractError: 'Cannot extract audio',
    extractNoUrl: 'Enter a link to extract audio from',
    extractAddToPlaylist: 'Add to playlist after saving',
    reopenLastFolderOnStart: 'Open last folder on start',
    tracksAlreadyLoaded: 'Skipped items already in the playlist',
    folderNothingNew: 'No new files to load',
    folderProgressTitle: 'Adding tracks from folder',
    folderScanning: 'Scanning for audio files…',
    folderLoadingTracks: 'Loading tracks',
    downloadProgressTitle: 'Downloading from link',
    downloadPreparing: 'Preparing…',
    downloadDownloading: 'Downloading…',
    downloadConverting: 'Converting audio…',
    downloadFinishing: 'Finishing…',
    language: 'Language',
    theme: 'Theme',
    themeMenu: 'Choose theme',
    themeMenuOpen: 'Theme menu',
    themePickerHint: 'Pick a theme by its colours. The toolbar theme button steps to the next one.',
    miniMode: 'Compact mode',
    restoreNormalMode: 'Back to normal mode',
    minimize: 'Minimize',
    close: 'Close',
    confirm: 'OK',
    quitApp: 'Quit',
    previous: 'Previous track',
    play: 'Play',
    pause: 'Pause',
    stop: 'Stop',
    next: 'Next track',
    volume: 'Volume',
    mute: 'Volume Off',
    unmute: 'Volume On',
    speakerActive: 'Speaker on',
    speakerInactive: 'Speaker off',
    position: 'Position',
    remoteUrl: 'Media or audio URL',
    noTrack: 'Add music to begin',
    playlist: 'Playlist',
    removeTrack: 'Remove from playlist',
    contextSaveDownload: 'Save downloaded audio',
    contextPlay: 'Play',
    folder: 'Folder',
    formats: 'MP3 FLAC WAV OGG AAC M4A WebM OPUS WMA AIFF',
    themeName: 'Theme name',
    accent: 'Accent',
    local: 'Local',
    remote: 'Remote',
    noAlbumArt: 'No album art',
    playbackError: 'Cannot play this track',
    saveError: 'Cannot save the playlist',
    saveEmpty: 'There is no playlist to save',
    saveNoPersistable: 'Only local files with paths or remote URLs can be saved. Use Open folder / Open files.',
    saveSuccess: 'Playlist saved',
    statusReady: 'Ready',
    statusPlaying: 'Playing',
    statusPaused: 'Paused',
    statusStopped: 'Stopped',
    statusTrayOn: 'Tray on',
    statusTrayOff: 'Tray off',
    statusWallpaperOn: 'Wallpaper on',
    statusWallpaperOff: 'No wallpaper',
    statusBar: 'Status bar',
    errorDialog: 'Error',
    errorDialogHint: 'You can select or copy the details below.',
    copyError: 'Copy details',
    copied: 'Copied',
    copyFailed: 'Could not copy to the clipboard',
    version: 'Version',
    build: 'Build',
    author: 'Author',
    copyright: 'Copyright',
    copyrightText: 'Copyright (c) 2026 SHKWON. All rights reserved.',
  },
} as const

export type Labels = (typeof text)[Language]
