<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.2.6" />
    <PackageReference Include="fo-dicom.Codecs" Version="5.16.7" />
    <PackageReference Include="fo-dicom.Imaging.Desktop" Version="5.2.6" />
  </ItemGroup>

</Project>