using System;
using System.Collections.Generic;
using System.Linq;

namespace MyClockWinV10.Models;

public record CityInfo(string City, string Country, string TimeZoneId, string CityEn = "");

public static class CityDatabase
{
    public static readonly IReadOnlyList<CityInfo> Cities = new CityInfo[]
    {
        // 대한민국
        new("서울",            "대한민국",      "Korea Standard Time",                "Seoul"),
        new("부산",            "대한민국",      "Korea Standard Time",                "Busan"),
        new("인천",            "대한민국",      "Korea Standard Time",                "Incheon"),
        new("대구",            "대한민국",      "Korea Standard Time",                "Daegu"),
        new("광주",            "대한민국",      "Korea Standard Time",                "Gwangju"),
        new("대전",            "대한민국",      "Korea Standard Time",                "Daejeon"),
        new("울산",            "대한민국",      "Korea Standard Time",                "Ulsan"),
        new("제주",            "대한민국",      "Korea Standard Time",                "Jeju"),
        // 일본
        new("도쿄",            "일본",          "Tokyo Standard Time",                "Tokyo"),
        new("오사카",          "일본",          "Tokyo Standard Time",                "Osaka"),
        new("나고야",          "일본",          "Tokyo Standard Time",                "Nagoya"),
        new("삿포로",          "일본",          "Tokyo Standard Time",                "Sapporo"),
        new("후쿠오카",        "일본",          "Tokyo Standard Time",                "Fukuoka"),
        new("교토",            "일본",          "Tokyo Standard Time",                "Kyoto"),
        new("히로시마",        "일본",          "Tokyo Standard Time",                "Hiroshima"),
        // 중국
        new("베이징",          "중국",          "China Standard Time",                "Beijing"),
        new("상하이",          "중국",          "China Standard Time",                "Shanghai"),
        new("광저우",          "중국",          "China Standard Time",                "Guangzhou"),
        new("선전",            "중국",          "China Standard Time",                "Shenzhen"),
        new("청두",            "중국",          "China Standard Time",                "Chengdu"),
        new("우한",            "중국",          "China Standard Time",                "Wuhan"),
        new("항저우",          "중국",          "China Standard Time",                "Hangzhou"),
        new("시안",            "중국",          "China Standard Time",                "Xi'an"),
        // 홍콩·마카오·대만
        new("홍콩",            "홍콩",          "China Standard Time",                "Hong Kong"),
        new("마카오",          "마카오",        "China Standard Time",                "Macau"),
        new("타이베이",        "대만",          "Taipei Standard Time",               "Taipei"),
        // 동남아시아
        new("싱가포르",        "싱가포르",      "Singapore Standard Time",            "Singapore"),
        new("방콕",            "태국",          "SE Asia Standard Time",              "Bangkok"),
        new("하노이",          "베트남",        "SE Asia Standard Time",              "Hanoi"),
        new("호치민",          "베트남",        "SE Asia Standard Time",              "Ho Chi Minh City"),
        new("자카르타",        "인도네시아",    "SE Asia Standard Time",              "Jakarta"),
        new("발리",            "인도네시아",    "Malay Peninsula Standard Time",      "Bali"),
        new("마닐라",          "필리핀",        "Singapore Standard Time",            "Manila"),
        new("쿠알라룸푸르",    "말레이시아",    "Singapore Standard Time",            "Kuala Lumpur"),
        new("양곤",            "미얀마",        "Myanmar Standard Time",              "Yangon"),
        new("프놈펜",          "캄보디아",      "SE Asia Standard Time",              "Phnom Penh"),
        // 남아시아
        new("뭄바이",          "인도",          "India Standard Time",                "Mumbai"),
        new("델리",            "인도",          "India Standard Time",                "Delhi"),
        new("콜카타",          "인도",          "India Standard Time",                "Kolkata"),
        new("벵갈루루",        "인도",          "India Standard Time",                "Bengaluru"),
        new("첸나이",          "인도",          "India Standard Time",                "Chennai"),
        new("하이데라바드",    "인도",          "India Standard Time",                "Hyderabad"),
        new("카라치",          "파키스탄",      "Pakistan Standard Time",             "Karachi"),
        new("라호르",          "파키스탄",      "Pakistan Standard Time",             "Lahore"),
        new("다카",            "방글라데시",    "Bangladesh Standard Time",           "Dhaka"),
        new("콜롬보",          "스리랑카",      "Sri Lanka Standard Time",            "Colombo"),
        new("카트만두",        "네팔",          "Nepal Standard Time",                "Kathmandu"),
        // 중앙아시아
        new("알마티",          "카자흐스탄",    "Central Asia Standard Time",         "Almaty"),
        new("타슈켄트",        "우즈베키스탄",  "West Asia Standard Time",            "Tashkent"),
        // 중동
        new("두바이",          "아랍에미리트",  "Arabian Standard Time",              "Dubai"),
        new("아부다비",        "아랍에미리트",  "Arabian Standard Time",              "Abu Dhabi"),
        new("리야드",          "사우디아라비아","Arab Standard Time",                 "Riyadh"),
        new("쿠웨이트",        "쿠웨이트",      "Arab Standard Time",                 "Kuwait"),
        new("도하",            "카타르",        "Arab Standard Time",                 "Doha"),
        new("바그다드",        "이라크",        "Arabic Standard Time",               "Baghdad"),
        new("테헤란",          "이란",          "Iran Standard Time",                 "Tehran"),
        new("텔아비브",        "이스라엘",      "Israel Standard Time",               "Tel Aviv"),
        new("예루살렘",        "이스라엘",      "Israel Standard Time",               "Jerusalem"),
        new("암만",            "요르단",        "Jordan Standard Time",               "Amman"),
        new("베이루트",        "레바논",        "Middle East Standard Time",          "Beirut"),
        // 튀르키예·러시아·유럽 동부
        new("이스탄불",        "튀르키예",      "Turkey Standard Time",               "Istanbul"),
        new("앙카라",          "튀르키예",      "Turkey Standard Time",               "Ankara"),
        new("모스크바",        "러시아",        "Russian Standard Time",              "Moscow"),
        new("상트페테르부르크","러시아",        "Russian Standard Time",              "St. Petersburg"),
        new("노보시비르스크",  "러시아",        "N. Central Asia Standard Time",      "Novosibirsk"),
        new("블라디보스토크",  "러시아",        "Vladivostok Standard Time",          "Vladivostok"),
        new("예카테린부르크",  "러시아",        "Ekaterinburg Standard Time",         "Yekaterinburg"),
        new("키이우",          "우크라이나",    "FLE Standard Time",                  "Kyiv"),
        new("부쿠레슈티",      "루마니아",      "GTB Standard Time",                  "Bucharest"),
        new("아테네",          "그리스",        "GTB Standard Time",                  "Athens"),
        new("소피아",          "불가리아",      "FLE Standard Time",                  "Sofia"),
        new("헬싱키",          "핀란드",        "FLE Standard Time",                  "Helsinki"),
        new("리가",            "라트비아",      "FLE Standard Time",                  "Riga"),
        new("탈린",            "에스토니아",    "FLE Standard Time",                  "Tallinn"),
        new("빌뉴스",          "리투아니아",    "FLE Standard Time",                  "Vilnius"),
        new("바르샤바",        "폴란드",        "Central European Standard Time",     "Warsaw"),
        new("프라하",          "체코",          "Central European Standard Time",     "Prague"),
        new("부다페스트",      "헝가리",        "Central European Standard Time",     "Budapest"),
        new("빈",              "오스트리아",    "W. Europe Standard Time",            "Vienna"),
        new("취리히",          "스위스",        "W. Europe Standard Time",            "Zurich"),
        new("제네바",          "스위스",        "W. Europe Standard Time",            "Geneva"),
        new("베를린",          "독일",          "W. Europe Standard Time",            "Berlin"),
        new("프랑크푸르트",    "독일",          "W. Europe Standard Time",            "Frankfurt"),
        new("뮌헨",            "독일",          "W. Europe Standard Time",            "Munich"),
        new("함부르크",        "독일",          "W. Europe Standard Time",            "Hamburg"),
        new("암스테르담",      "네덜란드",      "W. Europe Standard Time",            "Amsterdam"),
        new("브뤼셀",          "벨기에",        "Romance Standard Time",              "Brussels"),
        new("파리",            "프랑스",        "Romance Standard Time",              "Paris"),
        new("리옹",            "프랑스",        "Romance Standard Time",              "Lyon"),
        new("마드리드",        "스페인",        "Romance Standard Time",              "Madrid"),
        new("바르셀로나",      "스페인",        "Romance Standard Time",              "Barcelona"),
        new("로마",            "이탈리아",      "W. Europe Standard Time",            "Rome"),
        new("밀라노",          "이탈리아",      "W. Europe Standard Time",            "Milan"),
        new("런던",            "영국",          "GMT Standard Time",                  "London"),
        new("맨체스터",        "영국",          "GMT Standard Time",                  "Manchester"),
        new("에든버러",        "영국",          "GMT Standard Time",                  "Edinburgh"),
        new("더블린",          "아일랜드",      "GMT Standard Time",                  "Dublin"),
        new("리스본",          "포르투갈",      "GMT Standard Time",                  "Lisbon"),
        new("스톡홀름",        "스웨덴",        "W. Europe Standard Time",            "Stockholm"),
        new("오슬로",          "노르웨이",      "W. Europe Standard Time",            "Oslo"),
        new("코펜하겐",        "덴마크",        "Romance Standard Time",              "Copenhagen"),
        new("레이캬비크",      "아이슬란드",    "Greenwich Standard Time",            "Reykjavik"),
        // 아프리카
        new("카이로",          "이집트",        "Egypt Standard Time",                "Cairo"),
        new("카사블랑카",      "모로코",        "Morocco Standard Time",              "Casablanca"),
        new("라고스",          "나이지리아",    "W. Central Africa Standard Time",    "Lagos"),
        new("나이로비",        "케냐",          "E. Africa Standard Time",            "Nairobi"),
        new("요하네스버그",    "남아프리카공화국","South Africa Standard Time",        "Johannesburg"),
        new("케이프타운",      "남아프리카공화국","South Africa Standard Time",        "Cape Town"),
        new("아디스아바바",    "에티오피아",    "E. Africa Standard Time",            "Addis Ababa"),
        // 북미
        new("뉴욕",            "미국",          "Eastern Standard Time",              "New York"),
        new("워싱턴 DC",       "미국",          "Eastern Standard Time",              "Washington DC"),
        new("보스턴",          "미국",          "Eastern Standard Time",              "Boston"),
        new("마이애미",        "미국",          "Eastern Standard Time",              "Miami"),
        new("애틀란타",        "미국",          "Eastern Standard Time",              "Atlanta"),
        new("시카고",          "미국",          "Central Standard Time",              "Chicago"),
        new("휴스턴",          "미국",          "Central Standard Time",              "Houston"),
        new("댈러스",          "미국",          "Central Standard Time",              "Dallas"),
        new("덴버",            "미국",          "Mountain Standard Time",             "Denver"),
        new("피닉스",          "미국",          "US Mountain Standard Time",          "Phoenix"),
        new("로스앤젤레스",    "미국",          "Pacific Standard Time",              "Los Angeles"),
        new("샌프란시스코",    "미국",          "Pacific Standard Time",              "San Francisco"),
        new("시애틀",          "미국",          "Pacific Standard Time",              "Seattle"),
        new("라스베이거스",    "미국",          "Pacific Standard Time",              "Las Vegas"),
        new("호놀룰루",        "미국",          "Hawaiian Standard Time",             "Honolulu"),
        new("앵커리지",        "미국",          "Alaskan Standard Time",              "Anchorage"),
        new("토론토",          "캐나다",        "Eastern Standard Time",              "Toronto"),
        new("몬트리올",        "캐나다",        "Eastern Standard Time",              "Montreal"),
        new("밴쿠버",          "캐나다",        "Pacific Standard Time",              "Vancouver"),
        new("캘거리",          "캐나다",        "Mountain Standard Time",             "Calgary"),
        new("멕시코시티",      "멕시코",        "Central Standard Time (Mexico)",     "Mexico City"),
        // 중남미
        new("하바나",          "쿠바",          "Cuba Standard Time",                 "Havana"),
        new("보고타",          "콜롬비아",      "SA Pacific Standard Time",           "Bogotá"),
        new("리마",            "페루",          "SA Pacific Standard Time",           "Lima"),
        new("카라카스",        "베네수엘라",    "Venezuela Standard Time",            "Caracas"),
        new("산티아고",        "칠레",          "Pacific SA Standard Time",           "Santiago"),
        new("부에노스아이레스","아르헨티나",    "Argentina Standard Time",            "Buenos Aires"),
        new("상파울루",        "브라질",        "E. South America Standard Time",     "São Paulo"),
        new("리우데자네이루",  "브라질",        "E. South America Standard Time",     "Rio de Janeiro"),
        new("브라질리아",      "브라질",        "E. South America Standard Time",     "Brasília"),
        // 오세아니아
        new("시드니",          "호주",          "AUS Eastern Standard Time",          "Sydney"),
        new("멜버른",          "호주",          "AUS Eastern Standard Time",          "Melbourne"),
        new("브리즈번",        "호주",          "E. Australia Standard Time",         "Brisbane"),
        new("애들레이드",      "호주",          "Cen. Australia Standard Time",       "Adelaide"),
        new("퍼스",            "호주",          "W. Australia Standard Time",         "Perth"),
        new("오클랜드",        "뉴질랜드",      "New Zealand Standard Time",          "Auckland"),
        new("웰링턴",          "뉴질랜드",      "New Zealand Standard Time",          "Wellington"),
        // 추가 — 동아시아
        new("수원",            "대한민국",      "Korea Standard Time",                "Suwon"),
        new("창원",            "대한민국",      "Korea Standard Time",                "Changwon"),
        new("성남",            "대한민국",      "Korea Standard Time",                "Seongnam"),
        new("요코하마",        "일본",          "Tokyo Standard Time",                "Yokohama"),
        new("고베",            "일본",          "Tokyo Standard Time",                "Kobe"),
        new("센다이",          "일본",          "Tokyo Standard Time",                "Sendai"),
        new("오키나와",        "일본",          "Tokyo Standard Time",                "Okinawa"),
        new("난징",            "중국",          "China Standard Time",                "Nanjing"),
        new("톈진",            "중국",          "China Standard Time",                "Tianjin"),
        new("충칭",            "중국",          "China Standard Time",                "Chongqing"),
        new("하얼빈",          "중국",          "China Standard Time",                "Harbin"),
        new("다롄",            "중국",          "China Standard Time",                "Dalian"),
        new("쿤밍",            "중국",          "China Standard Time",                "Kunming"),
        new("가오슉",          "대만",          "Taipei Standard Time",               "Kaohsiung"),
        new("다낭",            "베트남",        "SE Asia Standard Time",              "Da Nang"),
        new("나트랑",          "베트남",        "SE Asia Standard Time",              "Nha Trang"),
        new("치앙마이",        "태국",          "SE Asia Standard Time",              "Chiang Mai"),
        new("푸켓",            "태국",          "SE Asia Standard Time",              "Phuket"),
        new("비엔티안",        "라오스",        "SE Asia Standard Time",              "Vientiane"),
        new("루앙프라방",      "라오스",        "SE Asia Standard Time",              "Luang Prabang"),
        new("브루나이",        "브루나이",      "Singapore Standard Time",            "Brunei"),
        new("수라바야",        "인도네시아",    "SE Asia Standard Time",              "Surabaya"),
        new("메단",            "인도네시아",    "SE Asia Standard Time",              "Medan"),
        new("다바오",          "필리핀",        "Singapore Standard Time",            "Davao"),
        new("세부",            "필리핀",        "Singapore Standard Time",            "Cebu"),
        // 추가 — 남아시아·중앙아시아
        new("아마다바드",      "인도",          "India Standard Time",                "Ahmedabad"),
        new("푸네",            "인도",          "India Standard Time",                "Pune"),
        new("자이푸르",        "인도",          "India Standard Time",                "Jaipur"),
        new("럭나우",          "인도",          "India Standard Time",                "Lucknow"),
        new("이슬라마바드",    "파키스탄",      "Pakistan Standard Time",             "Islamabad"),
        new("비슈케크",        "키르기스스탄",  "Central Asia Standard Time",         "Bishkek"),
        new("아슈하바트",      "투르크메니스탄","West Asia Standard Time",            "Ashgabat"),
        new("두샨베",          "타지키스탄",    "West Asia Standard Time",            "Dushanbe"),
        new("카불",            "아프가니스탄",  "Afghanistan Standard Time",          "Kabul"),
        // 추가 — 중동
        new("무스카트",        "오만",          "Arabian Standard Time",              "Muscat"),
        new("마나마",          "바레인",        "Arab Standard Time",                 "Manama"),
        new("제다",            "사우디아라비아","Arab Standard Time",                 "Jeddah"),
        new("메카",            "사우디아라비아","Arab Standard Time",                 "Mecca"),
        new("에르빌",          "이라크",        "Arabic Standard Time",               "Erbil"),
        new("라말라",          "팔레스타인",    "Israel Standard Time",               "Ramallah"),
        new("바쿠",            "아제르바이잔",  "Azerbaijan Standard Time",           "Baku"),
        new("트빌리시",        "조지아",        "Georgian Standard Time",             "Tbilisi"),
        new("예레반",          "아르메니아",    "Caucasus Standard Time",             "Yerevan"),
        // 추가 — 아프리카
        new("튀니스",          "튀니스",        "W. Central Africa Standard Time",    "Tunis"),
        new("알제",            "알제리",        "W. Central Africa Standard Time",    "Algiers"),
        new("아크라",          "가나",          "Greenwich Standard Time",            "Accra"),
        new("다카르",          "세네갈",        "Greenwich Standard Time",            "Dakar"),
        new("아비장",          "코트디부아르",  "Greenwich Standard Time",            "Abidjan"),
        new("다르에스살람",    "탄자니아",      "E. Africa Standard Time",            "Dar es Salaam"),
        new("캄팔라",          "우간다",        "E. Africa Standard Time",            "Kampala"),
        new("키갈리",          "르완다",        "South Africa Standard Time",         "Kigali"),
        new("하라레",          "짐바브웨",      "South Africa Standard Time",         "Harare"),
        new("루사카",          "잠비아",        "South Africa Standard Time",         "Lusaka"),
        new("하르트움",        "수단",          "Sudan Standard Time",                "Khartoum"),
        new("트리폴리",        "리비아",        "Libya Standard Time",                "Tripoli"),
        new("포트루이스",      "모리셔스",      "Mauritius Standard Time",            "Port Louis"),
        new("안타나나리보",    "마다가스카르",  "E. Africa Standard Time",            "Antananarivo"),
        // 추가 — 유럽
        new("나폴리",          "이탈리아",      "W. Europe Standard Time",            "Naples"),
        new("베네치아",        "이탈리아",      "W. Europe Standard Time",            "Venice"),
        new("토리노",          "이탈리아",      "W. Europe Standard Time",            "Turin"),
        new("세비야",          "스페인",        "Romance Standard Time",              "Seville"),
        new("발렌시아",        "스페인",        "Romance Standard Time",              "Valencia"),
        new("포르투",          "포르투갈",      "GMT Standard Time",                  "Porto"),
        new("글래스고",        "영국",          "GMT Standard Time",                  "Glasgow"),
        new("버밍엄",          "영국",          "GMT Standard Time",                  "Birmingham"),
        new("리버풀",          "영국",          "GMT Standard Time",                  "Liverpool"),
        new("마르세유",        "프랑스",        "Romance Standard Time",              "Marseille"),
        new("니스",            "프랑스",        "Romance Standard Time",              "Nice"),
        new("툴루즈",          "프랑스",        "Romance Standard Time",              "Toulouse"),
        new("쾰른",            "독일",          "W. Europe Standard Time",            "Cologne"),
        new("뒤셀도르프",      "독일",          "W. Europe Standard Time",            "Düsseldorf"),
        new("라이프치히",      "독일",          "W. Europe Standard Time",            "Leipzig"),
        new("드레스덴",        "독일",          "W. Europe Standard Time",            "Dresden"),
        new("크라쿠프",        "폴란드",        "Central European Standard Time",     "Krakow"),
        new("브라티슬라바",    "슬로바키아",    "Central European Standard Time",     "Bratislava"),
        new("자그레브",        "크로아티아",    "Central European Standard Time",     "Zagreb"),
        new("베오그라드",      "세르비아",      "Central European Standard Time",     "Belgrade"),
        new("류블랴나",        "슬로베니아",    "Central Europe Standard Time",       "Ljubljana"),
        new("사라예보",        "보스니아",      "Central European Standard Time",     "Sarajevo"),
        new("키시너우",        "몰도바",        "GTB Standard Time",                  "Chisinau"),
        new("민스크",          "벨라루스",      "Belarus Standard Time",              "Minsk"),
        new("카잔",            "러시아",        "Russian Standard Time",              "Kazan"),
        new("무르만스크",      "러시아",        "Russian Standard Time",              "Murmansk"),
        new("칼리닌그라드",    "러시아",        "Kaliningrad Standard Time",          "Kaliningrad"),
        new("오덴세",          "덴마크",        "Romance Standard Time",              "Odense"),
        new("베르겐",          "노르웨이",      "W. Europe Standard Time",            "Bergen"),
        new("트롬쇠",          "노르웨이",      "W. Europe Standard Time",            "Tromsø"),
        new("고텐부르크",      "스웨덴",        "W. Europe Standard Time",            "Gothenburg"),
        // 추가 — 북미
        new("필라델피아",      "미국",          "Eastern Standard Time",              "Philadelphia"),
        new("디트로이트",      "미국",          "Eastern Standard Time",              "Detroit"),
        new("미니애폴리스",    "미국",          "Central Standard Time",              "Minneapolis"),
        new("세인트루이스",    "미국",          "Central Standard Time",              "St. Louis"),
        new("뉴올리언스",      "미국",          "Central Standard Time",              "New Orleans"),
        new("오스틴",          "미국",          "Central Standard Time",              "Austin"),
        new("샌안토니오",      "미국",          "Central Standard Time",              "San Antonio"),
        new("포트랜드",        "미국",          "Pacific Standard Time",              "Portland"),
        new("샌디에이고",      "미국",          "Pacific Standard Time",              "San Diego"),
        new("새크라멘토",      "미국",          "Pacific Standard Time",              "Sacramento"),
        new("솔트레이크시티",  "미국",          "Mountain Standard Time",             "Salt Lake City"),
        new("샬럿",            "미국",          "Eastern Standard Time",              "Charlotte"),
        new("피츠버그",        "미국",          "Eastern Standard Time",              "Pittsburgh"),
        new("인디애나폴리스",  "미국",          "US Eastern Standard Time",           "Indianapolis"),
        new("내슈빌",          "미국",          "Central Standard Time",              "Nashville"),
        new("오타와",          "캐나다",        "Eastern Standard Time",              "Ottawa"),
        new("퀘벡",            "캐나다",        "Eastern Standard Time",              "Quebec City"),
        new("핼리팩스",        "캐나다",        "Atlantic Standard Time",             "Halifax"),
        new("위니펙",          "캐나다",        "Central Standard Time",              "Winnipeg"),
        new("에드먼턴",        "캐나다",        "Mountain Standard Time",             "Edmonton"),
        new("칸쿤",            "멕시코",        "Eastern Standard Time (Mexico)",     "Cancún"),
        new("티후아나",        "멕시코",        "Pacific Standard Time (Mexico)",     "Tijuana"),
        new("산후안",          "푸에르토리코",  "Atlantic Standard Time",             "San Juan"),
        new("킹스턴",          "자메이카",      "Eastern Standard Time",              "Kingston"),
        // 추가 — 중남미
        new("몬테비데오",      "우루과이",      "Montevideo Standard Time",           "Montevideo"),
        new("라파스",          "볼리비아",      "SA Western Standard Time",           "La Paz"),
        new("키토",            "에콰도르",      "SA Pacific Standard Time",           "Quito"),
        new("과야킬",          "에콰도르",      "SA Pacific Standard Time",           "Guayaquil"),
        new("파나마시티",      "파나마",        "SA Pacific Standard Time",           "Panama City"),
        new("산호세",          "코스타리카",    "Central America Standard Time",      "San José"),
        new("과테말라시티",    "과테말라",      "Central America Standard Time",      "Guatemala City"),
        new("산살바도르",      "엘살바도르",    "Central America Standard Time",      "San Salvador"),
        new("마나과",          "니카라과",      "Central America Standard Time",      "Managua"),
        new("아순시온",        "파라과이",      "Paraguay Standard Time",             "Asunción"),
        new("포르탈레자",      "브라질",        "SA Eastern Standard Time",           "Fortaleza"),
        new("마나우스",        "브라질",        "SA Western Standard Time",           "Manaus"),
        new("레시페",          "브라질",        "SA Eastern Standard Time",           "Recife"),
        new("살바도르",        "브라질",        "Bahia Standard Time",                "Salvador"),
        new("쿠리티바",        "브라질",        "E. South America Standard Time",     "Curitiba"),
        // 추가 — 오세아니아·태평양
        new("캔버라",          "호주",          "AUS Eastern Standard Time",          "Canberra"),
        new("골드코스트",      "호주",          "E. Australia Standard Time",         "Gold Coast"),
        new("다윈",            "호주",          "AUS Central Standard Time",          "Darwin"),
        new("호바트",          "호주",          "Tasmania Standard Time",             "Hobart"),
        new("크라이스트처치",  "뉴질랜드",      "New Zealand Standard Time",          "Christchurch"),
        new("퀸스타운",        "뉴질랜드",      "New Zealand Standard Time",          "Queenstown"),
        new("수바",            "피지",          "Fiji Standard Time",                 "Suva"),
        new("괌",              "괌",            "West Pacific Standard Time",         "Guam"),
        new("사이판",          "북마리아나",    "West Pacific Standard Time",         "Saipan"),
        new("포트모르즈",      "파푸아뉴기니",  "West Pacific Standard Time",         "Port Moresby"),
        new("타히티",          "프랑스령 폴리네시아","Hawaiian Standard Time",         "Tahiti"),
        new("누쿠알로파",      "통가",          "Tonga Standard Time",                "Nuku'alofa"),
        new("아피아",            "사모아",          "Samoa Standard Time",                "Apia"),
    };

    public static IEnumerable<CityInfo> Search(string query) =>
        string.IsNullOrWhiteSpace(query)
            ? Enumerable.Empty<CityInfo>()
            : Cities
                .Where(c =>
                    c.City.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                    c.CityEn.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                    c.Country.Contains(query, StringComparison.OrdinalIgnoreCase))
                .Take(20);

    public static IEnumerable<string> SearchCountries(string query) =>
        string.IsNullOrWhiteSpace(query)
            ? Enumerable.Empty<string>()
            : Cities
                .Select(c => c.Country)
                .Distinct()
                .Where(c => c.Contains(query, StringComparison.OrdinalIgnoreCase))
                .OrderBy(c => c)
                .Take(10);
}
