-- Generated by DBToolsWinV10
-- Database: OnlineShop
-- Target:   PostgreSQL
-- Date:     2026-06-17 13:37:24

-- 회원 정보
CREATE TABLE "users" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON COLUMN "users"."id" IS '회원 ID';
COMMENT ON COLUMN "users"."username" IS '로그인 이름';
COMMENT ON COLUMN "users"."email" IS '이메일';
COMMENT ON TABLE "users" IS '회원 정보';

-- 상품 카테고리
CREATE TABLE "categories" (
    "id" SERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT
);
COMMENT ON TABLE "categories" IS '상품 카테고리';

-- 판매 상품
CREATE TABLE "products" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "price" DECIMAL(12,2) NOT NULL,
    "category_id" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON COLUMN "products"."category_id" IS '카테고리 FK';
COMMENT ON TABLE "products" IS '판매 상품';

-- 주문 헤더
CREATE TABLE "orders" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "order_date" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);
COMMENT ON COLUMN "orders"."user_id" IS '주문 회원 FK';
COMMENT ON TABLE "orders" IS '주문 헤더';

-- 주문 상세
CREATE TABLE "order_items" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "unit_price" DECIMAL(12,2) NOT NULL
);
COMMENT ON TABLE "order_items" IS '주문 상세';

ALTER TABLE "categories"
    ADD CONSTRAINT "fk_products_category"
    FOREIGN KEY ("id")
    REFERENCES "products"("category_id");

ALTER TABLE "users"
    ADD CONSTRAINT "fk_orders_user"
    FOREIGN KEY ("id")
    REFERENCES "orders"("user_id");

ALTER TABLE "orders"
    ADD CONSTRAINT "fk_order_items_order"
    FOREIGN KEY ("id")
    REFERENCES "order_items"("order_id");

ALTER TABLE "products"
    ADD CONSTRAINT "fk_order_items_product"
    FOREIGN KEY ("id")
    REFERENCES "order_items"("product_id");

