// Themes.
//
// Each theme is a flat token map applied to :root as CSS custom properties, so
// every surface — including the SVG diagrams and the exported HTML report —
// picks up the same palette without any component knowing which theme is on.

/** Severity and diagram colors are per-theme so contrast survives on light grounds. */
export const THEMES = [
  {
    id: 'midnight',
    label: '미드나이트',
    labelEn: 'Midnight',
    mode: 'dark',
    tokens: {
      '--bg': '#12161c',
      '--bg-raised': '#1a2029',
      '--bg-panel': '#161b23',
      '--bg-input': '#0e1218',
      '--bg-hover': '#232b36',
      '--bg-active': '#2b3644',
      '--border': '#2a3441',
      '--border-strong': '#3b4859',
      '--text': '#e4e9f0',
      '--text-dim': '#97a3b4',
      '--text-faint': '#6b7789',
      '--accent': '#4cc9f0',
      '--accent-strong': '#4361ee',
      '--accent-text': '#06202b',
      '--accent-alt': '#a78bfa',
      '--accent-alt-hover': '#b9a3fb',
      '--accent-alt-text': '#1b1430',
      '--critical': '#ff6b6b',
      '--critical-bg': '#3a1c22',
      '--warning': '#ffb703',
      '--warning-bg': '#3a2f14',
      '--info': '#6fb3ff',
      '--info-bg': '#1c2a3a',
      '--ok': '#4ade80',
      '--ok-bg': '#16301f',
      '--diagram-bg': '#0e1218',
      '--diagram-grid': '#1c232c',
      '--node-fill': '#1e2733',
      '--node-stroke': '#3b4859',
      '--node-text': '#e4e9f0',
      '--edge': '#5a6b80',
      '--edge-highlight': '#4cc9f0',
      '--shadow': '0 6px 24px rgba(0,0,0,0.45)',
    },
  },
  {
    id: 'daylight',
    label: '데이라이트',
    labelEn: 'Daylight',
    mode: 'light',
    tokens: {
      '--bg': '#f6f7f9',
      '--bg-raised': '#ffffff',
      '--bg-panel': '#eef1f5',
      '--bg-input': '#ffffff',
      '--bg-hover': '#e4e9f0',
      '--bg-active': '#d6dee9',
      '--border': '#d3dae3',
      '--border-strong': '#aab6c5',
      '--text': '#1c2530',
      '--text-dim': '#586372',
      '--text-faint': '#8a94a3',
      '--accent': '#1565c0',
      '--accent-strong': '#0d47a1',
      '--accent-text': '#ffffff',
      '--accent-alt': '#6d28d9',
      '--accent-alt-hover': '#5b21b6',
      '--accent-alt-text': '#ffffff',
      '--critical': '#c62828',
      '--critical-bg': '#fde7e7',
      '--warning': '#b26a00',
      '--warning-bg': '#fdf3dd',
      '--info': '#1565c0',
      '--info-bg': '#e3f0fd',
      '--ok': '#2e7d32',
      '--ok-bg': '#e6f4e7',
      '--diagram-bg': '#ffffff',
      '--diagram-grid': '#eef1f5',
      '--node-fill': '#ffffff',
      '--node-stroke': '#aab6c5',
      '--node-text': '#1c2530',
      '--edge': '#8a94a3',
      '--edge-highlight': '#1565c0',
      '--shadow': '0 6px 20px rgba(20,30,45,0.12)',
    },
  },
  {
    id: 'nord',
    label: '노르드',
    labelEn: 'Nord',
    mode: 'dark',
    tokens: {
      '--bg': '#2e3440',
      '--bg-raised': '#3b4252',
      '--bg-panel': '#353c4a',
      '--bg-input': '#292e39',
      '--bg-hover': '#434c5e',
      '--bg-active': '#4c566a',
      '--border': '#434c5e',
      '--border-strong': '#5b6779',
      '--text': '#eceff4',
      '--text-dim': '#b6bfcd',
      '--text-faint': '#828c9d',
      '--accent': '#88c0d0',
      '--accent-strong': '#5e81ac',
      '--accent-text': '#2e3440',
      '--accent-alt': '#c4a1bd',
      '--accent-alt-hover': '#cdb0c8',
      '--accent-alt-text': '#2e3440',
      '--critical': '#bf616a',
      '--critical-bg': '#4a3138',
      '--warning': '#ebcb8b',
      '--warning-bg': '#4a4232',
      '--info': '#81a1c1',
      '--info-bg': '#333e4d',
      '--ok': '#a3be8c',
      '--ok-bg': '#3a4438',
      '--diagram-bg': '#292e39',
      '--diagram-grid': '#333a47',
      '--node-fill': '#3b4252',
      '--node-stroke': '#5b6779',
      '--node-text': '#eceff4',
      '--edge': '#77839a',
      '--edge-highlight': '#88c0d0',
      '--shadow': '0 6px 24px rgba(0,0,0,0.4)',
    },
  },
  {
    id: 'solarized',
    label: '솔라라이즈드',
    labelEn: 'Solarized',
    mode: 'light',
    tokens: {
      '--bg': '#fdf6e3',
      '--bg-raised': '#fffbf0',
      '--bg-panel': '#f3ecd8',
      '--bg-input': '#fffbf0',
      '--bg-hover': '#eee8d5',
      '--bg-active': '#e3ddc8',
      '--border': '#e0d8c0',
      '--border-strong': '#c0b89f',
      '--text': '#073642',
      '--text-dim': '#586e75',
      '--text-faint': '#93a1a1',
      '--accent': '#268bd2',
      '--accent-strong': '#1f6fa8',
      '--accent-text': '#fdf6e3',
      '--accent-alt': '#b02a6c',
      '--accent-alt-hover': '#9e2560',
      '--accent-alt-text': '#fdf6e3',
      '--critical': '#dc322f',
      '--critical-bg': '#fbe4e2',
      '--warning': '#b58900',
      '--warning-bg': '#f7eecd',
      '--info': '#268bd2',
      '--info-bg': '#e2eef8',
      '--ok': '#859900',
      '--ok-bg': '#eef2d9',
      '--diagram-bg': '#fffbf0',
      '--diagram-grid': '#f0e9d6',
      '--node-fill': '#fffbf0',
      '--node-stroke': '#c0b89f',
      '--node-text': '#073642',
      '--edge': '#93a1a1',
      '--edge-highlight': '#268bd2',
      '--shadow': '0 6px 20px rgba(88,110,117,0.18)',
    },
  },
  {
    id: 'contrast',
    label: '고대비',
    labelEn: 'High contrast',
    mode: 'dark',
    tokens: {
      '--bg': '#000000',
      '--bg-raised': '#0d0d0d',
      '--bg-panel': '#080808',
      '--bg-input': '#000000',
      '--bg-hover': '#1f1f1f',
      '--bg-active': '#2e2e2e',
      '--border': '#5a5a5a',
      '--border-strong': '#8c8c8c',
      '--text': '#ffffff',
      '--text-dim': '#d0d0d0',
      '--text-faint': '#a0a0a0',
      '--accent': '#00e5ff',
      '--accent-strong': '#00b8d4',
      '--accent-text': '#000000',
      '--accent-alt': '#ff9100',
      '--accent-alt-hover': '#ffa733',
      '--accent-alt-text': '#000000',
      '--critical': '#ff5252',
      '--critical-bg': '#3a0000',
      '--warning': '#ffd600',
      '--warning-bg': '#332b00',
      '--info': '#40c4ff',
      '--info-bg': '#00293a',
      '--ok': '#69f0ae',
      '--ok-bg': '#002e1a',
      '--diagram-bg': '#000000',
      '--diagram-grid': '#1a1a1a',
      '--node-fill': '#111111',
      '--node-stroke': '#8c8c8c',
      '--node-text': '#ffffff',
      '--edge': '#9e9e9e',
      '--edge-highlight': '#00e5ff',
      '--shadow': '0 0 0 1px #5a5a5a',
    },
  },
  {
    id: 'forest',
    label: '포레스트',
    labelEn: 'Forest',
    mode: 'dark',
    tokens: {
      '--bg': '#131a16',
      '--bg-raised': '#1c261f',
      '--bg-panel': '#18211b',
      '--bg-input': '#0f1512',
      '--bg-hover': '#243026',
      '--bg-active': '#2d3b30',
      '--border': '#2c3a2f',
      '--border-strong': '#3f5243',
      '--text': '#e3ece5',
      '--text-dim': '#9aab9e',
      '--text-faint': '#6d7d71',
      '--accent': '#7bd88f',
      '--accent-strong': '#3fa45c',
      '--accent-text': '#0d1a11',
      '--accent-alt': '#e0b64a',
      '--accent-alt-hover': '#ebc86a',
      '--accent-alt-text': '#1a1408',
      '--critical': '#e5714f',
      '--critical-bg': '#3a2118',
      '--warning': '#e0b64a',
      '--warning-bg': '#3a301a',
      '--info': '#6fc3d6',
      '--info-bg': '#193038',
      '--ok': '#7bd88f',
      '--ok-bg': '#1a3323',
      '--diagram-bg': '#0f1512',
      '--diagram-grid': '#1a231d',
      '--node-fill': '#1c261f',
      '--node-stroke': '#3f5243',
      '--node-text': '#e3ece5',
      '--edge': '#5f7364',
      '--edge-highlight': '#7bd88f',
      '--shadow': '0 6px 24px rgba(0,0,0,0.45)',
    },
  },
];

export const DEFAULT_THEME = 'midnight';

export function getTheme(id) {
  return THEMES.find((t) => t.id === id) || THEMES.find((t) => t.id === DEFAULT_THEME);
}

/** Applies a theme's tokens to the document root. */
export function applyTheme(id) {
  const theme = getTheme(id);
  const root = document.documentElement;
  for (const [key, value] of Object.entries(theme.tokens)) root.style.setProperty(key, value);
  root.setAttribute('data-theme', theme.id);
  root.style.colorScheme = theme.mode;
  return theme;
}

/**
 * Resolves the token map for a theme without touching the DOM — used when
 * generating a standalone HTML report, which must carry its own colors.
 */
export function themeTokens(id) {
  return getTheme(id).tokens;
}
