namespace Viewer3DWinForms;

partial class ThreeDViewerForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
            components.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        var resources = new System.ComponentModel.ComponentResourceManager(typeof(ThreeDViewerForm));
        components = new System.ComponentModel.Container();
        splitMain = new SplitContainer();
        splitLeft = new SplitContainer();
        topPanel = new Panel();
        btnSelectFolder = new Button();
        lblCurrentFolder = new Label();
        treeDirectories = new TreeView();
        listFiles = new ListView();
        panelZoomInfo = new Panel();
        lblZoomRatio = new Label();
        viewerHost = new System.Windows.Forms.Integration.ElementHost();
        statusStrip = new StatusStrip();
        lblStatus = new ToolStripStatusLabel();
        treeImageList = new ImageList(components);
        fileImageList = new ImageList(components);
        fileListContextMenu = new ContextMenuStrip(components);
        menuRenameFile = new ToolStripMenuItem();
        menuDeleteFile = new ToolStripMenuItem();
        panelLighting = new Panel();
        lblLightTitle = new Label();
        lblAmbientCap = new Label();
        trackAmbient = new TrackBar();
        lblAmbientVal = new Label();
        lblEmissiveCap = new Label();
        trackEmissive = new TrackBar();
        lblEmissiveVal = new Label();
        lblSunAltitudeCap = new Label();
        trackSunAltitude = new TrackBar();
        lblSunAltitudeVal = new Label();
        lblSunAzimuthCap = new Label();
        trackSunAzimuth = new TrackBar();
        lblSunAzimuthVal = new Label();
        lblFillBrightCap = new Label();
        trackFillBright = new TrackBar();
        lblFillBrightVal = new Label();
        panelViews = new Panel();
        btnViewFront = new Button();
        btnViewBack = new Button();
        btnViewLeft = new Button();
        btnViewRight = new Button();
        btnViewTop = new Button();
        btnViewBottom = new Button();
        btnViewHome = new Button();
        ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
        splitMain.Panel1.SuspendLayout();
        splitMain.Panel2.SuspendLayout();
        splitMain.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)splitLeft).BeginInit();
        splitLeft.Panel1.SuspendLayout();
        splitLeft.Panel2.SuspendLayout();
        splitLeft.SuspendLayout();
        topPanel.SuspendLayout();
        statusStrip.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)trackAmbient).BeginInit();
        ((System.ComponentModel.ISupportInitialize)trackEmissive).BeginInit();
        ((System.ComponentModel.ISupportInitialize)trackSunAltitude).BeginInit();
        ((System.ComponentModel.ISupportInitialize)trackSunAzimuth).BeginInit();
        ((System.ComponentModel.ISupportInitialize)trackFillBright).BeginInit();
        panelLighting.SuspendLayout();
        panelViews.SuspendLayout();
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1400, 850);
        Controls.Add(splitMain);
        Controls.Add(statusStrip);
        Name = "ThreeDViewerForm";
        Text = "3D Viewer (WinForms)";
        Load += ViewerForm_Load;
        splitMain.Dock = DockStyle.Fill;
        splitMain.FixedPanel = FixedPanel.Panel1;
        splitMain.Location = new Point(0, 0);
        splitMain.Name = "splitMain";
        splitMain.Panel1.Controls.Add(splitLeft);
        splitMain.Panel2.Controls.Add(panelViews);
        splitMain.Panel2.Controls.Add(panelLighting);
        splitMain.Panel2.Controls.Add(panelZoomInfo);
        splitMain.Panel2.Controls.Add(viewerHost);
        splitMain.Size = new Size(1400, 828);
        splitMain.SplitterDistance = 430;
        splitMain.TabIndex = 0;
        splitLeft.Dock = DockStyle.Fill;
        splitLeft.Location = new Point(0, 0);
        splitLeft.Name = "splitLeft";
        splitLeft.Orientation = Orientation.Horizontal;
        splitLeft.Panel1.Controls.Add(treeDirectories);
        splitLeft.Panel1.Controls.Add(topPanel);
        splitLeft.Panel2.Controls.Add(listFiles);
        splitLeft.Size = new Size(430, 828);
        splitLeft.SplitterDistance = 545;
        splitLeft.TabIndex = 0;
        topPanel.Controls.Add(btnSelectFolder);
        topPanel.Controls.Add(lblCurrentFolder);
        topPanel.Dock = DockStyle.Top;
        topPanel.Location = new Point(0, 0);
        topPanel.Name = "topPanel";
        topPanel.Size = new Size(430, 62);
        topPanel.TabIndex = 0;
        btnSelectFolder.Location = new Point(12, 17);
        btnSelectFolder.Name = "btnSelectFolder";
        btnSelectFolder.Size = new Size(123, 30);
        btnSelectFolder.TabIndex = 0;
        btnSelectFolder.Text = "폴더 선택...";
        btnSelectFolder.UseVisualStyleBackColor = true;
        btnSelectFolder.Click += btnSelectFolder_Click;
        lblCurrentFolder.AutoEllipsis = true;
        lblCurrentFolder.Location = new Point(148, 11);
        lblCurrentFolder.Name = "lblCurrentFolder";
        lblCurrentFolder.Size = new Size(270, 42);
        lblCurrentFolder.TabIndex = 1;
        lblCurrentFolder.Text = "루트 폴더를 선택하세요.";
        lblCurrentFolder.TextAlign = ContentAlignment.MiddleLeft;
        treeDirectories.Dock = DockStyle.Fill;
        treeDirectories.Location = new Point(0, 62);
        treeDirectories.Name = "treeDirectories";
        treeDirectories.Size = new Size(430, 483);
        treeDirectories.TabIndex = 1;
        treeDirectories.ImageList = treeImageList;
        treeDirectories.BeforeExpand += treeDirectories_BeforeExpand;
        treeDirectories.AfterSelect += treeDirectories_AfterSelect;
        listFiles.Dock = DockStyle.Fill;
        listFiles.FullRowSelect = true;
        listFiles.HideSelection = false;
        listFiles.Location = new Point(0, 0);
        listFiles.MultiSelect = false;
        listFiles.Name = "listFiles";
        listFiles.SmallImageList = fileImageList;
        listFiles.Size = new Size(430, 279);
        listFiles.TabIndex = 0;
        listFiles.UseCompatibleStateImageBehavior = false;
        listFiles.View = View.List;
        listFiles.SelectedIndexChanged += listFiles_SelectedIndexChanged;
        listFiles.KeyDown += listFiles_KeyDown;
        listFiles.ContextMenuStrip = fileListContextMenu;
        fileListContextMenu.Items.AddRange(new ToolStripItem[] { menuRenameFile, menuDeleteFile });
        fileListContextMenu.Name = "fileListContextMenu";
        fileListContextMenu.Opening += fileListContextMenu_Opening;
        menuRenameFile.Name = "menuRenameFile";
        menuRenameFile.Text = "이름 바꾸기...";
        menuRenameFile.Click += menuRenameFile_Click;
        menuDeleteFile.Name = "menuDeleteFile";
        menuDeleteFile.Text = "삭제";
        menuDeleteFile.Click += menuDeleteFile_Click;
        panelZoomInfo.BackColor = System.Drawing.Color.FromArgb(180, 32, 32, 32);
        panelZoomInfo.Controls.Add(lblZoomRatio);
        panelZoomInfo.Location = new Point(8, 8);
        panelZoomInfo.Name = "panelZoomInfo";
        panelZoomInfo.Size = new Size(108, 28);
        panelZoomInfo.TabIndex = 1;
        panelZoomInfo.Anchor = AnchorStyles.Top | AnchorStyles.Left;
        lblZoomRatio.ForeColor = System.Drawing.Color.White;
        lblZoomRatio.Location = new Point(8, 6);
        lblZoomRatio.Name = "lblZoomRatio";
        lblZoomRatio.Size = new Size(92, 16);
        lblZoomRatio.TabIndex = 0;
        lblZoomRatio.Text = "Zoom: 100%";
        viewerHost.Dock = DockStyle.Fill;
        viewerHost.Location = new Point(0, 0);
        viewerHost.Name = "viewerHost";
        viewerHost.Size = new Size(966, 828);
        viewerHost.TabIndex = 0;
        viewerHost.Text = "elementHost1";
        viewerHost.Child = null;
        statusStrip.ImageScalingSize = new Size(20, 20);
        statusStrip.Items.AddRange(new ToolStripItem[] { lblStatus });
        statusStrip.Location = new Point(0, 828);
        statusStrip.Name = "statusStrip";
        statusStrip.Size = new Size(1400, 22);
        statusStrip.TabIndex = 1;
        statusStrip.Text = "statusStrip1";
        lblStatus.Name = "lblStatus";
        lblStatus.Size = new Size(0, 16);
        // panelLighting
        panelLighting.BackColor = System.Drawing.Color.FromArgb(210, 32, 32, 32);
        panelLighting.Controls.Add(lblLightTitle);
        panelLighting.Controls.Add(lblSunAltitudeCap);
        panelLighting.Controls.Add(trackSunAltitude);
        panelLighting.Controls.Add(lblSunAltitudeVal);
        panelLighting.Controls.Add(lblSunAzimuthCap);
        panelLighting.Controls.Add(trackSunAzimuth);
        panelLighting.Controls.Add(lblSunAzimuthVal);
        panelLighting.Controls.Add(lblFillBrightCap);
        panelLighting.Controls.Add(trackFillBright);
        panelLighting.Controls.Add(lblFillBrightVal);
        panelLighting.Controls.Add(lblAmbientCap);
        panelLighting.Controls.Add(trackAmbient);
        panelLighting.Controls.Add(lblAmbientVal);
        panelLighting.Controls.Add(lblEmissiveCap);
        panelLighting.Controls.Add(trackEmissive);
        panelLighting.Controls.Add(lblEmissiveVal);
        panelLighting.AutoScroll = false;
        panelLighting.Location = new Point(710, 8);
        panelLighting.Name = "panelLighting";
        panelLighting.Size = new Size(248, 260);
        panelLighting.TabIndex = 2;
        panelLighting.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        lblLightTitle.AutoSize = false;
        lblLightTitle.ForeColor = System.Drawing.Color.White;
        lblLightTitle.Font = new Font("Segoe UI", 8.25f, FontStyle.Bold);
        lblLightTitle.Location = new Point(6, 4);
        lblLightTitle.Name = "lblLightTitle";
        lblLightTitle.Size = new Size(236, 14);
        lblLightTitle.Text = "조명 (환경광·태양/보조광)";
        lblSunAltitudeCap.AutoSize = false;
        lblSunAltitudeCap.ForeColor = System.Drawing.Color.White;
        lblSunAltitudeCap.Font = new Font("Segoe UI", 8f);
        lblSunAltitudeCap.Location = new Point(4, 22);
        lblSunAltitudeCap.Name = "lblSunAltitudeCap";
        lblSunAltitudeCap.Size = new Size(42, 14);
        lblSunAltitudeCap.Text = "태양고";
        trackSunAltitude.AutoSize = false;
        trackSunAltitude.Location = new Point(46, 14);
        trackSunAltitude.Maximum = 90;
        trackSunAltitude.Minimum = 0;
        trackSunAltitude.Name = "trackSunAltitude";
        trackSunAltitude.Size = new Size(162, 28);
        trackSunAltitude.TickStyle = TickStyle.None;
        trackSunAltitude.Value = 52;
        trackSunAltitude.SmallChange = 1;
        trackSunAltitude.LargeChange = 10;
        lblSunAltitudeVal.AutoSize = false;
        lblSunAltitudeVal.ForeColor = System.Drawing.Color.White;
        lblSunAltitudeVal.Font = new Font("Segoe UI", 8f);
        lblSunAltitudeVal.Location = new Point(212, 22);
        lblSunAltitudeVal.Name = "lblSunAltitudeVal";
        lblSunAltitudeVal.Size = new Size(30, 14);
        lblSunAltitudeVal.Text = "52";
        lblSunAltitudeVal.TextAlign = ContentAlignment.MiddleRight;
        lblSunAzimuthCap.AutoSize = false;
        lblSunAzimuthCap.ForeColor = System.Drawing.Color.White;
        lblSunAzimuthCap.Font = new Font("Segoe UI", 8f);
        lblSunAzimuthCap.Location = new Point(4, 50);
        lblSunAzimuthCap.Name = "lblSunAzimuthCap";
        lblSunAzimuthCap.Size = new Size(42, 14);
        lblSunAzimuthCap.Text = "태양방";
        trackSunAzimuth.AutoSize = false;
        trackSunAzimuth.Location = new Point(46, 42);
        trackSunAzimuth.Maximum = 359;
        trackSunAzimuth.Minimum = 0;
        trackSunAzimuth.Name = "trackSunAzimuth";
        trackSunAzimuth.Size = new Size(162, 28);
        trackSunAzimuth.TickStyle = TickStyle.None;
        trackSunAzimuth.Value = 38;
        trackSunAzimuth.SmallChange = 1;
        trackSunAzimuth.LargeChange = 15;
        lblSunAzimuthVal.AutoSize = false;
        lblSunAzimuthVal.ForeColor = System.Drawing.Color.White;
        lblSunAzimuthVal.Font = new Font("Segoe UI", 8f);
        lblSunAzimuthVal.Location = new Point(212, 50);
        lblSunAzimuthVal.Name = "lblSunAzimuthVal";
        lblSunAzimuthVal.Size = new Size(30, 14);
        lblSunAzimuthVal.Text = "38";
        lblSunAzimuthVal.TextAlign = ContentAlignment.MiddleRight;
        lblFillBrightCap.AutoSize = false;
        lblFillBrightCap.ForeColor = System.Drawing.Color.White;
        lblFillBrightCap.Font = new Font("Segoe UI", 8f);
        lblFillBrightCap.Location = new Point(4, 78);
        lblFillBrightCap.Name = "lblFillBrightCap";
        lblFillBrightCap.Size = new Size(42, 14);
        lblFillBrightCap.Text = "보조광";
        trackFillBright.AutoSize = false;
        trackFillBright.Location = new Point(46, 70);
        trackFillBright.Maximum = 100;
        trackFillBright.Minimum = 0;
        trackFillBright.Name = "trackFillBright";
        trackFillBright.Size = new Size(162, 28);
        trackFillBright.TickStyle = TickStyle.None;
        trackFillBright.Value = 100;
        trackFillBright.SmallChange = 2;
        trackFillBright.LargeChange = 10;
        lblFillBrightVal.AutoSize = false;
        lblFillBrightVal.ForeColor = System.Drawing.Color.White;
        lblFillBrightVal.Font = new Font("Segoe UI", 8f);
        lblFillBrightVal.Location = new Point(212, 78);
        lblFillBrightVal.Name = "lblFillBrightVal";
        lblFillBrightVal.Size = new Size(30, 14);
        lblFillBrightVal.Text = "100";
        lblFillBrightVal.TextAlign = ContentAlignment.MiddleRight;
        lblAmbientCap.AutoSize = false;
        lblAmbientCap.ForeColor = System.Drawing.Color.White;
        lblAmbientCap.Font = new Font("Segoe UI", 8f);
        lblAmbientCap.Location = new Point(4, 106);
        lblAmbientCap.Name = "lblAmbientCap";
        lblAmbientCap.Size = new Size(42, 14);
        lblAmbientCap.Text = "환경광";
        trackAmbient.AutoSize = false;
        trackAmbient.Location = new Point(46, 98);
        trackAmbient.Maximum = 255;
        trackAmbient.Minimum = 0;
        trackAmbient.Name = "trackAmbient";
        trackAmbient.Size = new Size(162, 28);
        trackAmbient.TabIndex = 1;
        trackAmbient.TickStyle = TickStyle.None;
        trackAmbient.Value = 110;
        trackAmbient.SmallChange = 5;
        trackAmbient.LargeChange = 20;
        trackAmbient.ValueChanged += trackAmbient_ValueChanged;
        lblAmbientVal.AutoSize = false;
        lblAmbientVal.ForeColor = System.Drawing.Color.White;
        lblAmbientVal.Font = new Font("Segoe UI", 8f);
        lblAmbientVal.Location = new Point(212, 106);
        lblAmbientVal.Name = "lblAmbientVal";
        lblAmbientVal.Size = new Size(30, 14);
        lblAmbientVal.Text = "110";
        lblAmbientVal.TextAlign = ContentAlignment.MiddleRight;
        lblEmissiveCap.AutoSize = false;
        lblEmissiveCap.ForeColor = System.Drawing.Color.White;
        lblEmissiveCap.Font = new Font("Segoe UI", 8f);
        lblEmissiveCap.Location = new Point(4, 134);
        lblEmissiveCap.Name = "lblEmissiveCap";
        lblEmissiveCap.Size = new Size(42, 14);
        lblEmissiveCap.Text = "발 광";
        trackEmissive.AutoSize = false;
        trackEmissive.Location = new Point(46, 126);
        trackEmissive.Maximum = 100;
        trackEmissive.Minimum = 0;
        trackEmissive.Name = "trackEmissive";
        trackEmissive.Size = new Size(162, 28);
        trackEmissive.TabIndex = 2;
        trackEmissive.TickStyle = TickStyle.None;
        trackEmissive.Value = 60;
        trackEmissive.SmallChange = 2;
        trackEmissive.LargeChange = 10;
        trackEmissive.ValueChanged += trackEmissive_ValueChanged;
        lblEmissiveVal.AutoSize = false;
        lblEmissiveVal.ForeColor = System.Drawing.Color.White;
        lblEmissiveVal.Font = new Font("Segoe UI", 8f);
        lblEmissiveVal.Location = new Point(212, 134);
        lblEmissiveVal.Name = "lblEmissiveVal";
        lblEmissiveVal.Size = new Size(30, 14);
        lblEmissiveVal.Text = "60";
        lblEmissiveVal.TextAlign = ContentAlignment.MiddleRight;
        // panelViews — 뷰 프리셋 버튼 (조명 패널 바로 아래)
        panelViews.BackColor = System.Drawing.Color.FromArgb(210, 32, 32, 32);
        panelViews.Controls.Add(btnViewFront);
        panelViews.Controls.Add(btnViewBack);
        panelViews.Controls.Add(btnViewLeft);
        panelViews.Controls.Add(btnViewRight);
        panelViews.Controls.Add(btnViewTop);
        panelViews.Controls.Add(btnViewBottom);
        panelViews.Controls.Add(btnViewHome);
        panelViews.Location = new Point(710, 274);
        panelViews.Name = "panelViews";
        panelViews.Size = new Size(248, 60);
        panelViews.TabIndex = 3;
        panelViews.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        ConfigureViewButton(btnViewFront,  "정면",   new Point(4,   4), new Size(58, 24), 0, btnViewFront_Click);
        ConfigureViewButton(btnViewBack,   "후면",   new Point(64,  4), new Size(58, 24), 1, btnViewBack_Click);
        ConfigureViewButton(btnViewLeft,   "좌측",   new Point(124, 4), new Size(58, 24), 2, btnViewLeft_Click);
        ConfigureViewButton(btnViewRight,  "우측",   new Point(184, 4), new Size(58, 24), 3, btnViewRight_Click);
        ConfigureViewButton(btnViewTop,    "상단",   new Point(4,  32), new Size(58, 24), 4, btnViewTop_Click);
        ConfigureViewButton(btnViewBottom, "하단",   new Point(64, 32), new Size(58, 24), 5, btnViewBottom_Click);
        ConfigureViewButton(btnViewHome,   "↺ 홈",   new Point(124,32), new Size(120,24), 6, btnViewHome_Click);
        splitMain.Panel1.ResumeLayout(false);
        splitMain.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
        splitMain.ResumeLayout(false);
        splitLeft.Panel1.ResumeLayout(false);
        splitLeft.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitLeft).EndInit();
        splitLeft.ResumeLayout(false);
        topPanel.ResumeLayout(false);
        panelLighting.ResumeLayout(false);
        panelViews.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)trackAmbient).EndInit();
        ((System.ComponentModel.ISupportInitialize)trackEmissive).EndInit();
        ((System.ComponentModel.ISupportInitialize)trackSunAltitude).EndInit();
        ((System.ComponentModel.ISupportInitialize)trackSunAzimuth).EndInit();
        ((System.ComponentModel.ISupportInitialize)trackFillBright).EndInit();
        statusStrip.ResumeLayout(false);
        statusStrip.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
        resources.ApplyResources(this, "$this");
    }

    private static void ConfigureViewButton(Button btn, string text, Point location, Size size, int tabIndex, EventHandler handler)
    {
        btn.BackColor = System.Drawing.Color.FromArgb(55, 55, 55);
        btn.FlatStyle = FlatStyle.Flat;
        btn.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(80, 80, 80);
        btn.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(75, 75, 75);
        btn.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(100, 100, 100);
        btn.ForeColor = System.Drawing.Color.White;
        btn.Font = new Font("Segoe UI", 8f);
        btn.Location = location;
        btn.Size = size;
        btn.TabIndex = tabIndex;
        btn.Text = text;
        btn.UseVisualStyleBackColor = false;
        btn.Click += handler;
    }

    #endregion

    private SplitContainer splitMain;
    private SplitContainer splitLeft;
    private Panel topPanel;
    private Button btnSelectFolder;
    private Label lblCurrentFolder;
    private TreeView treeDirectories;
    private ListView listFiles;
    private Panel panelZoomInfo;
    private Label lblZoomRatio;
    private System.Windows.Forms.Integration.ElementHost viewerHost;
    private StatusStrip statusStrip;
    private ToolStripStatusLabel lblStatus;
    private ImageList treeImageList;
    private ImageList fileImageList;
    private ContextMenuStrip fileListContextMenu;
    private ToolStripMenuItem menuRenameFile;
    private ToolStripMenuItem menuDeleteFile;
    private Panel panelLighting;
    private Label lblLightTitle;
    private Label lblAmbientCap;
    private TrackBar trackAmbient;
    private Label lblAmbientVal;
    private Label lblEmissiveCap;
    private TrackBar trackEmissive;
    private Label lblEmissiveVal;
    private Label lblSunAltitudeCap;
    private TrackBar trackSunAltitude;
    private Label lblSunAltitudeVal;
    private Label lblSunAzimuthCap;
    private TrackBar trackSunAzimuth;
    private Label lblSunAzimuthVal;
    private Label lblFillBrightCap;
    private TrackBar trackFillBright;
    private Label lblFillBrightVal;
    private Panel panelViews;
    private Button btnViewFront;
    private Button btnViewBack;
    private Button btnViewLeft;
    private Button btnViewRight;
    private Button btnViewTop;
    private Button btnViewBottom;
    private Button btnViewHome;
}
