namespace Viewer3DWinForms;

partial class ThreeDViewerForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
            components.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        var resources = new System.ComponentModel.ComponentResourceManager(typeof(ThreeDViewerForm));
        components = new System.ComponentModel.Container();
        splitMain = new SplitContainer();
        splitLeft = new SplitContainer();
        topPanel = new Panel();
        btnSelectFolder = new Button();
        lblCurrentFolder = new Label();
        treeDirectories = new TreeView();
        listFiles = new ListView();
        panelZoomInfo = new Panel();
        lblZoomRatio = new Label();
        viewerHost = new System.Windows.Forms.Integration.ElementHost();
        statusStrip = new StatusStrip();
        lblStatus = new ToolStripStatusLabel();
        treeImageList = new ImageList(components);
        fileImageList = new ImageList(components);
        fileListContextMenu = new ContextMenuStrip(components);
        menuRenameFile = new ToolStripMenuItem();
        menuDeleteFile = new ToolStripMenuItem();
        panelLighting = new Panel();
        lblLightTitle = new Label();
        lblAmbientCap = new Label();
        trackAmbient = new TrackBar();
        lblAmbientVal = new Label();
        lblEmissiveCap = new Label();
        trackEmissive = new TrackBar();
        lblEmissiveVal = new Label();
        ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
        splitMain.Panel1.SuspendLayout();
        splitMain.Panel2.SuspendLayout();
        splitMain.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)splitLeft).BeginInit();
        splitLeft.Panel1.SuspendLayout();
        splitLeft.Panel2.SuspendLayout();
        splitLeft.SuspendLayout();
        topPanel.SuspendLayout();
        statusStrip.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)trackAmbient).BeginInit();
        ((System.ComponentModel.ISupportInitialize)trackEmissive).BeginInit();
        panelLighting.SuspendLayout();
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1400, 850);
        Controls.Add(splitMain);
        Controls.Add(statusStrip);
        Name = "ThreeDViewerForm";
        Text = "3D Viewer (WinForms)";
        Load += ViewerForm_Load;
        splitMain.Dock = DockStyle.Fill;
        splitMain.FixedPanel = FixedPanel.Panel1;
        splitMain.Location = new Point(0, 0);
        splitMain.Name = "splitMain";
        splitMain.Panel1.Controls.Add(splitLeft);
        splitMain.Panel2.Controls.Add(panelLighting);
        splitMain.Panel2.Controls.Add(panelZoomInfo);
        splitMain.Panel2.Controls.Add(viewerHost);
        splitMain.Size = new Size(1400, 828);
        splitMain.SplitterDistance = 430;
        splitMain.TabIndex = 0;
        splitLeft.Dock = DockStyle.Fill;
        splitLeft.Location = new Point(0, 0);
        splitLeft.Name = "splitLeft";
        splitLeft.Orientation = Orientation.Horizontal;
        splitLeft.Panel1.Controls.Add(treeDirectories);
        splitLeft.Panel1.Controls.Add(topPanel);
        splitLeft.Panel2.Controls.Add(listFiles);
        splitLeft.Size = new Size(430, 828);
        splitLeft.SplitterDistance = 545;
        splitLeft.TabIndex = 0;
        topPanel.Controls.Add(btnSelectFolder);
        topPanel.Controls.Add(lblCurrentFolder);
        topPanel.Dock = DockStyle.Top;
        topPanel.Location = new Point(0, 0);
        topPanel.Name = "topPanel";
        topPanel.Size = new Size(430, 62);
        topPanel.TabIndex = 0;
        btnSelectFolder.Location = new Point(12, 17);
        btnSelectFolder.Name = "btnSelectFolder";
        btnSelectFolder.Size = new Size(123, 30);
        btnSelectFolder.TabIndex = 0;
        btnSelectFolder.Text = "폴더 선택...";
        btnSelectFolder.UseVisualStyleBackColor = true;
        btnSelectFolder.Click += btnSelectFolder_Click;
        lblCurrentFolder.AutoEllipsis = true;
        lblCurrentFolder.Location = new Point(148, 11);
        lblCurrentFolder.Name = "lblCurrentFolder";
        lblCurrentFolder.Size = new Size(270, 42);
        lblCurrentFolder.TabIndex = 1;
        lblCurrentFolder.Text = "루트 폴더를 선택하세요.";
        lblCurrentFolder.TextAlign = ContentAlignment.MiddleLeft;
        treeDirectories.Dock = DockStyle.Fill;
        treeDirectories.Location = new Point(0, 62);
        treeDirectories.Name = "treeDirectories";
        treeDirectories.Size = new Size(430, 483);
        treeDirectories.TabIndex = 1;
        treeDirectories.ImageList = treeImageList;
        treeDirectories.BeforeExpand += treeDirectories_BeforeExpand;
        treeDirectories.AfterSelect += treeDirectories_AfterSelect;
        listFiles.Dock = DockStyle.Fill;
        listFiles.FullRowSelect = true;
        listFiles.HideSelection = false;
        listFiles.Location = new Point(0, 0);
        listFiles.MultiSelect = false;
        listFiles.Name = "listFiles";
        listFiles.SmallImageList = fileImageList;
        listFiles.Size = new Size(430, 279);
        listFiles.TabIndex = 0;
        listFiles.UseCompatibleStateImageBehavior = false;
        listFiles.View = View.List;
        listFiles.SelectedIndexChanged += listFiles_SelectedIndexChanged;
        listFiles.KeyDown += listFiles_KeyDown;
        listFiles.ContextMenuStrip = fileListContextMenu;
        fileListContextMenu.Items.AddRange(new ToolStripItem[] { menuRenameFile, menuDeleteFile });
        fileListContextMenu.Name = "fileListContextMenu";
        fileListContextMenu.Opening += fileListContextMenu_Opening;
        menuRenameFile.Name = "menuRenameFile";
        menuRenameFile.Text = "이름 바꾸기...";
        menuRenameFile.Click += menuRenameFile_Click;
        menuDeleteFile.Name = "menuDeleteFile";
        menuDeleteFile.Text = "삭제";
        menuDeleteFile.Click += menuDeleteFile_Click;
        panelZoomInfo.BackColor = System.Drawing.Color.FromArgb(180, 32, 32, 32);
        panelZoomInfo.Controls.Add(lblZoomRatio);
        panelZoomInfo.Location = new Point(8, 8);
        panelZoomInfo.Name = "panelZoomInfo";
        panelZoomInfo.Size = new Size(108, 28);
        panelZoomInfo.TabIndex = 1;
        panelZoomInfo.Anchor = AnchorStyles.Top | AnchorStyles.Left;
        lblZoomRatio.ForeColor = System.Drawing.Color.White;
        lblZoomRatio.Location = new Point(8, 6);
        lblZoomRatio.Name = "lblZoomRatio";
        lblZoomRatio.Size = new Size(92, 16);
        lblZoomRatio.TabIndex = 0;
        lblZoomRatio.Text = "Zoom: 100%";
        viewerHost.Dock = DockStyle.Fill;
        viewerHost.Location = new Point(0, 0);
        viewerHost.Name = "viewerHost";
        viewerHost.Size = new Size(966, 828);
        viewerHost.TabIndex = 0;
        viewerHost.Text = "elementHost1";
        viewerHost.Child = null;
        statusStrip.ImageScalingSize = new Size(20, 20);
        statusStrip.Items.AddRange(new ToolStripItem[] { lblStatus });
        statusStrip.Location = new Point(0, 828);
        statusStrip.Name = "statusStrip";
        statusStrip.Size = new Size(1400, 22);
        statusStrip.TabIndex = 1;
        statusStrip.Text = "statusStrip1";
        lblStatus.Name = "lblStatus";
        lblStatus.Size = new Size(0, 16);
        // panelLighting
        panelLighting.BackColor = System.Drawing.Color.FromArgb(210, 32, 32, 32);
        panelLighting.Controls.Add(lblLightTitle);
        panelLighting.Controls.Add(lblAmbientCap);
        panelLighting.Controls.Add(trackAmbient);
        panelLighting.Controls.Add(lblAmbientVal);
        panelLighting.Controls.Add(lblEmissiveCap);
        panelLighting.Controls.Add(trackEmissive);
        panelLighting.Controls.Add(lblEmissiveVal);
        panelLighting.Location = new Point(710, 8);
        panelLighting.Name = "panelLighting";
        panelLighting.Size = new Size(248, 78);
        panelLighting.TabIndex = 2;
        panelLighting.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        lblLightTitle.AutoSize = false;
        lblLightTitle.ForeColor = System.Drawing.Color.White;
        lblLightTitle.Font = new Font("Segoe UI", 8.25f, FontStyle.Bold);
        lblLightTitle.Location = new Point(6, 4);
        lblLightTitle.Name = "lblLightTitle";
        lblLightTitle.Size = new Size(236, 14);
        lblLightTitle.Text = "조명 설정";
        lblAmbientCap.AutoSize = false;
        lblAmbientCap.ForeColor = System.Drawing.Color.White;
        lblAmbientCap.Font = new Font("Segoe UI", 8f);
        lblAmbientCap.Location = new Point(4, 24);
        lblAmbientCap.Name = "lblAmbientCap";
        lblAmbientCap.Size = new Size(42, 14);
        lblAmbientCap.Text = "환경광";
        trackAmbient.AutoSize = false;
        trackAmbient.Location = new Point(46, 16);
        trackAmbient.Maximum = 255;
        trackAmbient.Minimum = 0;
        trackAmbient.Name = "trackAmbient";
        trackAmbient.Size = new Size(162, 28);
        trackAmbient.TabIndex = 1;
        trackAmbient.TickStyle = TickStyle.None;
        trackAmbient.Value = 160;
        trackAmbient.SmallChange = 5;
        trackAmbient.LargeChange = 20;
        trackAmbient.ValueChanged += trackAmbient_ValueChanged;
        lblAmbientVal.AutoSize = false;
        lblAmbientVal.ForeColor = System.Drawing.Color.White;
        lblAmbientVal.Font = new Font("Segoe UI", 8f);
        lblAmbientVal.Location = new Point(212, 24);
        lblAmbientVal.Name = "lblAmbientVal";
        lblAmbientVal.Size = new Size(30, 14);
        lblAmbientVal.Text = "160";
        lblAmbientVal.TextAlign = ContentAlignment.MiddleRight;
        lblEmissiveCap.AutoSize = false;
        lblEmissiveCap.ForeColor = System.Drawing.Color.White;
        lblEmissiveCap.Font = new Font("Segoe UI", 8f);
        lblEmissiveCap.Location = new Point(4, 52);
        lblEmissiveCap.Name = "lblEmissiveCap";
        lblEmissiveCap.Size = new Size(42, 14);
        lblEmissiveCap.Text = "발 광";
        trackEmissive.AutoSize = false;
        trackEmissive.Location = new Point(46, 44);
        trackEmissive.Maximum = 100;
        trackEmissive.Minimum = 0;
        trackEmissive.Name = "trackEmissive";
        trackEmissive.Size = new Size(162, 28);
        trackEmissive.TabIndex = 2;
        trackEmissive.TickStyle = TickStyle.None;
        trackEmissive.Value = 60;
        trackEmissive.SmallChange = 2;
        trackEmissive.LargeChange = 10;
        trackEmissive.ValueChanged += trackEmissive_ValueChanged;
        lblEmissiveVal.AutoSize = false;
        lblEmissiveVal.ForeColor = System.Drawing.Color.White;
        lblEmissiveVal.Font = new Font("Segoe UI", 8f);
        lblEmissiveVal.Location = new Point(212, 52);
        lblEmissiveVal.Name = "lblEmissiveVal";
        lblEmissiveVal.Size = new Size(30, 14);
        lblEmissiveVal.Text = "60";
        lblEmissiveVal.TextAlign = ContentAlignment.MiddleRight;
        splitMain.Panel1.ResumeLayout(false);
        splitMain.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
        splitMain.ResumeLayout(false);
        splitLeft.Panel1.ResumeLayout(false);
        splitLeft.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitLeft).EndInit();
        splitLeft.ResumeLayout(false);
        topPanel.ResumeLayout(false);
        panelLighting.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)trackAmbient).EndInit();
        ((System.ComponentModel.ISupportInitialize)trackEmissive).EndInit();
        statusStrip.ResumeLayout(false);
        statusStrip.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
        resources.ApplyResources(this, "$this");
    }

    #endregion

    private SplitContainer splitMain;
    private SplitContainer splitLeft;
    private Panel topPanel;
    private Button btnSelectFolder;
    private Label lblCurrentFolder;
    private TreeView treeDirectories;
    private ListView listFiles;
    private Panel panelZoomInfo;
    private Label lblZoomRatio;
    private System.Windows.Forms.Integration.ElementHost viewerHost;
    private StatusStrip statusStrip;
    private ToolStripStatusLabel lblStatus;
    private ImageList treeImageList;
    private ImageList fileImageList;
    private ContextMenuStrip fileListContextMenu;
    private ToolStripMenuItem menuRenameFile;
    private ToolStripMenuItem menuDeleteFile;
    private Panel panelLighting;
    private Label lblLightTitle;
    private Label lblAmbientCap;
    private TrackBar trackAmbient;
    private Label lblAmbientVal;
    private Label lblEmissiveCap;
    private TrackBar trackEmissive;
    private Label lblEmissiveVal;
}
