'use strict';

const fs = require('fs');
const path = require('path');
const { BrowserWindow, session, app } = require('electron');

const PARTITION = 'persist:youtube-auth';
const COOKIE_DOMAINS = ['.youtube.com', 'youtube.com', '.google.com', 'google.com'];

function getYoutubeSession() {
  return session.fromPartition(PARTITION);
}

async function collectYoutubeCookies() {
  const ses = getYoutubeSession();
  const seen = new Set();
  const cookies = [];
  for (const domain of COOKIE_DOMAINS) {
    try {
      const list = await ses.cookies.get({ domain });
      for (const c of list) {
        const key = `${c.domain}|${c.name}|${c.path || '/'}`;
        if (seen.has(key)) continue;
        seen.add(key);
        cookies.push(c);
      }
    } catch {
      /* ignore domain */
    }
  }
  return cookies;
}

function hasUsefulYoutubeAuth(cookies) {
  const names = new Set(cookies.map((c) => c.name));
  return (
    names.has('LOGIN_INFO') ||
    names.has('SAPISID') ||
    names.has('__Secure-1PSID') ||
    names.has('__Secure-3PSID') ||
    names.has('SID')
  );
}

function toNetscapeCookies(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by MyVideoPlayer'];
  for (const c of cookies) {
    const domain = c.domain || '';
    const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const cookiePath = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires =
      c.expirationDate && Number.isFinite(c.expirationDate)
        ? Math.floor(c.expirationDate)
        : 0;
    const name = c.name || '';
    const value = c.value || '';
    lines.push(
      [domain, includeSub, cookiePath, secure, String(expires), name, value].join('\t')
    );
  }
  return `${lines.join('\n')}\n`;
}

async function writeYoutubeCookiesFile() {
  const cookies = await collectYoutubeCookies();
  if (!cookies.length) return null;
  const dir = path.join(app.getPath('temp'), 'my-video-player-yt');
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, 'cookies.txt');
  fs.writeFileSync(filePath, toNetscapeCookies(cookies), 'utf8');
  return {
    path: filePath,
    count: cookies.length,
    authenticated: hasUsefulYoutubeAuth(cookies)
  };
}

/**
 * Open a modal sign-in window bound to the YouTube cookie partition.
 * Resolves when the user closes the window (after signing in).
 */
function promptYoutubeSignIn(parentWindow) {
  return new Promise((resolve) => {
    const win = new BrowserWindow({
      parent: parentWindow || undefined,
      modal: Boolean(parentWindow),
      width: 980,
      height: 740,
      show: true,
      autoHideMenuBar: true,
      title: 'Sign in to YouTube',
      webPreferences: {
        partition: PARTITION,
        nodeIntegration: false,
        contextIsolation: true,
        sandbox: true
      }
    });

    let settled = false;
    const finish = async () => {
      if (settled) return;
      settled = true;
      try {
        if (!win.isDestroyed()) win.close();
      } catch {
        /* ignore */
      }
      const exported = await writeYoutubeCookiesFile();
      resolve(exported);
    };

    win.on('closed', () => {
      void finish();
    });

    win.webContents.setWindowOpenHandler(() => ({ action: 'allow' }));
    win.loadURL('https://www.youtube.com/').catch(() => {
      /* user can still navigate */
    });

    // Auto-close shortly after useful auth cookies appear.
    const timer = setInterval(async () => {
      if (settled || win.isDestroyed()) {
        clearInterval(timer);
        return;
      }
      try {
        const cookies = await collectYoutubeCookies();
        if (hasUsefulYoutubeAuth(cookies)) {
          clearInterval(timer);
          // Give the session a moment to settle extra cookies.
          setTimeout(() => void finish(), 800);
        }
      } catch {
        /* ignore */
      }
    }, 1200);

    win.on('closed', () => clearInterval(timer));
  });
}

async function ensureYoutubeCookies({ parentWindow = null, forcePrompt = false } = {}) {
  if (!forcePrompt) {
    const existing = await writeYoutubeCookiesFile();
    if (existing?.authenticated) return existing;
  }
  return promptYoutubeSignIn(parentWindow);
}

module.exports = {
  PARTITION,
  getYoutubeSession,
  collectYoutubeCookies,
  hasUsefulYoutubeAuth,
  writeYoutubeCookiesFile,
  promptYoutubeSignIn,
  ensureYoutubeCookies
};
