namespace MyGitWinV10.App.Services;

/// <summary>
/// Korean/English string table for the application UI. Defaults to Korean; switch via
/// <see cref="Language"/> or File → Preferences.
/// </summary>
public static class Localization
{
    public static event Action? LanguageChanged;

    public static AppLanguage Language { get; private set; } = AppLanguage.Korean;

    public static void SetLanguage(AppLanguage language)
    {
        if (Language == language)
        {
            return;
        }

        Language = language;
        LanguageChanged?.Invoke();
    }

    public static string T(string key) =>
        Strings.TryGetValue(key, out var pair) ? (Language == AppLanguage.Korean ? pair.Ko : pair.En) : key;

    public static string Tf(string key, params object[] args) =>
        string.Format(T(key), args);

    private static readonly Dictionary<string, (string Ko, string En)> Strings = new()
    {
        ["Menu.File"] = ("파일", "File"),
        ["Menu.File.Open"] = ("열기...", "&Open..."),
        ["Menu.File.Open.Tip"] = ("로컬 Git 저장소 폴더를 엽니다", "Open a local Git repository folder"),
        ["Menu.File.Clone"] = ("클론...", "&Clone..."),
        ["Menu.File.Clone.Tip"] = ("원격 저장소를 로컬 폴더로 클론합니다", "Clone a remote repository to a local folder"),
        ["Menu.File.BrowseRemote"] = ("원격 저장소 둘러보기...", "&Browse Remote..."),
        ["Menu.File.BrowseRemote.Tip"] = ("로컬에 저장하지 않고 원격 커밋 기록을 둘러봅니다", "Browse remote commit history without saving a local copy"),
        ["Menu.File.Preferences"] = ("환경설정...", "&Preferences..."),
        ["Menu.File.Preferences.Tip"] = ("외부 Diff 도구와 언어를 설정합니다", "Configure the external diff tool and language"),
        ["Menu.File.Exit"] = ("끝내기", "E&xit"),
        ["Menu.File.Exit.Tip"] = ("애플리케이션을 닫습니다", "Close the application"),

        ["Menu.Repository"] = ("저장소", "Repository"),
        ["Menu.Repository.RefreshTree"] = ("트리 새로고침", "Refresh &Tree"),
        ["Menu.Repository.ExportWord"] = ("Word로 내보내기", "Export to &Word"),
        ["Menu.Repository.ExportMarkdown"] = ("Markdown으로 내보내기", "Export to &Markdown"),
        ["Menu.Repository.ExportPdf"] = ("PDF로 내보내기", "Export to &PDF"),

        ["Menu.History"] = ("기록", "History"),
        ["Menu.History.RefreshGraph"] = ("그래프 새로고침", "Refresh &Graph"),
        ["Menu.History.CopySha"] = ("SHA 복사", "Copy &SHA"),
        ["Menu.History.CopyMessage"] = ("메시지 복사", "Copy &Message"),

        ["Menu.Diff"] = ("Diff", "Diff"),
        ["Menu.Diff.CopyPath"] = ("경로 복사", "Copy &Path"),
        ["Menu.Diff.WordWrap"] = ("자동 줄바꿈", "Word &Wrap"),
        ["Menu.Diff.CopyDiff"] = ("Diff 복사", "Copy &Diff"),

        ["Menu.Help"] = ("도움말", "Help"),
        ["Menu.Help.About"] = ("정보", "&About"),

        ["Toolbar.Open.Tip"] = ("로컬 Git 저장소 폴더를 엽니다", "Open a local Git repository folder"),
        ["Toolbar.Clone.Tip"] = ("원격 저장소를 로컬 폴더로 클론합니다", "Clone a remote repository to a local folder"),
        ["Toolbar.BrowseRemote.Tip"] = ("로컬에 저장하지 않고 원격 커밋 기록을 둘러봅니다", "Browse remote commit history without saving a local copy"),
        ["Toolbar.RefreshTree.Tip"] = ("브랜치, 태그, 릴리스를 새로고침합니다", "Reload branches, tags, and releases"),
        ["Toolbar.ExportSummary.Tip"] = ("저장소 요약을 PDF, Word, Markdown으로 내보냅니다", "Export repository summary as PDF, Word, or Markdown"),
        ["Toolbar.RefreshGraph.Tip"] = ("커밋 기록 그래프를 새로고침합니다", "Reload the commit history graph"),
        ["Toolbar.CopySha.Tip"] = ("선택한 커밋의 전체 해시를 클립보드에 복사합니다", "Copy the selected commit's full hash to the clipboard"),
        ["Toolbar.CopyMessage.Tip"] = ("선택한 커밋 메시지를 클립보드에 복사합니다", "Copy the selected commit message to the clipboard"),
        ["Toolbar.CopyFilePath.Tip"] = ("선택한 파일 경로를 클립보드에 복사합니다", "Copy the selected file path to the clipboard"),
        ["Toolbar.WordWrap.Tip"] = ("Diff 보기의 자동 줄바꿈을 켜고 끕니다", "Toggle word wrap for the diff view"),
        ["Toolbar.CopyDiff.Tip"] = ("화면에 보이는 Diff 텍스트를 복사합니다", "Copy the visible diff text to the clipboard"),
        ["Toolbar.Info.Tip"] = ("애플리케이션 정보를 표시합니다", "Show application information"),

        ["Section.Repo.Title"] = ("저장소", "Repository"),
        ["Section.Repo.Tip"] = ("브랜치, 태그, 릴리스가 포함된 로컬 저장소 트리입니다.", "Local repository tree with branches, tags, and releases."),
        ["Section.RepoFiles.Title"] = ("파일", "Files"),
        ["Section.RepoFiles.Tip"] = ("저장소 폴더와 파일입니다. 아이콘이 Git 상태를 표시하며, 노드에 마우스를 올리면 스테이지/작업 트리 세부정보를 볼 수 있습니다.", "Repository folders and files. Icons show Git status; hover a node for staged and work tree details."),
        ["Section.Graph.Title"] = ("커밋 기록", "Commit History"),
        ["Section.Graph.Tip"] = ("브랜치 그래프, 메시지, 메타데이터가 포함된 커밋 로그입니다.", "Commit log with branch graph, messages, and metadata."),
        ["Section.Files.Title"] = ("커밋 상세", "Commit Details"),
        ["Section.Files.Tip"] = ("선택한 커밋의 작성자, 메시지, 변경된 파일입니다.", "Author, message, and files changed in the selected commit."),
        ["Section.Diff.Title"] = ("Diff", "Diff"),
        ["Section.Diff.Tip"] = ("선택한 변경 파일의 통합 Diff입니다.", "Unified diff for the selected changed file."),
        ["Section.ChangedFiles.Title"] = ("변경된 파일", "Changed Files"),
        ["Section.ChangedFiles.Tip"] = ("선택한 커밋에서 수정된 파일 목록입니다.", "List of files modified in the selected commit."),

        ["Menu.Diff.ContextCopy"] = ("복사", "Copy"),
        ["Menu.Diff.ContextWordWrap"] = ("자동 줄바꿈", "Word Wrap"),

        ["Menu.CommitGraph.CopySha"] = ("SHA 복사", "Copy SHA"),
        ["Menu.CommitGraph.CopyMessage"] = ("메시지 복사", "Copy Message"),
        ["Menu.CommitGraph.ExportToFolder"] = ("폴더로 내보내기...", "Export to Folder..."),

        ["Column.RepoFiles.Name"] = ("디렉토리/파일", "Directory/File"),
        ["Column.RepoFiles.Name.Tip"] = ("저장소 트리 내 위치를 들여쓰기로 표시한 파일 또는 디렉토리 이름입니다.", "Name of the file or directory, indented to show its place in the repository tree."),
        ["Column.RepoFiles.Status"] = ("상태", "Status"),
        ["Column.RepoFiles.Status.Tip"] = ("Git 상태 배지입니다 (C=변경, U=미추적, P=미Push, D=삭제, R=이름변경, X=무시, !=충돌).", "Git status badge (C=Changed, U=Untracked, P=Not pushed, D=Deleted, R=Renamed, X=Ignored, !=Conflicted)."),

        ["Column.ChangedFiles.Path"] = ("경로", "Path"),
        ["Column.ChangedFiles.Path.Tip"] = ("저장소 내 변경된 파일의 상대 경로입니다.", "Relative path of the changed file in the repository."),
        ["Column.ChangedFiles.Status"] = ("상태", "Status"),
        ["Column.ChangedFiles.Status.Tip"] = ("변경 종류입니다 (추가, 수정, 삭제, 이름변경 등).", "Kind of change (Added, Modified, Deleted, Renamed, etc.)."),

        ["Menu.RepoFiles.AddToGitIgnore"] = (".gitignore에 추가", "Add to .gitignore"),
        ["Menu.RepoFiles.AddToGitIgnore.Tip"] = ("선택한 경로를 .gitignore에 추가합니다", "Append the selected path to .gitignore"),
        ["Menu.RepoFiles.RemoveFromGitIgnore"] = (".gitignore에서 제거", "Remove from .gitignore"),
        ["Menu.RepoFiles.RemoveFromGitIgnore.Tip"] = ("선택한 경로를 .gitignore에서 제거합니다", "Remove the selected path from .gitignore"),

        ["Menu.ChangedFiles.OpenExternal"] = ("외부 뷰어로 보기", "Open in External Viewer"),
        ["Menu.ChangedFiles.OpenExternal.Tip"] = ("환경설정에 지정한 외부 Diff 도구로 선택한 파일을 엽니다.", "Open the selected file in the external diff tool configured in Preferences."),
        ["Menu.ChangedFiles.ExternalNotConfigured"] = ("설정안됨", "not configured"),
        ["Menu.ChangedFiles.CopyPath"] = ("경로 복사", "Copy Path"),
        ["Menu.ChangedFiles.CopyPath.Tip"] = ("선택한 파일 경로를 클립보드에 복사합니다.", "Copy the selected file path to the clipboard."),

        ["Column.Graph.Graph"] = ("그래프", "Graph"),
        ["Column.Graph.Graph.Tip"] = ("커밋이 레인 사이에서 어떻게 연결되는지 보여주는 브랜치/머지 그래프입니다.", "Branch and merge graph showing how commits connect across lanes."),
        ["Column.Graph.Message"] = ("메시지", "Message"),
        ["Column.Graph.Message.Tip"] = ("커밋 메시지의 첫 줄 요약입니다.", "Short summary of the commit (first line of the commit message)."),
        ["Column.Graph.Sha"] = ("SHA", "SHA"),
        ["Column.Graph.Sha.Tip"] = ("이 리비전을 고유하게 식별하는 축약된 커밋 해시입니다.", "Abbreviated commit hash that uniquely identifies this revision."),
        ["Column.Graph.Author"] = ("작성자", "Author"),
        ["Column.Graph.Author.Tip"] = ("커밋을 작성한 사람입니다.", "Person who authored the commit."),
        ["Column.Graph.Date"] = ("날짜", "Date"),
        ["Column.Graph.Date.Tip"] = ("커밋이 작성된 날짜입니다.", "Date when the commit was authored."),

        ["Preferences.Title"] = ("환경설정", "Preferences"),
        ["Preferences.Diff.Group"] = ("외부 Diff 도구", "External Diff Tool"),
        ["Preferences.Diff.Path"] = ("도구 경로", "Tool Path"),
        ["Preferences.Diff.Browse"] = ("찾아보기...", "Browse..."),
        ["Preferences.Diff.Arguments"] = ("인수", "Arguments"),
        ["Preferences.Diff.Hint"] = ("{left}와 {right}는 비교할 두 임시 파일 경로로 대체됩니다.", "{left} and {right} are replaced with the two temp file paths to compare."),
        ["Preferences.Language.Group"] = ("언어", "Language"),
        ["Preferences.Language.Korean"] = ("한국어", "Korean"),
        ["Preferences.Language.English"] = ("영어", "English"),
        ["Preferences.OK"] = ("확인", "OK"),
        ["Preferences.Cancel"] = ("취소", "Cancel"),

        ["Common.OK"] = ("확인", "OK"),
        ["Common.Cancel"] = ("취소", "Cancel"),
        ["Common.Close"] = ("닫기", "Close"),
        ["Common.Delete"] = ("삭제", "Delete"),
        ["Common.Ready"] = ("준비", "Ready"),

        ["Menu.Git"] = ("Git", "Git"),
        ["Menu.Git.Add"] = ("Git Add", "Git &Add"),
        ["Menu.Git.Reset"] = ("Git Reset (Unstage)", "Git Reset (&Unstage)"),
        ["Menu.Git.Discard"] = ("Git Discard Changes", "Git &Discard Changes"),
        ["Menu.Git.Commit"] = ("Git Commit...", "Git &Commit..."),
        ["Menu.Git.Fetch"] = ("Git Fetch", "Git Fetc&h"),
        ["Menu.Git.Pull"] = ("Git Pull", "Git P&ull"),
        ["Menu.Git.Push"] = ("Git Push", "Git P&ush"),
        ["Menu.Git.Stash"] = ("Git Stash", "Git Stas&h"),
        ["Menu.Git.StashPop"] = ("Git Stash Pop", "Git Stash &Pop"),
        ["Menu.Git.Status"] = ("Git Status...", "Git &Status..."),

        ["Menu.RepoTree.Checkout"] = ("체크아웃", "Checkout"),
        ["Menu.RepoTree.CopyName"] = ("이름 복사", "Copy Name"),
        ["Menu.ExportSummary"] = ("요약 내보내기", "Export Summary"),
        ["Menu.ExportSummary.Bar"] = ("요약 내보내기", "Export &Summary"),
        ["Menu.ExportSummary.Pdf"] = ("PDF (.pdf)", "PDF (.pdf)"),
        ["Menu.ExportSummary.Word"] = ("Word (.docx)", "Word (.docx)"),
        ["Menu.ExportSummary.Markdown"] = ("Markdown (.md)", "Markdown (.md)"),

        ["Menu.RepoFiles.ShowLog"] = ("로그 보기", "Show Log"),
        ["Menu.RepoFiles.NewFile"] = ("새 파일...", "New File..."),
        ["Menu.RepoFiles.NewFolder"] = ("새 폴더...", "New Folder..."),
        ["Menu.RepoFiles.Delete"] = ("삭제", "Delete"),
        ["Menu.RepoFiles.CopyPath"] = ("경로 복사", "Copy Path"),
        ["Menu.RepoFiles.ClearFilter"] = ("모든 커밋 보기", "Show All Commits"),

        ["Commit.SelectPrompt"] = ("커밋을 선택하면 상세 정보가 표시됩니다.", "Select a commit to see its details."),
        ["Repo.NoRepository"] = ("열린 저장소 없음", "No repository open"),

        ["ChangeKind.Added"] = ("추가됨", "Added"),
        ["ChangeKind.Modified"] = ("수정됨", "Modified"),
        ["ChangeKind.Deleted"] = ("삭제됨", "Deleted"),
        ["ChangeKind.Renamed"] = ("이름변경", "Renamed"),
        ["ChangeKind.Copied"] = ("복사됨", "Copied"),
        ["ChangeKind.Unmodified"] = ("변경 없음", "Unmodified"),

        ["Status.Path.Unchanged"] = ("변경 없음", "Unchanged"),
        ["Status.Path.UnchangedFolder"] = ("변경 없음 (이 폴더)", "Unchanged (no changes in this folder)"),
        ["Status.Path.ContainsChanges"] = ("변경 포함", "Contains changes"),
        ["Status.Path.ContainsUnpushed"] = ("Push 안 된 커밋 포함", "Contains unpushed commits"),
        ["Status.Path.Unpushed"] = ("커밋됨 (Push 안 됨)", "Committed (not pushed)"),
        ["Status.Path.Ignored"] = ("무시됨", "Ignored"),
        ["Status.Path.IgnoredFolder"] = ("무시된 폴더", "Ignored folder"),
        ["Status.Path.Deleted"] = ("삭제됨", "Deleted"),
        ["Status.Path.Mixed"] = ("혼합", "Mixed"),
        ["Status.Path.Changed"] = ("변경됨", "Changed"),
        ["Status.Path.Unavailable"] = ("상태: 사용 불가 (읽기 전용 저장소)", "Status: Unavailable (read-only repository view)"),
        ["Status.Tooltip.Staged"] = ("스테이징", "Staged"),
        ["Status.Tooltip.WorkTree"] = ("작업 트리", "Work tree"),
        ["Status.Tooltip.PushPending"] = ("Push: 대기 중", "Push: Pending"),
        ["Status.Tooltip.ListedInGitignore"] = (".gitignore에 등록됨", "Listed in .gitignore"),

        ["GitCommit.Title"] = ("Git Commit", "Git Commit"),
        ["GitCommit.Category"] = ("카테고리", "Category"),
        ["GitCommit.Subject"] = ("제목", "Subject"),
        ["GitCommit.Body"] = ("본문", "Body"),
        ["GitCommit.Preview"] = ("미리보기", "Preview"),
        ["GitCommit.StagedPath"] = ("경로", "Path"),
        ["GitCommit.ManageCategories"] = ("관리...", "Manage..."),
        ["GitCommit.Commit"] = ("커밋", "Commit"),
        ["GitCommit.RemoveFromCommit"] = ("커밋에서 제거", "Remove from Commit"),
        ["GitCommit.RemovePath"] = ("경로 제거", "Remove Path"),
        ["GitCommit.StagedNone"] = ("스테이징된 파일 (남은 항목 없음)", "Staged files (none remaining)"),
        ["GitCommit.StagedOne"] = ("스테이징된 파일 (1개)", "Staged files (1 path)"),
        ["GitCommit.StagedMany"] = ("스테이징된 파일 ({0}개)", "Staged files ({0} paths)"),

        ["About.Title"] = ("MyGitWinV10 정보", "About MyGitWinV10"),
        ["About.Description"] = ("Git 기록, 브랜치, GitHub Release 뷰어입니다.\n커밋 그래프, Diff, 릴리스를 탐색합니다.", "A Git history, branch, and GitHub Release viewer.\nBrowse commit graphs, inspect diffs, and explore releases."),
        ["About.Version"] = ("버전 {0}", "Version {0}"),

        ["Dialog.NewFile.Title"] = ("새 파일", "New File"),
        ["Dialog.NewFile.Prompt"] = ("{0}에 만들 파일 이름:", "File name in {0}:"),
        ["Dialog.NewFolder.Title"] = ("새 폴더", "New Folder"),
        ["Dialog.NewFolder.Prompt"] = ("{0}에 만들 폴더 이름:", "Folder name in {0}:"),
        ["Dialog.DeleteFile"] = ("파일 '{0}'을(를) 삭제하시겠습니까?\n되돌릴 수 없습니다.", "Delete file '{0}'?\nThis cannot be undone."),
        ["Dialog.DeleteFolder"] = ("폴더 '{0}'과(와) 내용을 모두 삭제하시겠습니까?\n되돌릴 수 없습니다.", "Delete folder '{0}' and everything inside it?\nThis cannot be undone."),
        ["Dialog.Delete.Title"] = ("삭제", "Delete"),

        ["Msg.OpenFileUnavailable"] = ("작업 트리에서 파일을 사용할 수 없습니다.", "The file is not available in the working tree."),
        ["Msg.GitAdd.NoChanges"] = ("스테이징할 변경 사항이 없습니다.", "No changes are available to stage."),
        ["Msg.GitAdd.NoneStaged"] = ("스테이징된 변경 사항이 없습니다.", "No changes were staged."),
        ["Msg.GitCommit.StageFirst"] = ("커밋하기 전에 Git Add로 변경 사항을 스테이징하세요.", "Stage changes with Git Add before committing."),
        ["Msg.GitCommit.NoneRemaining"] = ("커밋할 스테이징된 파일이 없습니다.", "No staged files remain to commit."),
        ["Msg.GitCommit.EnterCategory"] = ("커밋 카테고리를 입력하거나 선택하세요.", "Enter or select a commit category."),
        ["Msg.GitCommit.EnterMessage"] = ("커밋 메시지를 입력하세요.", "Enter a commit message."),
        ["Msg.GitAdd.SelectPath"] = ("스테이징할 경로를 하나 이상 선택하세요.", "Select at least one path to stage."),
        ["Msg.GitDiscard.Confirm"] = ("{0}의 커밋되지 않은 변경 사항을 버리시겠습니까?\n되돌릴 수 없습니다.", "Discard uncommitted changes in {0}?\nThis cannot be undone."),
        ["Msg.Cancelled"] = ("작업이 취소되었습니다.", "The operation was cancelled."),
        ["Msg.CancelledTitle"] = ("{0} 취소됨", "{0} Cancelled"),
        ["Msg.ExportNeedRepo"] = ("요약을 내보내려면 먼저 저장소를 여세요.", "Open a repository before exporting a summary."),

        ["Menu.ExportSummary.Tip"] = ("저장소 요약을 보고서로 내보냅니다", "Export repository summary as a report"),
        ["Toolbar.ExportSummary.Button"] = ("요약 내보내기", "Export Summary"),
        ["Repo.RemoteView"] = ("(원격 보기)", "(remote view)"),
        ["Repo.Counts"] = ("{0}개 브랜치 · {1}개 태그", "{0} branches · {1} tags"),
        ["Status.Ready"] = ("준비", "Ready"),
        ["Status.ShowingAllCommits"] = ("모든 커밋 표시", "Showing all commits"),
        ["Status.ShowingCommitsFor"] = ("{0}의 커밋 표시", "Showing commits for {0}"),

        ["Status.Tooltip.StatusLine"] = ("상태: {0}", "Status: {0}"),
        ["Status.Tooltip.StagedLine"] = ("스테이징: {0}", "Staged: {0}"),
        ["Status.Tooltip.WorkTreeLine"] = ("작업 트리: {0}", "Work tree: {0}"),
        ["Status.Tooltip.DeletedStatus"] = ("상태: 삭제됨", "Status: Deleted"),
        ["Status.Tooltip.WorkTreeDeleted"] = ("작업 트리: 삭제됨", "Work tree: Deleted"),

        ["Error.OpenRepository"] = ("저장소 열기 실패", "Open Repository Failed"),
        ["Error.BrowseRemote"] = ("원격 둘러보기 실패", "Browse Remote Failed"),
        ["Error.Export"] = ("내보내기 실패", "Export Failed"),
        ["Error.ExportSummary"] = ("요약 내보내기", "Export Summary"),
        ["Error.Checkout"] = ("체크아웃 실패", "Checkout Failed"),
        ["Error.LoadHistory"] = ("커밋 기록 불러오기 실패", "Load Commit History Failed"),
        ["Error.LoadCommitDetails"] = ("커밋 상세 불러오기 실패", "Load Commit Details Failed"),
        ["Error.ExternalDiff"] = ("외부 Diff 실패", "External Diff Failed"),
        ["Error.LoadDiff"] = ("Diff 불러오기 실패", "Load Diff Failed"),
        ["Error.Delete"] = ("삭제 실패", "Delete Failed"),

        ["GitOp.Add"] = ("Git Add", "Git Add"),
        ["GitOp.AddComplete"] = ("Git Add 완료", "Git Add Complete"),
        ["GitOp.AddFailed"] = ("Git Add 실패", "Git Add Failed"),
        ["GitOp.ResetComplete"] = ("Git Reset 완료", "Git Reset Complete"),
        ["GitOp.ResetFailed"] = ("Git Reset 실패", "Git Reset Failed"),
        ["GitOp.Discard"] = ("Git Discard Changes", "Git Discard Changes"),
        ["GitOp.DiscardComplete"] = ("Git Discard 완료", "Git Discard Complete"),
        ["GitOp.DiscardFailed"] = ("Git Discard 실패", "Git Discard Failed"),
        ["GitOp.Commit"] = ("Git Commit", "Git Commit"),
        ["GitOp.CommitComplete"] = ("Git Commit 완료", "Git Commit Complete"),
        ["GitOp.CommitFailed"] = ("Git Commit 실패", "Git Commit Failed"),
        ["GitOp.FetchComplete"] = ("Git Fetch 완료", "Git Fetch Complete"),
        ["GitOp.FetchFailed"] = ("Git Fetch 실패", "Git Fetch Failed"),
        ["GitOp.PullComplete"] = ("Git Pull 완료", "Git Pull Complete"),
        ["GitOp.PullFailed"] = ("Git Pull 실패", "Git Pull Failed"),
        ["GitOp.PushComplete"] = ("Git Push 완료", "Git Push Complete"),
        ["GitOp.PushFailed"] = ("Git Push 실패", "Git Push Failed"),
        ["GitOp.StashComplete"] = ("Git Stash 완료", "Git Stash Complete"),
        ["GitOp.StashFailed"] = ("Git Stash 실패", "Git Stash Failed"),
        ["GitOp.StashPopComplete"] = ("Git Stash Pop 완료", "Git Stash Pop Complete"),
        ["GitOp.StashPopFailed"] = ("Git Stash Pop 실패", "Git Stash Pop Failed"),
        ["GitOp.Fetch"] = ("Git Fetch", "Git Fetch"),
        ["GitOp.Pull"] = ("Git Pull", "Git Pull"),
        ["GitOp.Push"] = ("Git Push", "Git Push"),
        ["GitOp.Stash"] = ("Git Stash", "Git Stash"),
        ["GitOp.StashPop"] = ("Git Stash Pop", "Git Stash Pop"),
        ["GitOp.Status"] = ("Git Status", "Git Status"),

        ["GitAdd.Title"] = ("Git Add", "Git Add"),
        ["GitAdd.TitleScope"] = ("Git Add — {0}", "Git Add — {0}"),

        ["GitStatus.Title"] = ("Git Status", "Git Status"),
        ["GitStatus.TitleScope"] = ("Git Status — {0}", "Git Status — {0}"),
        ["GitStatus.Clean"] = ("작업 트리가 깨끗합니다.", "Working tree clean."),
        ["GitStatus.ChangedCount"] = ("변경된 경로 {0}개", "{0} changed path(s)"),
        ["Column.GitStatus.Path"] = ("경로", "Path"),
        ["Column.GitStatus.Staged"] = ("스테이징", "Staged"),
        ["Column.GitStatus.WorkTree"] = ("작업 트리", "Work Tree"),

        ["GitOp.OpenFile"] = ("파일 열기", "Open File"),
        ["Error.OpenFile"] = ("파일 열기 실패", "Open File Failed"),
        ["Repo.Root"] = ("(저장소 루트)", "(repository root)"),
        ["Menu.RepoFiles.Delete.Tip"] = ("선택한 파일 또는 폴더를 디스크에서 삭제합니다", "Delete the selected file or folder from disk"),

        // Status bar
        ["Status.OpeningLastRemote"] = ("마지막 원격 저장소 여는 중...", "Opening last remote repository..."),
        ["Status.OpeningLastLocal"] = ("마지막 저장소 여는 중...", "Opening last repository..."),
        ["Status.OpeningRepo"] = ("저장소 여는 중...", "Opening repository..."),
        ["Status.OpeningCloned"] = ("클론된 저장소 여는 중...", "Opening cloned repository..."),
        ["Status.OpeningRemote"] = ("원격 저장소 여는 중...", "Opening remote repository..."),
        ["Status.Branch"] = ("브랜치: {0}", "Branch: {0}"),
        ["Status.BranchRemote"] = ("브랜치: {0} (원격 보기)", "Branch: {0} (remote view)"),
        ["Status.RefreshingTree"] = ("브랜치, 태그, 릴리스 새로고침 중...", "Refreshing branches, tags, and releases..."),
        ["Status.RefreshingGraph"] = ("커밋 그래프 새로고침 중...", "Refreshing commit graph..."),
        ["Status.LoadingReleases"] = ("GitHub 릴리스 불러오는 중...", "Loading GitHub releases..."),
        ["Status.CheckingOut"] = ("{0} 체크아웃 중...", "Checking out {0}..."),
        ["Status.CheckoutCancelled"] = ("체크아웃 취소됨", "Checkout cancelled"),
        ["Status.StagedOne"] = ("스테이징됨: {0}", "Staged {0}"),
        ["Status.StagedMany"] = ("{0}개 경로 스테이징됨", "Staged {0} paths"),
        ["Status.UnstagedAll"] = ("모든 변경 사항 스테이징 해제됨", "Unstaged all changes"),
        ["Status.UnstagedPath"] = ("스테이징 해제됨: {0}", "Unstaged {0}"),
        ["Status.DiscardedAll"] = ("모든 커밋되지 않은 변경 사항 버림", "Discarded all uncommitted changes"),
        ["Status.DiscardedPath"] = ("변경 사항 버림: {0}", "Discarded changes in {0}"),
        ["Status.Committed"] = ("커밋됨: {0}", "Committed {0}"),
        ["Status.Fetched"] = ("origin에서 가져옴", "Fetched from origin"),
        ["Status.FetchCancelled"] = ("Fetch 취소됨", "Fetch cancelled"),
        ["Status.Pulled"] = ("{0}을(를) origin에서 Pull함", "Pulled {0} from origin"),
        ["Status.PullCancelled"] = ("Pull 취소됨", "Pull cancelled"),
        ["Status.Pushed"] = ("{0}을(를) origin에 Push함", "Pushed {0} to origin"),
        ["Status.PushCancelled"] = ("Push 취소됨", "Push cancelled"),
        ["Status.Stashed"] = ("커밋되지 않은 변경 사항 Stash함", "Stashed uncommitted changes"),
        ["Status.StashApplied"] = ("최신 Stash 적용됨", "Applied latest stash"),
        ["Status.Created"] = ("생성됨: {0}", "Created {0}"),
        ["Status.Deleted"] = ("삭제됨: {0}", "Deleted {0}"),
        ["Status.AddedGitignore"] = (".gitignore에 {0} 추가됨", "Added {0} to .gitignore"),
        ["Status.RemovedGitignoreOne"] = (".gitignore에서 {0} 제거됨", "Removed {0} from .gitignore"),
        ["Status.RemovedGitignoreMany"] = (".gitignore에서 {0}개 패턴 제거됨", "Removed {0} patterns from .gitignore"),
        ["Status.LoadingChanges"] = ("{0}  변경 사항 불러오는 중...", "{0}  Loading changes..."),
        ["Status.ExportedSummary"] = ("요약 내보냄: {0}", "Exported summary to {0}"),
        ["Status.ExportCancelled"] = ("내보내기 취소됨", "Export cancelled"),
        ["Status.ExportingCommit"] = ("커밋 {0} 내보내는 중... {1}%", "Exporting commit {0}... {1}%"),
        ["Status.ExportedCommit"] = ("{0}을(를) {1}에 내보냄", "Exported {0} to {1}"),
        ["Status.Cancelling"] = ("취소 중...", "Cancelling..."),
        ["Status.Complete"] = ("완료.", "Complete."),
        ["Status.Failed"] = ("실패.", "Failed."),
        ["Status.Cancelled"] = ("취소됨.", "Cancelled."),
        ["Status.Cloning"] = ("클론 중... {0}%", "Cloning... {0}%"),
        ["Status.Downloading"] = ("다운로드 중... {0}%", "Downloading... {0}%"),

        // Operation complete dialogs
        ["OpComplete.DefaultSummary"] = ("작업이 성공적으로 완료되었습니다.", "The operation completed successfully."),
        ["OpComplete.RepoOpened"] = ("저장소 열림", "Repository Opened"),
        ["OpComplete.RepoOpenedSummary"] = ("저장소가 성공적으로 열렸습니다.", "The repository was opened successfully."),
        ["OpComplete.CloneComplete"] = ("클론 완료", "Clone Complete"),
        ["OpComplete.CloneSummary"] = ("저장소가 성공적으로 클론되었습니다.", "The repository was cloned successfully."),
        ["OpComplete.RemoteBrowseReady"] = ("원격 둘러보기 준비됨", "Remote Browse Ready"),
        ["OpComplete.RemoteBrowseSummary"] = ("원격 저장소 기록을 둘러볼 준비가 되었습니다.", "The remote repository history is ready to browse."),
        ["OpComplete.ExportComplete"] = ("내보내기 완료", "Export Complete"),
        ["OpComplete.ExportSummary"] = ("저장소 요약이 성공적으로 내보내졌습니다.", "The repository summary was exported successfully."),
        ["OpComplete.ExportCommitSummary"] = ("커밋 스냅샷이 성공적으로 내보내졌습니다.", "The commit snapshot was exported successfully."),
        ["OpComplete.CheckoutComplete"] = ("체크아웃 완료", "Checkout Complete"),
        ["OpComplete.CheckoutSummary"] = ("브랜치가 성공적으로 체크아웃되었습니다.", "The branch was checked out successfully."),
        ["OpComplete.CopyDetails"] = ("세부정보 복사", "Copy Details"),
        ["OpComplete.Copied"] = ("복사됨", "Copied"),
        ["Detail.Format"] = ("형식", "Format"),
        ["Detail.File"] = ("파일", "File"),
        ["Detail.Folder"] = ("폴더", "Folder"),
        ["Detail.RemoteUrl"] = ("원격 URL", "Remote URL"),
        ["Detail.Pattern"] = ("패턴", "Pattern"),
        ["Detail.RemovedPatterns"] = ("제거된 패턴", "Removed patterns"),

        // Git operation summaries (titles keep English git command names)
        ["GitOp.ResetCompleteSummary"] = ("선택한 스테이징 변경 사항이 성공적으로 해제되었습니다.", "The selected staged changes were unstaged successfully."),
        ["GitOp.DiscardCompleteSummary"] = ("커밋되지 않은 변경 사항이 성공적으로 버려졌습니다.", "The uncommitted changes were discarded successfully."),
        ["GitOp.CommitCompleteSummary"] = ("스테이징된 변경 사항이 성공적으로 커밋되었습니다.", "The staged changes were committed successfully."),
        ["GitOp.FetchCompleteSummary"] = ("origin에서 업데이트를 성공적으로 가져왔습니다.", "Updates were fetched from origin successfully."),
        ["GitOp.PullCompleteSummary"] = ("origin에서 변경 사항을 성공적으로 Pull했습니다.", "Changes were pulled from origin successfully."),
        ["GitOp.PushCompleteSummary"] = ("커밋을 origin에 성공적으로 Push했습니다.", "Commits were pushed to origin successfully."),
        ["GitOp.StashCompleteSummary"] = ("커밋되지 않은 변경 사항이 성공적으로 Stash되었습니다.", "The uncommitted changes were stashed successfully."),
        ["GitOp.StashPopCompleteSummary"] = ("최신 Stash가 성공적으로 적용되었습니다.", "The latest stash was applied successfully."),
        ["GitOp.FetchProgress"] = ("origin에서 Fetch 중...", "Fetching from origin..."),
        ["GitOp.PullProgress"] = ("origin에서 Pull 중...", "Pulling from origin..."),
        ["GitOp.PushProgress"] = ("origin에 Push 중...", "Pushing to origin..."),

        // .gitignore operations
        ["Gitignore.RemoveTitle"] = (".gitignore에서 제거", "Remove from .gitignore"),
        ["Gitignore.RemoveSummary"] = ("선택한 경로가 .gitignore에서 제거되었습니다.", "The selected path was removed from .gitignore."),
        ["Gitignore.RemoveNotFound"] = ("선택한 경로와 일치하는 .gitignore 항목을 찾을 수 없습니다.", "No matching entry was found in .gitignore for the selected path."),
        ["Gitignore.RemoveFailed"] = (".gitignore 제거 실패", "Remove from .gitignore Failed"),
        ["Gitignore.AddTitle"] = (".gitignore에 추가됨", "Added to .gitignore"),
        ["Gitignore.AddSummary"] = ("선택한 경로가 .gitignore에 추가되었습니다.", "The selected path was added to .gitignore."),
        ["Gitignore.AddFailed"] = (".gitignore 추가 실패", "Add to .gitignore Failed"),

        // Git Add dialog
        ["GitAdd.SummaryNone"] = ("스테이징할 경로가 선택되지 않았습니다.", "No paths selected to stage."),
        ["GitAdd.SummaryOne"] = ("1개 경로가 스테이징됩니다. 포함하지 않을 경로는 제거하세요.", "1 path will be staged. Remove any paths you do not want to include."),
        ["GitAdd.SummaryMany"] = ("{0}개 경로가 스테이징됩니다. 포함하지 않을 경로는 제거하세요.", "{0} paths will be staged. Remove any paths you do not want to include."),
        ["GitAdd.RemoveSelected"] = ("선택 항목 제거", "Remove Selected"),
        ["GitAdd.Stage"] = ("스테이징", "Stage"),
        ["GitAdd.CompleteTitle"] = ("Git Add Complete", "Git Add Complete"),
        ["GitAdd.CompleteTitleScope"] = ("Git Add Complete — {0}", "Git Add Complete — {0}"),
        ["GitAdd.CompleteOne"] = ("1개 경로가 스테이징되었습니다.", "1 path was staged."),
        ["GitAdd.CompleteMany"] = ("{0}개 경로가 스테이징되었습니다.", "{0} paths were staged."),
        ["Column.Status"] = ("상태", "Status"),

        // Git operation detail labels
        ["Detail.Repository"] = ("저장소", "Repository"),
        ["Detail.Branch"] = ("브랜치", "Branch"),
        ["Detail.Path"] = ("경로", "Path"),
        ["Detail.UnstagedPaths"] = ("스테이징 해제된 경로", "Unstaged paths"),
        ["Detail.DiscardedChanges"] = ("버린 변경 사항", "Discarded changes"),
        ["Detail.Commit"] = ("커밋", "Commit"),
        ["Detail.ShortSha"] = ("짧은 SHA", "Short SHA"),
        ["Detail.Author"] = ("작성자", "Author"),
        ["Detail.Date"] = ("날짜", "Date"),
        ["Detail.Message"] = ("메시지", "Message"),
        ["Detail.Parent"] = ("부모", "Parent"),
        ["Detail.ChangedFiles"] = ("변경된 파일", "Changed files"),
        ["Detail.Remote"] = ("원격", "Remote"),
        ["Detail.Updates"] = ("업데이트", "Updates"),
        ["Detail.Result"] = ("결과", "Result"),
        ["Detail.HeadBefore"] = ("이전 HEAD", "HEAD before"),
        ["Detail.HeadAfter"] = ("이후 HEAD", "HEAD after"),
        ["Detail.MergeCommit"] = ("머지 커밋", "Merge commit"),
        ["Detail.Ref"] = ("Ref", "Ref"),
        ["Detail.CommitsPushed"] = ("Push된 커밋", "Commits pushed"),
        ["Detail.StashMessage"] = ("Stash 메시지", "Stash message"),
        ["Detail.StashEntries"] = ("Stash 항목", "Stash entries"),
        ["Detail.StashedChanges"] = ("Stash된 변경 사항", "Stashed changes"),
        ["Detail.AppliedStash"] = ("적용된 Stash", "Applied stash"),
        ["Detail.RemainingStashes"] = ("남은 Stash", "Remaining stashes"),
        ["Detail.Value.Detached"] = ("(분리됨)", "(detached)"),
        ["Detail.Value.RootCommit"] = ("(루트 커밋)", "(root commit)"),
        ["Detail.Value.Unknown"] = ("(알 수 없음)", "(unknown)"),
        ["Detail.Value.None"] = ("(없음)", "(none)"),
        ["Detail.Value.Repository"] = ("(저장소 전체)", "(repository)"),
        ["Detail.Value.BareRepository"] = ("(bare 저장소)", "(bare repository)"),
        ["Detail.Value.NotConfigured"] = ("(설정 안 됨)", "(not configured)"),
        ["Detail.Value.UpToDate"] = ("모든 커밋이 최신 상태입니다 (새 커밋 없음).", "Everything up-to-date (no new commits)."),
        ["Detail.Value.RemoteUpToDate"] = ("원격 추적 브랜치가 이미 최신 상태입니다.", "Remote-tracking branches are already up to date."),
        ["Detail.Value.AndMore"] = ("  • ... 외 {0}개 더", "  • ... and {0} more"),
        ["Merge.UpToDate"] = ("이미 최신 상태", "Already up to date"),
        ["Merge.FastForward"] = ("Fast-forward", "Fast-forward"),
        ["Merge.NonFastForward"] = ("머지 커밋 생성됨", "Merge commit created"),
        ["Merge.Conflicts"] = ("충돌 해결 후 완료", "Completed with conflicts resolved"),

        // Clone / Browse remote
        ["Clone.Title"] = ("저장소 클론", "Clone Repository"),
        ["Clone.UrlLabel"] = ("저장소 URL", "Repository URL"),
        ["Clone.DestLabel"] = ("대상 폴더", "Destination Folder"),
        ["Clone.BrowseFolder"] = ("찾아보기...", "Browse..."),
        ["Clone.CloneButton"] = ("클론", "Clone"),
        ["Clone.StopButton"] = ("중지", "Stop"),
        ["Clone.FolderPrompt"] = ("클론할 빈 대상 폴더를 선택하세요", "Select an empty destination folder for the clone"),
        ["Clone.NeedUrlAndFolder"] = ("저장소 URL과 대상 폴더를 모두 입력하세요.", "Please enter both a repository URL and a destination folder."),
        ["Clone.Failed"] = ("클론 실패", "Clone Failed"),
        ["Browse.Title"] = ("원격 저장소 둘러보기", "Browse Remote Repository"),
        ["Browse.Info"] = ("로컬 폴더를 선택하지 않고 커밋 기록을 둘러볼 수 있도록 임시 캐시에 다운로드합니다.", "Downloads commit history to a temporary cache so you can browse logs and diffs without choosing a local folder."),
        ["Browse.BrowseButton"] = ("둘러보기", "Browse"),
        ["Browse.NeedUrl"] = ("저장소 URL을 입력하세요.", "Please enter a repository URL."),
        ["Browse.Failed"] = ("원격 둘러보기 실패", "Browse Remote Failed"),
        ["Dialog.SelectRepoFolder"] = ("Git 저장소 폴더를 선택하세요", "Select a Git repository folder"),
        ["App.Title"] = ("MyGit", "MyGit"),

        // Commit categories
        ["Categories.Title"] = ("커밋 카테고리", "Commit Categories"),
        ["Categories.ListLabel"] = ("카테고리", "Categories"),
        ["Categories.EditLabel"] = ("카테고리", "Category"),
        ["Categories.Add"] = ("추가", "Add"),
        ["Categories.Update"] = ("수정", "Update"),
        ["Categories.Remove"] = ("제거", "Remove"),
        ["Categories.Defaults"] = ("기본값", "Defaults"),
        ["Categories.AddTitle"] = ("카테고리 추가", "Add Category"),
        ["Categories.UpdateTitle"] = ("카테고리 수정", "Update Category"),
        ["Categories.RemoveTitle"] = ("카테고리 제거", "Remove Category"),
        ["Categories.EnterName"] = ("카테고리 이름을 입력하세요.", "Enter a category name."),
        ["Categories.AlreadyExists"] = ("이미 존재하는 카테고리입니다.", "That category already exists."),
        ["Categories.SelectToUpdate"] = ("수정할 카테고리를 선택하세요.", "Select a category to update."),
        ["Categories.SelectToRemove"] = ("제거할 카테고리를 선택하세요.", "Select a category to remove."),
        ["Categories.OneRequired"] = ("최소 하나의 카테고리가 필요합니다.", "At least one category is required."),
        ["Categories.NeedOne"] = ("카테고리를 하나 이상 추가하세요.", "Add at least one category."),

        // Credentials
        ["Credentials.Title"] = ("Git 인증", "Git Credentials"),
        ["Credentials.Info"] = ("이 원격 저장소는 인증이 필요합니다.", "This remote requires authentication."),
        ["Credentials.Username"] = ("사용자 이름", "Username"),
        ["Credentials.Password"] = ("비밀번호 또는 Personal Access Token", "Password or Personal Access Token"),
        ["Credentials.Pat"] = ("Personal Access Token (PAT)", "Personal Access Token (PAT)"),
        ["Credentials.PatHintGitHub"] = ("GitHub는 더 이상 계정 비밀번호를 사용하지 않습니다 — github.com/settings/tokens에서 PAT를 사용하세요\n(로그인 비밀번호가 아닙니다).", "GitHub no longer accepts your account password here — use a PAT\nfrom github.com/settings/tokens (not your login password)."),
        ["Credentials.PatHintGeneric"] = ("호스트 설정에 따라 계정 비밀번호 또는\nPersonal Access Token을 사용할 수 있습니다.", "This host accepts either your account password or a personal\naccess token, depending on how it is configured."),

        // Error dialog
        ["Error.DefaultSummary"] = ("오류가 발생했습니다.", "An error occurred."),
        ["Error.CreateFile"] = ("파일 만들기 실패", "Create File Failed"),
        ["Error.CreateFolder"] = ("폴더 만들기 실패", "Create Folder Failed"),

        // Export commit
        ["Export.CommitFolderPrompt"] = ("커밋 {0}을(를) 내보낼 폴더를 선택하세요", "Select a folder to export commit {0} into."),
        ["Export.CommitTitle"] = ("커밋 내보내기", "Export Commit"),
        ["Export.FolderNotEmpty"] = ("폴더가 비어 있지 않습니다:\n{0}\n\n기존 파일이 덮어쓰기될 수 있습니다. 계속하시겠습니까?", "The folder is not empty:\n{0}\n\nExisting files may be overwritten. Continue?"),
        ["Export.SummaryTitle"] = ("저장소 요약 내보내기", "Export Repository Summary"),
        ["Export.FilterPdf"] = ("PDF 문서 (*.pdf)|*.pdf", "PDF document (*.pdf)|*.pdf"),
        ["Export.FilterWord"] = ("Word 문서 (*.docx)|*.docx", "Word document (*.docx)|*.docx"),
        ["Export.FilterMarkdown"] = ("Markdown 문서 (*.md)|*.md", "Markdown document (*.md)|*.md"),

        // Progress
        ["Progress.Working"] = ("작업 중...", "Working..."),
        ["Progress.Stop"] = ("중지", "Stop"),
        ["Progress.Stopping"] = ("중지 중...", "Stopping..."),

        // Report preview
        ["Preview.Title"] = ("보고서 미리보기 — {0}", "Report Preview — {0}"),
        ["Preview.Subtitle"] = ("{0}  ·  생성 {1:yyyy-MM-dd HH:mm:ss}", "{0}  ·  Generated {1:yyyy-MM-dd HH:mm:ss}"),
        ["Preview.ReportTitle"] = ("저장소 요약", "Report Preview"),
        ["Preview.ExportPdf"] = ("PDF 내보내기", "Export PDF"),
        ["Preview.ExportWord"] = ("Word 내보내기", "Export Word"),
        ["Preview.ExportMarkdown"] = ("Markdown 내보내기", "Export Markdown"),
        ["Preview.RepoSummaryHeading"] = ("저장소 요약: {0}", "Repository Summary: {0}"),
        ["Preview.Charts"] = ("차트", "Charts"),
        ["Preview.HeadCommit"] = ("HEAD 커밋", "HEAD Commit"),

        ["GitCommit.BodyOptional"] = ("본문 (선택)", "Details (optional)"),
        ["GitCommit.RemoveSelected"] = ("선택 항목 제거", "Remove Selected"),
    };
}
