// Writes src/buildinfo.js with the version, build time and git revision so the
// About window can show exactly which build is running.
//   node scripts/build-info.mjs        (run automatically by start/dist/build:web)
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const git = (cmd) => {
  try { return execSync(`git ${cmd}`, { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim(); } catch { return ""; }
};
const info = {
  name: pkg.productName || "MyArchitecture",
  version: pkg.version,
  buildDate: new Date().toISOString(),
  commit: git("rev-parse --short HEAD") || "unknown",
  branch: git("rev-parse --abbrev-ref HEAD") || "unknown",
  dirty: git("status --porcelain -- .") !== "",
  builder: process.env.USERNAME || process.env.USER || "",
  node: process.version,
  author: "SHKWON",
  email: "knix008@naver.com",
};
const text = `// Generated by scripts/build-info.mjs — do not edit.\nexport const BUILD = ${JSON.stringify(info, null, 2)};\n`;
fs.writeFileSync(path.join(root, "src", "buildinfo.js"), text);
console.log(`build-info: ${info.name} ${info.version} (${info.commit}${info.dirty ? "+" : ""}, ${info.buildDate})`);
