namespace ReqTrace.Localization;

internal static class StringResources
{
    private static readonly Dictionary<string, string> Korean = new()
    {
        ["Menu_File"] = "파일(&F)",
        ["Menu_Edit"] = "편집(&E)",
        ["Menu_View"] = "보기(&V)",
        ["Menu_Tools"] = "도구(&T)",
        ["Menu_Help"] = "도움말(&H)",
        ["Menu_NewProject"] = "새 프로젝트(&N)",
        ["Menu_OpenProject"] = "프로젝트 열기(&O)...",
        ["Menu_Save"] = "저장(&S)",
        ["Menu_SaveAs"] = "다른 이름으로 저장(&A)...",
        ["Menu_ImportExcel"] = "Excel에서 가져오기(&I)...",
        ["Menu_ExportReport"] = "보고서 내보내기(&E)...",
        ["Menu_RecentProjects"] = "최근 프로젝트(&R)",
        ["Menu_LanguageSettings"] = "언어 설정(&L)",
        ["Menu_LanguageKorean"] = "한국어",
        ["Menu_LanguageEnglish"] = "English",
        ["Menu_Exit"] = "종료(&X)",
        ["Menu_AddRequirement"] = "요구사항 추가(&R)",
        ["Menu_EditRequirement"] = "요구사항 편집(&E)",
        ["Menu_DeleteRequirement"] = "요구사항 삭제(&D)",
        ["Menu_AddTestCase"] = "테스트 케이스 추가(&T)",
        ["Menu_EditTestCase"] = "테스트 케이스 편집(&C)",
        ["Menu_DeleteTestCase"] = "테스트 케이스 삭제(&A)",
        ["Menu_RecordTestRun"] = "테스트 실행 기록(&R)",
        ["Menu_GroupByCategory"] = "카테고리별 그룹(&C)",
        ["Menu_GroupByHierarchy"] = "계층별 그룹(&H)",
        ["Menu_Refresh"] = "새로 고침(&R)",
        ["Menu_SearchFilter"] = "검색 / 필터(&S)",
        ["Menu_TraceabilitySummary"] = "추적성 요약(&T)",
        ["Menu_Options"] = "옵션(&O)...",
        ["Dlg_Options"] = "옵션",
        ["Options_Language"] = "언어:",
        ["Options_ImportFolder"] = "기본 가져오기 폴더:",
        ["Options_ExportFolder"] = "기본 내보내기 폴더:",
        ["Options_ProjectFolder"] = "기본 프로젝트 폴더:",
        ["Menu_About"] = "정보(&A)",
        ["Menu_Database"] = "데이터베이스(&B)",
        ["Menu_ConnectDatabase"] = "데이터베이스 연결(&C)...",
        ["Menu_SaveToDatabase"] = "데이터베이스에 저장(&S)",
        ["Menu_LoadFromDatabase"] = "데이터베이스에서 불러오기(&L)",

        ["Tool_New"] = "새로 만들기",
        ["Tool_Open"] = "열기",
        ["Tool_Save"] = "저장",
        ["Tool_Import"] = "가져오기",
        ["Tool_Export"] = "내보내기",
        ["Tool_DbConnect"] = "DB 연결",
        ["Tool_DbSend"] = "DB로 보내기",
        ["Tool_DbReceive"] = "DB에서 받기",
        ["Tool_AddReq"] = "요구사항 추가",
        ["Tool_EditReq"] = "요구사항 편집",
        ["Tool_DeleteReq"] = "요구사항 삭제",
        ["Tool_AddTC"] = "테스트 케이스 추가",
        ["Tool_RecordRun"] = "실행 기록",

        ["Panel_Requirements"] = "요구사항",
        ["Panel_RequirementDetails"] = "요구사항 상세",
        ["Panel_TestCases"] = "테스트 케이스",

        ["Col_Code"] = "코드",
        ["Col_Title"] = "제목",
        ["Col_Description"] = "설명",
        ["Col_Category"] = "카테고리",
        ["Col_Priority"] = "우선순위",
        ["Col_RequirementStatus"] = "요구사항 상태",
        ["Col_TestStatus"] = "테스트 상태",
        ["Col_Source"] = "출처",
        ["Col_Parent"] = "상위",
        ["Col_Status"] = "상태",
        ["Col_Steps"] = "단계",
        ["Col_ExpectedResult"] = "예상 결과",
        ["Col_LatestStatus"] = "최근 상태",
        ["Col_LastRun"] = "최근 실행",
        ["Col_LastRunBy"] = "실행자",
        ["Col_Action"] = "동작",
        ["Col_ExpectedOutcome"] = "예상 결과",

        ["Detail_Code"] = "코드:",
        ["Detail_Title"] = "제목:",
        ["Detail_Category"] = "카테고리:",
        ["Detail_Priority"] = "우선순위:",
        ["Detail_Status"] = "상태:",
        ["Detail_Description"] = "설명:",
        ["Btn_EditRequirement"] = "요구사항 편집...",

        ["Status_UnsavedProject"] = "(저장되지 않은 프로젝트)",
        ["Status_Requirements"] = "요구사항: {0}",
        ["Status_Coverage"] = "커버리지: {0:F0}%",
        ["Status_PassRate"] = "통과율: {0:F0}%",
        ["Status_DirtyMarker"] = " *",

        ["Placeholder_NoRequirements"] = "(요구사항 없음)",
        ["Placeholder_NoRequirementsHint"] = "파일 > Excel에서 가져오기 또는 편집 > 요구사항 추가",

        ["Common_None"] = "(없음)",
        ["Common_OK"] = "확인",
        ["Common_Cancel"] = "취소",
        ["Common_Close"] = "닫기",
        ["Common_Validation"] = "유효성 검사",
        ["Common_ConfirmDelete"] = "삭제 확인",
        ["Common_Browse"] = "찾아보기...",
        ["Common_Export"] = "내보내기",
        ["Common_Import"] = "가져오기",
        ["Common_CopyToClipboard"] = "클립보드에 복사",

        ["Filter_Project"] = "요구사항 프로젝트 (*.reqtproj)|*.reqtproj|모든 파일 (*.*)|*.*",
        ["Filter_Excel"] = "Excel 파일 (*.xlsx)|*.xlsx",
        ["Filter_AllFiles"] = "모든 파일 (*.*)|*.*",

        ["DefaultProjectName"] = "새 프로젝트",

        ["Msg_UnsavedChanges"] = "저장하지 않은 변경 사항이 있습니다.\r\n\r\n예: 저장 후 계속\r\n아니오: 저장하지 않고 계속\r\n취소: 작업 취소",
        ["Msg_UnsavedChangesTitle"] = "저장되지 않은 변경 사항",
        ["Msg_NewProjectTitle"] = "새 프로젝트",
        ["Msg_ProjectNamePrompt"] = "프로젝트 이름:",
        ["Msg_OpenProjectFailed"] = "프로젝트 열기 실패",
        ["Msg_SaveProjectFailed"] = "프로젝트 저장 실패",
        ["Msg_DeleteRequirement"] = "요구사항 '{0} - {1}' 및 모든 테스트 케이스를 삭제하시겠습니까?",
        ["Msg_DeleteTestCase"] = "테스트 케이스 '{0} - {1}'을(를) 삭제하시겠습니까?",
        ["Msg_NoRequirementSelected"] = "먼저 요구사항을 선택하세요.",
        ["Msg_NoRequirementSelectedTitle"] = "선택된 요구사항 없음",
        ["Msg_NoTestCaseSelected"] = "먼저 테스트 케이스를 선택하세요.",
        ["Msg_NoTestCaseSelectedTitle"] = "선택된 테스트 케이스 없음",
        ["Msg_ValueRequired"] = "값을 입력해야 합니다.",
        ["Msg_TitleRequired"] = "제목은 필수입니다.",
        ["Msg_DuplicateCode"] = "코드 '{0}'은(는) 이미 다른 요구사항에서 사용 중입니다.",

        ["Msg_ImportFailed"] = "가져오기 실패",
        ["Msg_ImportOpenFailed"] = "'{0}' 파일을 열 수 없습니다. 다른 프로그램(예: Excel)에서 열려 있을 수 있습니다. 닫은 후 다시 시도하세요.",
        ["Msg_ImportReadFailed"] = "'{0}' 파일을 읽을 수 없습니다. 다른 프로그램(예: Excel)에서 열려 있을 수 있습니다. 닫은 후 다시 시도하세요.",
        ["Msg_DuplicateRequirement"] = "요구사항 '{0}'이(가) 이미 존재합니다. 덮어쓰시겠습니까?",
        ["Msg_DuplicateRequirementsBatch"] = "가져온 요구사항 중 {0}개가 이미 프로젝트에 있습니다.\r\n\r\n모두 덮어쓰시겠습니까?\r\n\r\n예: 중복 항목 모두 덮어쓰기\r\n아니오: 중복 항목은 건너뛰고 새 항목만 추가",
        ["Msg_DuplicateRequirementTitle"] = "중복 요구사항",
        ["Msg_ImportNoneImported"] = "Excel 파일에서 가져온 요구사항이 없습니다. 헤더 행과 열 매핑(제목 필수)을 확인하세요.",
        ["Msg_ImportNoneAdded"] = "추가된 요구사항이 없습니다. 기존 항목은 그대로 유지되었습니다.",
        ["Msg_ImportTitle"] = "가져오기",
        ["Msg_ImportSummary"] = "{0}개 행 처리, {1}개 건너뜀, {2}개 요구사항 추가{3}",
        ["Msg_ImportSummaryWithTests"] = " (자동 생성 테스트 케이스 {0}개 포함).",
        ["Msg_ImportSummaryEnd"] = ".",
        ["Msg_ImportSummaryTitle"] = "가져오기 요약",
        ["Msg_ImportWarningsTitle"] = "가져오기 경고",
        ["Msg_ImportWarnings"] = "가져오기가 {0}개의 경고와 함께 완료되었습니다:\n\n{1}",
        ["Msg_TitleColumnRequired"] = "제목 열을 매핑해야 합니다.",

        ["Msg_TraceabilitySummaryTitle"] = "추적성 요약",
        ["Msg_TraceabilitySummary"] = "전체 요구사항: {0}\n테스트가 있는 요구사항: {1}\n전체 테스트 케이스: {2}\n커버리지: {3:F1}%\n통과율: {4:F1}%",

        ["Msg_ExportFailed"] = "내보내기 실패",
        ["Msg_ExportWriteFailed"] = "'{0}' 파일을 쓸 수 없습니다. 다른 프로그램에서 열려 있을 수 있습니다. 닫은 후 다시 시도하세요.",
        ["Msg_ExportSelectFormat"] = "하나 이상의 형식을 선택하세요.",
        ["Msg_ExportFolderMissing"] = "출력 폴더가 존재하지 않습니다.",
        ["Msg_ExportCompleteTitle"] = "내보내기 완료",
        ["Msg_ExportComplete"] = "{0}개 파일을 다음 위치에 내보냈습니다:\n{1}\n\n폴더를 여시겠습니까?",

        ["Msg_UnexpectedError"] = "예기치 않은 오류",

        ["Dlg_AddRequirement"] = "요구사항 추가",
        ["Dlg_EditRequirement"] = "요구사항 편집",
        ["Dlg_AddTestCase"] = "테스트 케이스 추가",
        ["Dlg_EditTestCase"] = "테스트 케이스 편집",
        ["Dlg_RecordTestRun"] = "테스트 실행 기록 — {0}",
        ["Dlg_ImportExcel"] = "Excel에서 가져오기 — {0}",
        ["Dlg_ExportReport"] = "추적성 보고서 내보내기",
        ["Dlg_AboutTitle"] = "요구사항 추적 관리자 정보",
        ["Dlg_AboutText"] = "요구사항 추적 관리자\r\n버전 1.0\r\n\r\nExcel에서 요구사항을 가져오고, 테스트 케이스를 관리하며, 통과/실패 상태를 추적하고, Excel·Word·Markdown·PDF로 추적성 보고서를 내보냅니다.\r\n\r\n사용 기술:\r\n  - ClosedXML (Excel)\r\n  - DocumentFormat.OpenXml (Word)\r\n  - QuestPDF, Community license (PDF)",
        ["Dlg_ProgressImportTitle"] = "Excel에서 가져오는 중",
        ["Dlg_ProgressImportMessage"] = "'{0}' 읽는 중...",

        ["Import_Sheet"] = "시트:",
        ["Import_HeaderRow"] = "헤더 행:",
        ["Import_Preview"] = "미리보기:",
        ["Import_ColumnMapping"] = "열 매핑:",
        ["Import_Code"] = "코드:",
        ["Import_Title"] = "제목:",
        ["Import_Description"] = "설명:",
        ["Import_Category"] = "카테고리:",
        ["Import_Priority"] = "우선순위:",
        ["Import_Status"] = "상태:",
        ["Import_Source"] = "출처:",
        ["Import_ParentCode"] = "상위 코드:",
        ["Import_GenerateIds"] = "코드가 없으면 ID 자동 생성",
        ["Import_GenerateTestCases"] = "제목/설명에서 테스트 케이스 자동 생성 (권장)",

        ["TcGen_Preconditions"] = "시스템이 정상적으로 사용 가능한 상태이다.",
        ["TcGen_PositiveTitle"] = "검증: {0} (정상 시나리오)",
        ["TcGen_NegativeTitle"] = "검증: {0} (잘못된/경계 입력)",
        ["TcGen_BoundaryTitle"] = "검증: {0} (경계 조건)",
        ["TcGen_DefaultExpected"] = "{0}이(가) 명세대로 동작한다.",
        ["TcGen_NegativeExpected"] = "잘못되거나 범위를 벗어난 입력은 거부되거나, 경계 경우가 오류나 충돌 없이 적절히 처리되어야 한다.",
        ["TcGen_BoundaryExpected"] = "경계값이 오프-by-one 또는 오버플로 오류 없이 올바르게 처리되어야 한다.",
        ["TcGen_StepExpected"] = "요구사항에 기술된 대로 동작한다.",
        ["TcGen_NegativeStepAction"] = "\"{0}\" 시나리오를 잘못되거나 범위를 벗어난 입력으로 시도한다.",
        ["TcGen_NegativeStepOutcome"] = "적절한 유효성 검사 메시지가 표시되고 시스템이 안정적으로 유지된다.",
        ["TcGen_BoundaryStepAction"] = "\"{0}\"의 최소 및 최대 지원 한계에서 동작을 확인한다.",
        ["TcGen_BoundaryStepOutcome"] = "두 한계 모두 오류 없이 올바르게 처리된다.",
        ["TcGen_FallbackStepAction"] = "요구사항 \"{0}\"에 기술된 시나리오를 실행한다.",
        ["TcGen_FallbackStepOutcome"] = "결과가 요구사항의 기대와 일치한다.",

        ["Export_Formats"] = "형식:",
        ["Export_Excel"] = "Excel (.xlsx)",
        ["Export_Word"] = "Word (.docx)",
        ["Export_Markdown"] = "Markdown (.md)",
        ["Export_Pdf"] = "PDF (.pdf)",
        ["Export_Scope"] = "범위:",
        ["Export_AllRequirements"] = "모든 요구사항",
        ["Export_OnlyWithTests"] = "테스트 케이스가 있는 요구사항만",
        ["Export_IncludeHistory"] = "전체 실행 이력 포함",
        ["Export_OutputFolder"] = "출력 폴더:",

        ["ReqEdit_Code"] = "코드:",
        ["ReqEdit_Title"] = "제목:",
        ["ReqEdit_Description"] = "설명:",
        ["ReqEdit_Category"] = "카테고리:",
        ["ReqEdit_Priority"] = "우선순위:",
        ["ReqEdit_Status"] = "상태:",
        ["ReqEdit_Source"] = "출처:",
        ["ReqEdit_Parent"] = "상위:",

        ["TcEdit_Code"] = "코드:",
        ["TcEdit_Title"] = "제목:",
        ["TcEdit_Preconditions"] = "전제 조건:",
        ["TcEdit_ExpectedResult"] = "예상 결과:",
        ["TcEdit_Steps"] = "단계:",
        ["TcEdit_AddStep"] = "+ 단계 추가",
        ["TcEdit_RemoveStep"] = "선택 단계 삭제",

        ["RunEdit_Status"] = "상태:",
        ["RunEdit_ExecutedBy"] = "실행자:",
        ["RunEdit_ExecutedAt"] = "실행 일시:",
        ["RunEdit_Build"] = "빌드/버전:",
        ["RunEdit_Notes"] = "메모:",
        ["RunEdit_History"] = "실행 이력:",

        ["Priority_Low"] = "낮음",
        ["Priority_Medium"] = "보통",
        ["Priority_High"] = "높음",
        ["Priority_Critical"] = "긴급",

        ["RequirementStatus_Draft"] = "초안",
        ["RequirementStatus_Approved"] = "승인됨",
        ["RequirementStatus_InProgress"] = "진행 중",
        ["RequirementStatus_Implemented"] = "구현됨",
        ["RequirementStatus_Deprecated"] = "폐기됨",

        ["TestRunStatus_NotRun"] = "미실행",
        ["TestRunStatus_Pass"] = "통과",
        ["TestRunStatus_Fail"] = "실패",
        ["TestRunStatus_Blocked"] = "차단됨",

        ["Title_DatabaseConnection"] = "데이터베이스 연결",
        ["Db_Provider"] = "데이터베이스 종류:",
        ["Db_Server"] = "서버:",
        ["Db_Port"] = "포트:",
        ["Db_Database"] = "데이터베이스:",
        ["Db_FilePath"] = "파일 경로:",
        ["Db_Username"] = "사용자:",
        ["Db_Password"] = "비밀번호:",
        ["Db_IntegratedSecurity"] = "Windows 통합 인증",
        ["Db_TestConnection"] = "연결 테스트",
        ["Msg_DbConnectionSuccess"] = "데이터베이스에 성공적으로 연결되었습니다.",
        ["Msg_DbConnectionFailed"] = "데이터베이스 연결 실패",
        ["Msg_DbSaveFailed"] = "데이터베이스 저장 실패",
        ["Msg_DbLoadFailed"] = "데이터베이스 불러오기 실패",
        ["Msg_DbSaveSuccessTitle"] = "저장 완료",
        ["Msg_DbSaveSuccess"] = "프로젝트가 데이터베이스에 저장되었습니다.",
        ["Msg_DbLoadSuccessTitle"] = "불러오기 완료",
        ["Msg_DbLoadSuccess"] = "프로젝트를 데이터베이스에서 불러왔습니다.",
        ["Msg_DbNotConnected"] = "먼저 데이터베이스에 연결하세요.",
    };

    private static readonly Dictionary<string, string> English = new()
    {
        ["Menu_File"] = "&File",
        ["Menu_Edit"] = "&Edit",
        ["Menu_View"] = "&View",
        ["Menu_Tools"] = "&Tools",
        ["Menu_Help"] = "&Help",
        ["Menu_NewProject"] = "&New Project",
        ["Menu_OpenProject"] = "&Open Project...",
        ["Menu_Save"] = "&Save",
        ["Menu_SaveAs"] = "Save &As...",
        ["Menu_ImportExcel"] = "&Import from Excel...",
        ["Menu_ExportReport"] = "&Export Report...",
        ["Menu_RecentProjects"] = "Recent &Projects",
        ["Menu_LanguageSettings"] = "&Language Settings",
        ["Menu_LanguageKorean"] = "한국어",
        ["Menu_LanguageEnglish"] = "English",
        ["Menu_Exit"] = "E&xit",
        ["Menu_AddRequirement"] = "Add &Requirement",
        ["Menu_EditRequirement"] = "&Edit Requirement",
        ["Menu_DeleteRequirement"] = "&Delete Requirement",
        ["Menu_AddTestCase"] = "Add &Test Case",
        ["Menu_EditTestCase"] = "Edit Test &Case",
        ["Menu_DeleteTestCase"] = "Delete Test C&ase",
        ["Menu_RecordTestRun"] = "&Record Test Run",
        ["Menu_GroupByCategory"] = "Group by &Category",
        ["Menu_GroupByHierarchy"] = "Group by &Hierarchy",
        ["Menu_Refresh"] = "&Refresh",
        ["Menu_SearchFilter"] = "&Search / Filter",
        ["Menu_TraceabilitySummary"] = "&Traceability Summary",
        ["Menu_Options"] = "&Options...",
        ["Dlg_Options"] = "Options",
        ["Options_Language"] = "Language:",
        ["Options_ImportFolder"] = "Default import folder:",
        ["Options_ExportFolder"] = "Default export folder:",
        ["Options_ProjectFolder"] = "Default project folder:",
        ["Menu_About"] = "&About",
        ["Menu_Database"] = "Data&base",
        ["Menu_ConnectDatabase"] = "&Connect to Database...",
        ["Menu_SaveToDatabase"] = "&Save to Database",
        ["Menu_LoadFromDatabase"] = "&Load from Database",

        ["Tool_New"] = "New",
        ["Tool_Open"] = "Open",
        ["Tool_Save"] = "Save",
        ["Tool_Import"] = "Import",
        ["Tool_Export"] = "Export",
        ["Tool_DbConnect"] = "DB Connect",
        ["Tool_DbSend"] = "Send to DB",
        ["Tool_DbReceive"] = "Load from DB",
        ["Tool_AddReq"] = "Add Requirement",
        ["Tool_EditReq"] = "Edit Requirement",
        ["Tool_DeleteReq"] = "Delete Requirement",
        ["Tool_AddTC"] = "Add Test Case",
        ["Tool_RecordRun"] = "Record Run",

        ["Panel_Requirements"] = "Requirements",
        ["Panel_RequirementDetails"] = "Requirement Details",
        ["Panel_TestCases"] = "Test Cases",

        ["Col_Code"] = "Code",
        ["Col_Title"] = "Title",
        ["Col_Description"] = "Description",
        ["Col_Category"] = "Category",
        ["Col_Priority"] = "Priority",
        ["Col_RequirementStatus"] = "Requirement Status",
        ["Col_TestStatus"] = "Test Status",
        ["Col_Source"] = "Source",
        ["Col_Parent"] = "Parent",
        ["Col_Status"] = "Status",
        ["Col_Steps"] = "Steps",
        ["Col_ExpectedResult"] = "Expected Result",
        ["Col_LatestStatus"] = "Latest Status",
        ["Col_LastRun"] = "Last Run",
        ["Col_LastRunBy"] = "Last Run By",
        ["Col_Action"] = "Action",
        ["Col_ExpectedOutcome"] = "Expected Outcome",

        ["Detail_Code"] = "Code:",
        ["Detail_Title"] = "Title:",
        ["Detail_Category"] = "Category:",
        ["Detail_Priority"] = "Priority:",
        ["Detail_Status"] = "Status:",
        ["Detail_Description"] = "Description:",
        ["Btn_EditRequirement"] = "Edit Requirement...",

        ["Status_UnsavedProject"] = "(unsaved project)",
        ["Status_Requirements"] = "Requirements: {0}",
        ["Status_Coverage"] = "Coverage: {0:F0}%",
        ["Status_PassRate"] = "Pass rate: {0:F0}%",
        ["Status_DirtyMarker"] = " *",

        ["Placeholder_NoRequirements"] = "(No requirements yet)",
        ["Placeholder_NoRequirementsHint"] = "Use File > Import from Excel or Edit > Add Requirement",

        ["Common_None"] = "(none)",
        ["Common_OK"] = "OK",
        ["Common_Cancel"] = "Cancel",
        ["Common_Close"] = "Close",
        ["Common_Validation"] = "Validation",
        ["Common_ConfirmDelete"] = "Confirm Delete",
        ["Common_Browse"] = "Browse...",
        ["Common_Export"] = "Export",
        ["Common_Import"] = "Import",
        ["Common_CopyToClipboard"] = "Copy to Clipboard",

        ["Filter_Project"] = "Requirement Project (*.reqtproj)|*.reqtproj|All files (*.*)|*.*",
        ["Filter_Excel"] = "Excel Files (*.xlsx)|*.xlsx",
        ["Filter_AllFiles"] = "All files (*.*)|*.*",

        ["DefaultProjectName"] = "New Project",

        ["Msg_UnsavedChanges"] = "You have unsaved changes.\r\n\r\nYes: Save and continue\r\nNo: Continue without saving\r\nCancel: Cancel",
        ["Msg_UnsavedChangesTitle"] = "Unsaved Changes",
        ["Msg_NewProjectTitle"] = "New Project",
        ["Msg_ProjectNamePrompt"] = "Project name:",
        ["Msg_OpenProjectFailed"] = "Open Project Failed",
        ["Msg_SaveProjectFailed"] = "Save Project Failed",
        ["Msg_DeleteRequirement"] = "Delete requirement '{0} - {1}' and all its test cases?",
        ["Msg_DeleteTestCase"] = "Delete test case '{0} - {1}'?",
        ["Msg_NoRequirementSelected"] = "Select a requirement first.",
        ["Msg_NoRequirementSelectedTitle"] = "No Requirement Selected",
        ["Msg_NoTestCaseSelected"] = "Select a test case first.",
        ["Msg_NoTestCaseSelectedTitle"] = "No Test Case Selected",
        ["Msg_ValueRequired"] = "Value cannot be empty.",
        ["Msg_TitleRequired"] = "Title is required.",
        ["Msg_DuplicateCode"] = "Code '{0}' is already used by another requirement.",

        ["Msg_ImportFailed"] = "Import Failed",
        ["Msg_ImportOpenFailed"] = "Could not open '{0}'. It may be open in another program (such as Excel). Close it and try again.",
        ["Msg_ImportReadFailed"] = "Could not read '{0}'. It may be open in another program (such as Excel). Close it and try again.",
        ["Msg_DuplicateRequirement"] = "Requirement '{0}' already exists. Overwrite it?",
        ["Msg_DuplicateRequirementsBatch"] = "{0} imported requirement(s) already exist in this project.\r\n\r\nOverwrite all of them?\r\n\r\nYes: overwrite all duplicates\r\nNo: skip duplicates and add only new items",
        ["Msg_DuplicateRequirementTitle"] = "Duplicate Requirement",
        ["Msg_ImportNoneImported"] = "No requirements were imported from the Excel file. Check the header row and column mapping (Title is required).",
        ["Msg_ImportNoneAdded"] = "No requirements were added. Existing items were kept unchanged.",
        ["Msg_ImportTitle"] = "Import",
        ["Msg_ImportSummary"] = "Processed {0} row(s), skipped {1}, added {2} requirement(s){3}",
        ["Msg_ImportSummaryWithTests"] = " with {0} auto-generated test case(s).",
        ["Msg_ImportSummaryEnd"] = ".",
        ["Msg_ImportSummaryTitle"] = "Import Summary",
        ["Msg_ImportWarningsTitle"] = "Import Warnings",
        ["Msg_ImportWarnings"] = "Import finished with {0} warning(s):\n\n{1}",
        ["Msg_TitleColumnRequired"] = "Title column must be mapped.",

        ["Msg_TraceabilitySummaryTitle"] = "Traceability Summary",
        ["Msg_TraceabilitySummary"] = "Total requirements: {0}\nRequirements with tests: {1}\nTotal test cases: {2}\nCoverage: {3:F1}%\nPass rate: {4:F1}%",

        ["Msg_ExportFailed"] = "Export Failed",
        ["Msg_ExportWriteFailed"] = "Could not write '{0}'. It may be open in another program. Close it and try again.",
        ["Msg_ExportSelectFormat"] = "Select at least one format.",
        ["Msg_ExportFolderMissing"] = "Output folder does not exist.",
        ["Msg_ExportCompleteTitle"] = "Export Complete",
        ["Msg_ExportComplete"] = "Exported {0} file(s) to:\n{1}\n\nOpen folder?",

        ["Msg_UnexpectedError"] = "Unexpected Error",

        ["Dlg_AddRequirement"] = "Add Requirement",
        ["Dlg_EditRequirement"] = "Edit Requirement",
        ["Dlg_AddTestCase"] = "Add Test Case",
        ["Dlg_EditTestCase"] = "Edit Test Case",
        ["Dlg_RecordTestRun"] = "Record Test Run — {0}",
        ["Dlg_ImportExcel"] = "Import from Excel — {0}",
        ["Dlg_ExportReport"] = "Export Traceability Report",
        ["Dlg_AboutTitle"] = "About Requirements Traceability Manager",
        ["Dlg_AboutText"] = "Requirements Traceability Manager\r\nVersion 1.0\r\n\r\nImport requirements from Excel, manage test cases, track pass/fail status, and export traceability reports to Excel, Word, Markdown, and PDF.\r\n\r\nBuilt with:\r\n  - ClosedXML (Excel)\r\n  - DocumentFormat.OpenXml (Word)\r\n  - QuestPDF, Community license (PDF)",
        ["Dlg_ProgressImportTitle"] = "Importing from Excel",
        ["Dlg_ProgressImportMessage"] = "Reading '{0}'...",

        ["Import_Sheet"] = "Sheet:",
        ["Import_HeaderRow"] = "Header row:",
        ["Import_Preview"] = "Preview:",
        ["Import_ColumnMapping"] = "Column Mapping:",
        ["Import_Code"] = "Code:",
        ["Import_Title"] = "Title:",
        ["Import_Description"] = "Description:",
        ["Import_Category"] = "Category:",
        ["Import_Priority"] = "Priority:",
        ["Import_Status"] = "Status:",
        ["Import_Source"] = "Source:",
        ["Import_ParentCode"] = "ParentCode:",
        ["Import_GenerateIds"] = "Generate IDs if missing",
        ["Import_GenerateTestCases"] = "Auto-generate test cases from Title/Description (recommended)",

        ["TcGen_Preconditions"] = "System is in a valid, ready-to-use state.",
        ["TcGen_PositiveTitle"] = "Verify: {0} (normal scenario)",
        ["TcGen_NegativeTitle"] = "Verify: {0} (invalid / edge-case input)",
        ["TcGen_BoundaryTitle"] = "Verify: {0} (boundary condition)",
        ["TcGen_DefaultExpected"] = "{0} behaves as specified.",
        ["TcGen_NegativeExpected"] = "Invalid or out-of-range input is rejected, or the edge case is handled gracefully without errors or crashes.",
        ["TcGen_BoundaryExpected"] = "Boundary values are processed correctly with no off-by-one or overflow errors.",
        ["TcGen_StepExpected"] = "Behaves as described in the requirement.",
        ["TcGen_NegativeStepAction"] = "Attempt the scenario for \"{0}\" using invalid or out-of-range input.",
        ["TcGen_NegativeStepOutcome"] = "An appropriate validation message is shown and the system remains stable.",
        ["TcGen_BoundaryStepAction"] = "Exercise \"{0}\" at its minimum and maximum supported limits.",
        ["TcGen_BoundaryStepOutcome"] = "Both limits are handled correctly without errors.",
        ["TcGen_FallbackStepAction"] = "Execute the scenario described by requirement \"{0}\".",
        ["TcGen_FallbackStepOutcome"] = "Result matches the requirement's expectation.",

        ["Export_Formats"] = "Formats:",
        ["Export_Excel"] = "Excel (.xlsx)",
        ["Export_Word"] = "Word (.docx)",
        ["Export_Markdown"] = "Markdown (.md)",
        ["Export_Pdf"] = "PDF (.pdf)",
        ["Export_Scope"] = "Scope:",
        ["Export_AllRequirements"] = "All Requirements",
        ["Export_OnlyWithTests"] = "Only Requirements With Test Cases",
        ["Export_IncludeHistory"] = "Include full run history",
        ["Export_OutputFolder"] = "Output folder:",

        ["ReqEdit_Code"] = "Code:",
        ["ReqEdit_Title"] = "Title:",
        ["ReqEdit_Description"] = "Description:",
        ["ReqEdit_Category"] = "Category:",
        ["ReqEdit_Priority"] = "Priority:",
        ["ReqEdit_Status"] = "Status:",
        ["ReqEdit_Source"] = "Source:",
        ["ReqEdit_Parent"] = "Parent:",

        ["TcEdit_Code"] = "Code:",
        ["TcEdit_Title"] = "Title:",
        ["TcEdit_Preconditions"] = "Preconditions:",
        ["TcEdit_ExpectedResult"] = "Expected Result:",
        ["TcEdit_Steps"] = "Steps:",
        ["TcEdit_AddStep"] = "+ Add Step",
        ["TcEdit_RemoveStep"] = "Remove Selected Step",

        ["RunEdit_Status"] = "Status:",
        ["RunEdit_ExecutedBy"] = "Executed By:",
        ["RunEdit_ExecutedAt"] = "Executed At:",
        ["RunEdit_Build"] = "Build/Version:",
        ["RunEdit_Notes"] = "Notes:",
        ["RunEdit_History"] = "Run History:",

        ["Priority_Low"] = "Low",
        ["Priority_Medium"] = "Medium",
        ["Priority_High"] = "High",
        ["Priority_Critical"] = "Critical",

        ["RequirementStatus_Draft"] = "Draft",
        ["RequirementStatus_Approved"] = "Approved",
        ["RequirementStatus_InProgress"] = "In Progress",
        ["RequirementStatus_Implemented"] = "Implemented",
        ["RequirementStatus_Deprecated"] = "Deprecated",

        ["TestRunStatus_NotRun"] = "Not Run",
        ["TestRunStatus_Pass"] = "Pass",
        ["TestRunStatus_Fail"] = "Fail",
        ["TestRunStatus_Blocked"] = "Blocked",

        ["Title_DatabaseConnection"] = "Database Connection",
        ["Db_Provider"] = "Database type:",
        ["Db_Server"] = "Server:",
        ["Db_Port"] = "Port:",
        ["Db_Database"] = "Database:",
        ["Db_FilePath"] = "File path:",
        ["Db_Username"] = "Username:",
        ["Db_Password"] = "Password:",
        ["Db_IntegratedSecurity"] = "Windows Integrated Security",
        ["Db_TestConnection"] = "Test Connection",
        ["Msg_DbConnectionSuccess"] = "Successfully connected to the database.",
        ["Msg_DbConnectionFailed"] = "Database Connection Failed",
        ["Msg_DbSaveFailed"] = "Save to Database Failed",
        ["Msg_DbLoadFailed"] = "Load from Database Failed",
        ["Msg_DbSaveSuccessTitle"] = "Save Complete",
        ["Msg_DbSaveSuccess"] = "Project saved to the database.",
        ["Msg_DbLoadSuccessTitle"] = "Load Complete",
        ["Msg_DbLoadSuccess"] = "Project loaded from the database.",
        ["Msg_DbNotConnected"] = "Connect to a database first.",
    };

    public static string Get(string key)
    {
        var table = LocalizationService.IsEnglish ? English : Korean;
        return table.TryGetValue(key, out var value) ? value : key;
    }
}
